### ISSUE TITLE
Launcher become unresponsive when trying to copy a large save directory

### ISSUE THREAD

**Issue by remyroy** [remyroy/CDDA-Game-Launcher#1]
When your save directory becomes large, the update process can take a while to complete when it tries to copy your save folder from your previous version to the new one on slow hard drives. The UI will become unresponsive because of this.

There is no workaround for this. Waiting for the launcher to become responsive again is the best way to solve this. Forcing the application to close will potentially make the save folder corrupted. The save folder of your previous version should still be fine.

Possible solutions are to include an option not to move or copy the save folder, use NTFS junctions to share the save folder between the previous version and the new one or add a better progress bar to see the progress of copying those files instead of making the UI unresponsive.

**Comment by remyroy** [comment]
[v0.3](https://github.com/remyroy/CDDA-Game-Launcher/releases) includes a setting that will prevent copying or moving the save directory as a good workaround for this.

**Comment by DanmakuDan** [comment]
Does python have asynchronous IO, or threads that could avoid the freezing?

**Comment by remyroy** [comment]
It does but that is not the problem. The progress needs to be communicated to the user which is just a bit more complicated. It will eventually be added.

**Comment by remyroy** [comment]
The last few commits include a good amount of features to help with this problem. Saves information is now displayed in the game group box. A warning is now displayed if the size of the save directory is larger than 150 MiB. There is a new progressive display for the copy step of the save directory showing more information and preventing the UI from becoming unresponsive.

Someone who has a large save directory and do not want to use the `Do not copy or move the save directory` option will be able to see the progress on the copying of the save directory and wait for it to complete.
