### ISSUE TITLE
[Suggestion] Copy over graveyard folder when updating.

### ISSUE THREAD

**Issue by Malkeus** [remyroy/CDDA-Game-Launcher#10]
This is entirely user generated content, I believe it does nifty things like letting you encounter the zombie version of a previous character.

**Comment by remyroy** [comment]
This is implemented in 69a5f3cd0e373815919ea09cd979bf761f4c4127 . It will be part of the next release.

**Comment by Malkeus** [comment]
You rock, thanks remyroy :)
