### ISSUE TITLE
Update Cataclysm++ link

### ISSUE THREAD

**Issue by ethanparkerr** [remyroy/CDDA-Game-Launcher#100]
Please use this link to download the mod as it is direct link and most up to date and no need to change it again:

https://github.com/Noctifer-de-Mortem/nocs_cata_mod/archive/master.zip

Even the latest release link here doesn't include those spelling fixes mentioned, but that's another problem

https://github.com/Noctifer-de-Mortem/nocs_cata_mod/releases

**Comment by remyroy** [comment]
@Noctifer-de-Mortem Is that good with you?

**Comment by Noctifer-de-Mortem** [comment]
They are correct saying that the incorrect file was uploaded but I simply need to update the file with the one provided in the link without having to make a change to your launcher.

**Comment by remyroy** [comment]
I will now be using the master link for Cataclysm++. It will be easier to download with the launcher. This is done with b442bdd2d5ee5fdbd39a37a253b2c6c727b5d729. It will be part of the next release.
