### ISSUE TITLE
Update CDDAXP?

### ISSUE THREAD

**Issue by ethanparkerr** [remyroy/CDDA-Game-Launcher#101]
http://smf.cataclysmdda.com/index.php?topic=11583.msg285839#msg285839

However compared to other zsfixed mods, this one has its name in modinfo modified:

ZSFIXED_C:DDA Extra Professions & Gears

**Comment by remyroy** [comment]
What is the issue exactly? Is the current C:DDA Extra Professions bad?

**Comment by ethanparkerr** [comment]
I don't know, haven't tried. EXTENDED_BUILDINGS and Parks and Rec Building Pack links in the launcher are similarly using ZSFIXED ones, that's why I posted this

**Comment by remyroy** [comment]
This is now included in d4dc766dbcc54269e2c4377829ad9f5dff60b8bf. It will be part of the next release.
