### ISSUE TITLE
"Fatal Error" when launching the launcher

### ISSUE THREAD

**Issue by defdeed** [remyroy/CDDA-Game-Launcher#109]
I downloaded the exe and whenever I try to open it all I get is a window saying Failed to execute script launcher

**Comment by remyroy** [comment]
Do you have a screenshot of that error? Do you see something interesting in your log located in `%LOCALAPPDATA%\CDDA Game Launcher\app.log`?

**Comment by defdeed** [comment]
![error](https://cloud.githubusercontent.com/assets/26492305/24061867/98555ec2-0b2f-11e7-85a7-7b916f23ac2a.png)

I deleted the %localappdata% folder because before this I had an issue where I couldn't update, something about it being unable to create something because it already existed.

**Comment by remyroy** [comment]
Do you have some antivirus product that might be blocking it?

**Comment by defdeed** [comment]
wow that actually worked, I don't know how though I had the launcher working with my antivirus for months before this problem randomly occurred. Thanks remyroy

**Comment by remyroy** [comment]
No problem.
