### ISSUE TITLE
[Suggestion] Add option to download much older builds

### ISSUE THREAD

**Issue by harald921** [remyroy/CDDA-Game-Launcher#11]
Perhaps a button that you can click to get a much larger list of builds to choose from? For bug checking perhpas?

**Comment by Malkeus** [comment]
Where is there such a list? The jenkins list only goes back about 20 versions or so. Which could be a particularly busy weekend around here...

**Comment by remyroy** [comment]
It would be great if we could have someone hosting the previous builds somewhere but I am not aware of such a thing. I'm getting the current builds from http://dev.narc.ro/cataclysm/jenkins-latest/ and that's the only place I know where they are being hosted. They only keep a few of the recent builds.

**Comment by harald921** [comment]
Aah yes, I didn't think of that. Stupid me. :)
