### ISSUE TITLE
Add link to needed MS libs to description of launcher

### ISSUE THREAD

**Issue by AMurkin** [remyroy/CDDA-Game-Launcher#111]
Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)
https://www.microsoft.com/download/details.aspx?id=8328

**Comment by remyroy** [comment]
It is a very valid point. I'll try to fix it as soon as possible.

**Comment by remyroy** [comment]
I will add a link to the release notes in the future releases. Thanks.
