### ISSUE TITLE
Could you add this buildings mod?

### ISSUE THREAD

**Issue by Romooska** [remyroy/CDDA-Game-Launcher#116]
* Name: [Whaleys Small Town Building Pack]
* Url: [http://s000.tinyupload.com/index.php?file_id=04160603493089527084]
* Author: [Whaley]
* Homepage: [http://smf.cataclysmdda.com/index.php?topic=14434.0]

**Comment by remyroy** [comment]
Sure, does it work with the latest version of the game?

**Comment by ZhilkinSerg** [comment]
Yes, I've just tested and it works.

**Comment by remyroy** [comment]
It has been added in b094f71f8a31ead88bc62b6d704f998a6e307bc1 and it will be part of the next release. Thanks.
