### ISSUE TITLE
Update download link for C:DDA Extra Professions & Gears mod

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#117]
C:DDA Extra Professions & Gears was updated (recipes were set to use SEW quality and filament requirement, all files were linted) - https://www.dropbox.com/s/r4ay5uqdnyfp36j/ZSFixed_CDDAXP_2017-05-18.zip?dl=0

**Comment by remyroy** [comment]
This has been completed in dea989daebd5ace9ee202c3d532e1e2d08c47225 and it will be part of the next release. Thanks.
