### ISSUE TITLE
Suggestion: Symlink Support

### ISSUE THREAD

**Issue by Philosophunculist** [remyroy/CDDA-Game-Launcher#122]
Instead of replacing every folder in the CDDA installation with new ones with the content from the old folders copied over, edit the contents of the folders. This would allow users to implement symbolic links into their installation without them disappearing every time they update. Symlinks could be used to facilitate the cloning of saves and settings folders between PCs. I personally want to be able to have my save file sync to all my devices using OneDrive.

An alternative would be if you don't need to edit the save file or config files in the update, then don't. It seems likely that the save file never needs to be updated.

P.S. Keep up the good work! 👍

**Comment by remyroy** [comment]
The symlink part might be similar to #21 which I though about implementing. One of the issue is the need for NTFS which is not always there and the poor support for it within the Windows ecosystem (can't see, move, remove or copy them properly with explorer for instance).

**Comment by Philosophunculist** [comment]
Please forgive me if I have misunderstood but what i'm suggesting is not that you implement symlinks into the installation process but that you make the process symlink friendly. At the moment if I replace my save folder with a symlink to a folder in my OneDrive called "save" when I update using your launcher the symlink will be replaced with the folder my symlink was linked to. You wouldn't have to implement anything involving symlinks, just prevent your launcher from deleting the save folder. When I watch my installation of CDDA in explorer while I update the game I see everything within is presumably copied then deleted then replaced but with the update. Perhaps if the save folder doesn't need updating you could just leave it instead of cutting and pasting it. Is it possible to update CDDA without touching the save folder in any way?

**Comment by remyroy** [comment]
There is an option in the settings called "Do not copy or move the save folder". Have you tried that?

**Comment by Philosophunculist** [comment]
I feel stupid now. I did not know that existed! Thank you very much and sorry for wasting your time. Just FYI my symlink seems to copy successful to the previous_version folder. Maybe it won't work on other systems but thought I should say however you copied it on mine worked.

**Comment by Philosophunculist** [comment]
Checking "Do not copy or move the save folder" works perfectly. Thanks again.
