### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by nornagon** [remyroy/CDDA-Game-Launcher#124]
* Name: More City Locations
* Url: https://github.com/nornagon/cdda-more-city-locations/releases
* Author: nornagon
* Homepage: http://smf.cataclysmdda.com/index.php?topic=14698.msg301740
* Mod not found in version: 1.3.10

(Thanks! :))

**Comment by remyroy** [comment]
It will be added in the next version. Thanks for noticing me.
