### ISSUE TITLE
Add this new mod to the repository: Chaosvolt's Arcana (not built in)

### ISSUE THREAD

**Issue by IronRex** [remyroy/CDDA-Game-Launcher#125]
* Name: Arcana
* Url: https://github.com/chaosvolt/cdda-arcana-mod
* Author: chaosvolt
* Homepage: http://smf.cataclysmdda.com/index.php?topic=10987.0
* Mod not found in version: 1.3.10

Game's built in Arcana is currently deprecated with low if any chance of coming back (I do not disagree with the reasons for banning Chaosvolt). I love the idea of the more "otherworldly" things happening in Cataclysm (we have shoggoths after all).
Currently I am using a shell script to auto update Arcana from the above repo. It would be nice to have (up to date) Arcana added to the launcher.
Here is my update script if you are interested:
```
@echo off
rd /s /q backup\Arcana\
move c:\Games\Cataclysm\data\mods\Arcana backup
cd cdda-arcana-mod\
git pull
dir
xcopy Arcana c:\Games\Cataclysm\data\mods\Arcana\
cd ..
```

**Comment by remyroy** [comment]
I'll see what I can do for the next release. Thanks.
