### ISSUE TITLE
PK Rebalancing Mod

### ISSUE THREAD

**Issue by Zetsukaze** [remyroy/CDDA-Game-Launcher#127]
Installing an update causes a faulty version of PK Rebalancing to be downloaded. I have to delete the data in the mods folder, then reinstall using the launcher.

After update folder name:
PK_Rebalancing

After deleting and manually reinstalling:
PK_Rebalancing-master

https://github.com/CleverRaven/Cataclysm-DDA/issues/21481#issuecomment-318985656

**Comment by remyroy** [comment]
The launcher uses the latest version of PK_Rebalancing when you install it from the mod tab. I believe the issue was from the git repository which should be fixed now.

**Comment by pisskop** [comment]
Aye.

current users say they have to reinstall the mod via the launcher, i think that is fixed too

**Comment by Zetsukaze** [comment]
Can confirm that this is not working with build 6650 from the launcher. I still have to reinstall the mod via the launcher.

**Comment by remyroy** [comment]
I believe this is solved now.
