### ISSUE TITLE
Update this mod in the repository

### ISSUE THREAD

**Issue by MrLabRat** [remyroy/CDDA-Game-Launcher#129]
* Name: Nimian's Manufacture Guns
* Url: https://github.com/MrLabRat/nimian_manufacture_guns
* Author: Noctifer-de-Mortem and MrLabRat
* Homepage: https://github.com/MrLabRat/nimian_manufacture_guns
* This is an updated version of the Nimian's Manufacture Guns already present in 1.3.10
* This mod is compatible with latest "stable" experimental version (6736)

**Comment by remyroy** [comment]
This will be updated in the next release. Thanks for the info.

**Comment by MrLabRat** [comment]
Thanks!
