### ISSUE TITLE
[Suggestion] Auto-Refresh (Or Auto-Refresh option)

### ISSUE THREAD

**Issue by harald921** [remyroy/CDDA-Game-Launcher#13]
Realized I downloaded an outdated version by forgetting to press refresh. Perhaps make it auto-refresh every 30 or 60 minutes, or add an option for it? Or should the launcher keep to itself as much as possible? Thoughts?

**Comment by remyroy** [comment]
It would probably make sense to auto-refresh the list of builds once in a while if you keep the launcher open for a long period. Every 30 minutes seems like a good frequency. I'll add that in the next release.

**Comment by harald921** [comment]
Another way to solve it would perhaps be to force the launcher to refresh before updating if it has been open over 30 minutes, or show you a window giving you a warning it was a while since it was refreshed.

**Comment by remyroy** [comment]
I'll think about this a little more and see if there could some interesting solutions.

**Comment by remyroy** [comment]
I think I'll just add another option in the settings tab with auto-refreshing the builds list every X minutes where you can select the value for X. I'll probably use 30 minutes as the default value.

**Comment by remyroy** [comment]
Implemented with 0aaf262b960e60aad577912257de8558e0443d3b. That will be part of the next release.
