### ISSUE TITLE
Can not update game

### ISSUE THREAD

**Issue by zapa1928** [remyroy/CDDA-Game-Launcher#130]
The launcher claims the game is up to date even tough it is not. It even shows today's updates in change log, but 5 days old build is seen as the latest.

![aaas](https://user-images.githubusercontent.com/7189448/30251915-9c29b0f0-9669-11e7-8284-246de5f559f1.jpg)

Win 7 x64 HP SP1

**Comment by remyroy** [comment]
There is an issue with the game builds on Windows x64. The available builds only list builds that are available and that can be downloaded. This is related to https://github.com/CleverRaven/Cataclysm-DDA/issues/21802

This is out of my control.

**Comment by zapa1928** [comment]
Ok.

**Comment by boydkr** [comment]
Might want to leave this open util it's fixed on the CDDA side, took me a while to find this.

**Comment by remyroy** [comment]
Sure

**Comment by BorkBorkGoesTheCode** [comment]
Seems to be fixed.
