### ISSUE TITLE
Add `dda-lua` mods to launcher

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#131]
Forum page: http://smf.cataclysmdda.com/index.php?topic=14861.0
Repository: https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA
Releases: https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA/releases

**Comment by remyroy** [comment]
Thanks for the info. It will be added in the next release.

**Comment by ZhilkinSerg** [comment]
Is there anything I can do to make adding it to launcher easier? Naming of release acrhive, etc?

**Comment by remyroy** [comment]
Yes. If you add a version property in your modinfo.json files similar to how [PK'rebalancing](https://github.com/pisskop/PKs_Rebalancing/blob/master/modinfo.json) is doing, I will eventually add a feature to auto-update your mod based on the local version detected and the version available on github. It can also help you with doing support if you know what version a user is reporting from.
