### ISSUE TITLE
"Available builds" list is outdated

### ISSUE THREAD

**Issue by rm-code** [remyroy/CDDA-Game-Launcher#134]
![unbenannt](https://user-images.githubusercontent.com/11627131/31631084-dbf80158-b2b8-11e7-9c47-7df9660d16e0.PNG)

**Comment by remyroy** [comment]
Available builds are simply that. Builds that are available to be downloaded. If there are changes and builds are not available, it means that there are broken builds.

See http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/
See http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/changes

This is not a bug.

**Comment by rm-code** [comment]
Ohhhh ... should've checked Jenkins directly.

Sorry!
