### ISSUE TITLE
Pressing certain keys on the magazine reloading bar crashes to desktop

### ISSUE THREAD

**Issue by Hugna** [remyroy/CDDA-Game-Launcher#136]
I'm not sure if a mod or not, but when i tried to use the left or right arrow keys when in this menu, the game crashes to desktop.

![cddabug1](https://user-images.githubusercontent.com/32887882/31696921-0417ac6c-b37a-11e7-94ea-d028e3d6ae28.png)

**Comment by remyroy** [comment]
You are on the wrong project. This is for the CDDA Launcher.
