### ISSUE TITLE
Not installing soundpacks propperly

### ISSUE THREAD

**Issue by Velken** [remyroy/CDDA-Game-Launcher#139]
Should be saving the .txt file like: 

#ChestHole soundpack

#Name of the soundpack

NAME: ChestHole

#Viewing name of the soundpack

VIEW: ChestHole

DESCRIPTION: A sound set with ambient sounds for music.

But is saving like:

#ChestHole soundpack#Name of the soundpackNAME: ChestHole#Viewing name of the soundpackVIEW: ChestHoleDESCRIPTION: A sound set with ambient sounds for music.

**Comment by remyroy** [comment]
Hi Velken,

The launcher does not save any file when it downloads a soundpack. All it does is decompress it from the archive. So there might be a problem with the archive but maybe it's a problem on your side as well.

**Comment by remyroy** [comment]
I don't thinks this is an issue with the launcher.
