### ISSUE TITLE
Also please add this new mod to the repository

### ISSUE THREAD

**Issue by ShadowDragon8685** [remyroy/CDDA-Game-Launcher#144]
* Name: Wintertime Classes
* Url: https://drive.google.com/open?id=1Syut09Asr393JYkzND3-FAYcR5sv_jFM
* Author: ShadowDragon8685
* Homepage: https://discourse.cataclysmdda.org/t/wintertime-classes/14608
* Mod not found in version: 1.3.10

The other mod I made adds new classes to the game; all are geared to presume a cold-weather start, and most are simply practically clones of existing stock classes.

**Comment by remyroy** [comment]
Thanks for sharing these info. Your mods will be added in the next version.
