### ISSUE TITLE
CDDA-Game-Launcher targeted as virus by KIS 18

### ISSUE THREAD

**Issue by MrLabRat** [remyroy/CDDA-Game-Launcher#147]
I've started noticing that cdda-launcher.exe is being marked as a virus for containing a file named tk86t.dll

Could you look into it?

Thanks!

**Comment by remyroy** [comment]
This is a false positive.

I suggest you submit this issue to Kaspersky.

In any case, you can always build the compiled executable from the source and check the source yourself if you do not trust the built release.

Regards,

**Comment by MrLabRat** [comment]
Will do! I ran their tool and it didn't bring up any issues which I find weird.

Thanks for the prompt answer!
