### ISSUE TITLE
Unhandled exception: Stat through skills IV mod crashes when i install 

### ISSUE THREAD

**Issue by talfouzan** [remyroy/CDDA-Game-Launcher#149]
* Description:Tried installing stats through skills IV mod 
* Version: 1.3.9.1
* OS: Darwin-16.4.0-x86_64-i386-64bit (64-bit)
* Type: `<class 'NameError'>`
* Value: name 'FormatError' is not defined
* Traceback:
```
  File "/Users/talfouzan/Downloads/CDDA-Game-Launcher-master/cddagl/ui.py", line 7126, in download_http_finished
    except FormatError:

```

**Comment by remyroy** [comment]
There is no Mac version of the CDDA Launcher. There is no support for running it on Mac. Sorry.
