### ISSUE TITLE
Unhandled exception: Crash on show current game after game itself crashed.

### ISSUE THREAD

**Issue by AdrianWennberg** [remyroy/CDDA-Game-Launcher#151]
* Description: Alt-Tabbed out of game. Game crashed. Pressed show current game where the launch game button usually is. Launcher crashed.
* Version: 1.3.10
* OS: Windows-10-10.0.16299 (64-bit)
* Type: `<class 'pywintypes.error'>`
* Value: (1400, 'SetForegroundWindow', 'Invalid window handle.')
* Traceback:
```
  File "cddagl\ui.py", line 973, in launch_game
  File "cddagl\ui.py", line 969, in focus_game
  File "cddagl\win32.py", line 693, in activate_window

```

**Comment by remyroy** [comment]
Thanks for the report. I think this is now fixed with 64761ee788d2413dd6183776d6c002c7e08533c1 . It will be part of the next release.
