### ISSUE TITLE
Chesthole CC Soundpack Not Working through CDDA Launcher

### ISSUE THREAD

**Issue by Coloradomtnman** [remyroy/CDDA-Game-Launcher#153]
Playing through the launcher, I get the main menu sounds but nothing in game.  Checked the files and everything seems to be in order including the .txt file.

**Comment by remyroy** [comment]
Once the soundpack is installed, you need to launch the game, go in the options, select the proper soundpack in the general tab, save theses new options and restart the game to enjoy the new soundpack.
