### ISSUE TITLE
Unhandled exception: [Launcher Error]

### ISSUE THREAD

**Issue by Rod995** [remyroy/CDDA-Game-Launcher#157]
* Description: [Hit update game when it said "Could not find remote builds" ]
* Version: 1.3.10
* OS: Windows-10-10.0.16299 (64-bit)
* Type: `<class 'TypeError'>`
* Value: 'NoneType' object is not subscriptable
* Traceback:
```
  File "cddagl\ui.py", line 1856, in update_game

```

**Comment by remyroy** [comment]
So I guess the launcher didn't find any remote builds and you still tried to update the game. I guess I need to show another message here instead of crashing.

**Comment by remyroy** [comment]
This change f9d60501f212a0b5fb5c26b427f8a66ec039593e should fix this issue. It will be part of the next release. Thanks for the report.
