### ISSUE TITLE
Scroling bug 

### ISSUE THREAD

**Issue by patrykpo** [remyroy/CDDA-Game-Launcher#159]
The game once launched keeps scrolling on launch, instantly goes into the character create screen and when i try to change the settings the game assingnes any command i try to change as up arrow. All other applications including the not launcher game work fine.

**Comment by remyroy** [comment]
I doubt this is related to the launcher. This seems more like an issue with your keyboard or something else.

**Comment by patrykpo** [comment]
I've done some additional testing in the form of launching the core game without using the launcher, meaning downloading it by itself, this resulted in no problem. Then I downloaded the chesthole tile set, the download that comes with a preinstalled launcher, this resulted in the same problem. By removing the Up binding the menues become somewhat managable. I didnt mean to seem insulting.

**Comment by patrykpo** [comment]
Ok After a little more investegation I had a Joystick managment program device istalled which was causing the problem.
