### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by Dmcd28** [remyroy/CDDA-Game-Launcher#161]
* Description: [Enter what you did and what happened]
* Version: 1.3.10
* OS: Windows-10-10.0.16299 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'stop'
* Traceback:
```
  File "cddagl\ui.py", line 6011, in timeout

```

**Comment by remyroy** [comment]
I believe this bug is solved with 498790c3ec4aa516722e2e9b583bb8c786a7194e . Thanks for the report.
