### ISSUE TITLE
[INFO] New soundpack

### ISSUE THREAD

**Issue by budg3** [remyroy/CDDA-Game-Launcher#164]
I've created a new soundpack that adds A LOT of missing sounds to CDDA. The newest versions will be available here: https://github.com/budg3/CDDA-Soundpack/releases

**Comment by remyroy** [comment]
Great stuff! Do you want me to add the release version or the master version? If I add version 1.1, it will always be that same version unless I update the launcher again. If I add the master version, it will use the latest commit you did.

**Comment by budg3** [comment]
You can add the master version. I will only push commits that are full updates.

**Comment by remyroy** [comment]
It was added with commit 690235673ee3b10b277eedb2b0098bdbf8e4c5c7. It will be part of the next release.
