### ISSUE TITLE
The launcher links to the old website insttead of the new one.

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [remyroy/CDDA-Game-Launcher#167]
The old address http://en.cataclysmdda.com/ is deprecated and may be causing people to think the main project is abandoned. It might also be driving the use of 0.C instead of experimental. It should be replaced with https://cataclysmdda.org/.

**Comment by remyroy** [comment]
Fixed with c8e42fa5bb660cbb7733ad7e7bb161aa0ea601a0. Thanks for letting me know.
