### ISSUE TITLE
Launcher self-update doesn't work

### ISSUE THREAD

**Issue by remyroy** [remyroy/CDDA-Game-Launcher#170]
It seems like the launcher self-update process doesn't work. This needs some investigation.

**Comment by ZhilkinSerg** [comment]
Confirming.

**Comment by Beetlecat** [comment]
Shoot -- me as well. Any issues with just dropping the new one right over the top of the old? ❔

**Comment by remyroy** [comment]
Just replacing the old with the new one should work just fine.

**Comment by remyroy** [comment]
I'll be working on replacing the old single file distribution with a proper installer and update process. This will require time and effort so patience is required for this to be fixed properly.

**Comment by D3L33T3D** [comment]
Anyone news on a fix to the update launcher? I have zero programming skills but I love the game and any news on a fix would be great. Thanks for such a fun game btw.

**Comment by evankimori** [comment]
(Launcher version 1.3.19)

In this new build: is the Launcher meant to operate with confirmation popup of removal of 'previous_version' folder and more user input to send to Recycle Bin specific folders? 

Escalating it to Admin Run doesn't seem to make the popups go away. 

First time I've ever seen the launcher ask me for a confirmation to add/remove/update folders. I can supply screenshots and log files if directed where necessary.

**Comment by remyroy** [comment]
@evankimori This is unrelated to the current issue. This should probably be in a new issue.

Recent versions of the launcher uses the FileOperation API to send elements in the recycle bin instead of deleting them. There is no confirmation prompt on Windows 10. Maybe Windows 7 shows one or maybe this is under some circumstances only. I can't control the location of the prompt windows since this is within a Windows API.

There are [various flags](https://docs.microsoft.com/fr-ca/windows/desktop/api/shobjidl_core/nf-shobjidl_core-ifileoperation-setoperationflags) that can be used with this API. A combination of FOF_WANTNUKEWARNING and FOF_NOCONFIRMATION might do the trick to prevent this prompt while keeping the safeguard of a prompt if a file cannot be sent to the recycle bin and it needs to be confirmed by the user.

**Comment by evankimori** [comment]
@remyroy Thank you for the update and info, my bad in posting it here. I'll create another issue with this problem separately. :)

**Comment by remyroy** [comment]
This will be fixed starting with version 1.4 meaning that if you have version 1.4, you can have the launcher self-update to later versions.
