### ISSUE TITLE
Add more mods from Chezzo site and Japanese wiki

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#176]
https://discourse.cataclysmdda.org/t/new-japanese-mod-space-victory/14472

https://discourse.cataclysmdda.org/t/nechronica-mod-from-the-japanese-wiki/13707

https://discourse.cataclysmdda.org/t/new-japanese-mod-uekibati-flower-pots-for-growing-crops-in-vehicles/14519

http://chezzo.com/cdda/mods/

https://www.reddit.com/r/cataclysmdda/comments/698fud/awesome_japanese_mods_wield_two_hanguns_hit/

https://translate.google.com/translate?hl=en&sl=ja&u=https://www57.atwiki.jp/cataclyj/&prev=search

**Comment by remyroy** [comment]
I'll see what I can do for the next release.

**Comment by ZhilkinSerg** [comment]
A little bit more of assorted links from Japanese author *yasuyasu*:

・北斗MOD(Fist of the North Star martial arts MOD) - https://www.axfc.net/u/3747167
・作物追加MOD(More crops MOD) - https://www.axfc.net/u/3832181
・襲撃MOD(Periodic raid MOD) - https://www.axfc.net/u/3867055
・Artyoms' Gun Emporiumで追加される銃のサウンドセット設定ファイル(Artyoms' Gun Emporium additional sound set) - https://www.axfc.net/u/3881086
・ユーティリティライトと建築物追加MOD(Utility light & more furniture construction MOD) - https://www.axfc.net/u/3890673

I can make PR for all of these on weekend.
