### ISSUE TITLE
Add Japanese locale

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#178]
Judging on number of mods in [Japanese wiki](https://translate.google.com/translate?hl=en&sl=ja&u=https://www57.atwiki.jp/cataclyj/&prev=search) they have strong Cataclysm community and probably benefit from the launcher.

**Comment by jattosan1980** [comment]
I tried translate but I don't know how github works.
anyway txt is here.
[cddagl.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/2020637/cddagl.txt)

**Comment by jattosan1980** [comment]
Yup Im using poedit but this writing space says "We don't support that file type." so I renamed it to txt.

>B(byte), OK, Not found, Windows
>Ki, Mi, Gi,
These are easier to understand as it is for japanese users.
Normally, software made in Japan does not display it as "ギビバイト" , just "GiB".

menu items and somethings added.
[cddagl.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/2020693/cddagl.txt)

**Comment by remyroy** [comment]
Great, thanks

**Comment by remyroy** [comment]
Japanese locale has been added with 0c611e264b2ff0c91048946e09d180fd2e191d91 . It will be part of the next release. Thanks again!
