### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by DracoGriffin** [remyroy/CDDA-Game-Launcher#180]
* Name: Draco's Dog Mod
* Url: https://github.com/DracoGriffin/DG_Mods/tree/master/DracoDogMod
* Author: DracoGriffin
* Homepage: https://www.reddit.com/r/cataclysmdda/comments/8kxl3r/new_mod_release_dracos_dog_mod/
* Mod not found in version: 1.3.11

**Comment by remyroy** [comment]
It will be done in the next release. Thanks for the contribution.

**Comment by DracoGriffin** [comment]
Closing as this was added in 8ac1bf9d44f6acef96fc471e27e5f4b67f033e22. Thanks for all your work @remyroy.
