### ISSUE TITLE
Can't complete NPC missions

### ISSUE THREAD

**Issue by Lazasar** [remyroy/CDDA-Game-Launcher#182]
So far I have tried the "Kill my Mom" and "Find weather patterns". I kill the mom, have the weather forcasts in my inventory and the NPC doesn't react accordingly when chatting with them

**Comment by Zireael07** [comment]
This should be reported to the game's repo, not launcher repo.

**Comment by Lazasar** [comment]
My bad

**Comment by Lazasar** [comment]
mistaken repo
