### ISSUE TITLE
Game Launcher Isn't Recognising Any New Updates Since 7432

### ISSUE THREAD

**Issue by JazzGuru** [remyroy/CDDA-Game-Launcher#184]
As the title says, the Game Launcher doesn't seem to be able to see any new versions since 7432, though there are newer version available on the GitHub page: 

https://github.com/CleverRaven/Cataclysm-DDA/commits/master

I have tried redownloading the installer, but the issue still persists.  The last update that was successfully installed was 7433...

**Comment by remyroy** [comment]
The game launcher only display builds that are available on the official builds server: http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/ . If there is an issue with the build process, which I suspect there might be, it is unlikely that those builds will be available which means they cannot be displayed in the dropdown list.

This is likely related to https://github.com/CleverRaven/Cataclysm-DDA/issues/23865

**Comment by JazzGuru** [comment]
Thanks.

I did do a quck search, but didn't come across the issue to which you have provided a link... ;)
