### ISSUE TITLE
More Whaleys mods with buildings

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#185]
Homepage: https://www.reddit.com/r/cataclysmdda/comments/8nayyx/cataclysm_building_pack_seedy_spots/
Download link: https://nofile.io/f/NRZrNjWvZDK/Cataclysm+Seedy+Spots+Building+Pack.zip

### What was added:

- Stripclubs (3 Variations)
- Scrapyards (3 Variations)
- 3-Tile Trailer Parks (2 Variations)
- Homeless camps (5 Variations)
- New Houses (14 Variations, Some of them with detached sheds, pools, etc and some that are downright filthy.)
- And a Park and Coffee Shop variation just for fun. 

***

Homepage: https://nofile.io/f/kbEB4HekuOq/Whaleys+Big+Buildings+Pack.zip

Download link: https://www.reddit.com/r/cataclysmdda/comments/8nc0b0/whaleys_big_buildings_pack/

### What was added:

- Stadium - (20 Overmap Tiles)
- Zoo - (9 Overmap Tiles, 2 Variations)
- Pet Stores - (2 Variations)
- More Derelict Properties - (8 Variations)
- More Dispensaries - (3 Variations)
- Headshop - (1 Variation)
- And an additional Gun Store variation for fun.

The Zoo also includes an optional Scenario Start.

**Comment by remyroy** [comment]
I think these were added with c1996a971ff9d0604c37a390d8d2babbe575b945 . I failed to see your pull request that included them before I added some of them. My bad.
