### ISSUE TITLE
Changelog not displaying?

### ISSUE THREAD

**Issue by TechyBen** [remyroy/CDDA-Game-Launcher#186]
Cannot see any changelog details in the updater anymore.

**Comment by SirClarke** [comment]
Also having the same problem

**Comment by ZhilkinSerg** [comment]
Site with PR changelog is currently down - see https://github.com/CleverRaven/Cataclysm-DDA/issues/23865

**Comment by Sammmmm** [comment]
If this is just static content, couldn't it be hosted in firebase or s3 for free?

**Comment by remyroy** [comment]
This isn't static content. It is generated by a process which is most likely down right now. Just gotta wait for the related issue to be solved.

**Comment by Sammmmm** [comment]
Ah makes sense, I just assumed the process was run on a dev machine or CI
build or something, and the output could be changed to a cloud deploy of
some sort.

**Comment by ZhilkinSerg** [comment]
Should be resolved now.

**Comment by remyroy** [comment]
I think this is resolved. I'm closing but let me know if you are still having this issue.
