### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by Stone94** [remyroy/CDDA-Game-Launcher#187]
* Name: [Monster Exclusion Mod]
* Url: [https://www.nexusmods.com/cataclysmdarkdaysahead/mods/5]
* Author: [Stone - Me]
* Homepage: [https://www.nexusmods.com/]
* Mod not found in version: 1.3.10

Someone told me they would like to see it here.

**Comment by remyroy** [comment]
It will be added in the next version. Thanks.
