### ISSUE TITLE
Whaleys Big River Building Pack (2 versions)

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#191]
# Site Link:

https://www.reddit.com/r/cataclysmdda/comments/8rfnio/whaleys_big_river_building_pack/

# Additions:

- Riverside Dwellings - Small riverside buildings, Warehouses, etc. [ 15 Variants ]
- Boat Rentals - A building which almost always has boats available. [ 3 Variants ]
- Rural Houses (3x1) - Houses tucked into the woods with long dirt driveways. [ 2 Variants ]
- Moonshine Stills - Stills for brewing moonshine, hidden in the woods. [ 3 Variants ]

# Download Links:

- https://nofile.io/f/JHWXQPk80Uu/Whaleys+Big+River+Building+Pack.zip
~~- https://nofile.io/f/OC365DHbH5e/Whaleys+Big+River+Building+Pack+CLASSIC+.zip (for those that like to play with Classic Zombies only, Here is a version that does that.~~

**Comment by JazzGuru** [comment]
Hope this gets mainlined soon.  The 1st link works, but then it's as if the file isn't there...

**Comment by remyroy** [comment]
Second download link does not work.

**Comment by ZhilkinSerg** [comment]
> Second download link does not work.

It was deleted probably, so only first one should be used.

**Comment by remyroy** [comment]
This mod with 2 new others mods from Whaleys were added in c1996a971ff9d0604c37a390d8d2babbe575b945 . They will be part of the next release.
