### ISSUE TITLE
Unhandled exception: Music error

### ISSUE THREAD

**Issue by Gabe-Lincoln** [remyroy/CDDA-Game-Launcher#198]
* Description: I tried updating my game to the latest version, and this exception occurred.
* Version: 1.3.11.1
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'PermissionError'>`
* Value: [WinError 5] Access is denied: 'C:\\Users\\Adam\\Documents\\previous_version\\My Music'
* Traceback:
```
  File "cddagl\ui.py", line 7793, in step

```

I have no idea what the actual problem is, but that folder doesn't exist. Should I just create it to fix this?

**Comment by remyroy** [comment]
It's a really bad idea to have your game in your Documents folder with everything that Windows and other applications are putting in there. You should make a distinct folder for the game and update it from there.

I would HIGHLY suggest to stop using the launcher until you do so. That will also prevent those kind of errors.

Now, if you don't want to lose any of your documents, you should look into C:\Users\Adam\Documents\previous_version and backup that folder before proceeding to do anything else. You likely have some misplaced documents in there.

**Comment by Gabe-Lincoln** [comment]
Okay, thank you. I made a folder for the game. Seems like that fixed the problem. Hopefully the next time I update it won't break.
