### ISSUE TITLE
[Suggestion] Grey out "Update game" button when up to date

### ISSUE THREAD

**Issue by harald921** [remyroy/CDDA-Game-Launcher#2]
[TITLE] - and perhaps even add a "Your game is up to date!"? :) 

Off-Topic: Great work on the launcher, it's golden

**Comment by remyroy** [comment]
I though about doing it but someone might want to download a fresh copy of a build even if they already have that version. Adding the message "Your game is up to date" would make sense. I might add a question dialog to confirm someone wants to update to the same version if they try.

**Comment by remyroy** [comment]
I've added various messages and a confirmation dialog to update your game when it is already up to d ate in ff3fb8fdae216905faba1a4eb8f71b9c52bce3bc . This should be enough for now.
