### ISSUE TITLE
Unhandled exception: Error on soundpacks repository

### ISSUE THREAD

**Issue by dsiOne** [remyroy/CDDA-Game-Launcher#20]
* Description: Was checking out the settings in the program before actually installing CDDA, clicked on the ChestHole soundpack in the Soundpacks repository list to see what would happen. This did. I installed CDDA through the launcher afterwards (the error didn't close the launcher) and the program became unusable with everything on the Main and Soundpacks tab disabled, works fine after relaunching it.
* Version: 0.7
* Type: `<class 'AttributeError'>`
* Value: 'SoundpacksTab' object has no attribute 'soundpacks_dir'
* Traceback:
```
  File "cddagl\ui.py", line 3264, in repository_clicked

```

**Comment by remyroy** [comment]
Thanks for the report. I'll fix this and include the fix in the next release.

**Comment by remyroy** [comment]
This should be fixed with 1e26f15156822d8b039c65dd799a5cdf601cbc91. It will be part of the next release.
