### ISSUE TITLE
"Could not download" dropbox link Mods and Soundpacks

### ISSUE THREAD

**Issue by KurzedMetal** [remyroy/CDDA-Game-Launcher#200]
Seems like all dropbox links can't be downloaded from the Launcher anymore.

I got errors for StatsThoughSkills IV, Whaleys Small Town Building Pack and RRFSounds.
I could download them from my browser, so it's something specific to the Launcher.
I'm guessing something changed on dropbox servers? (maybe requiring some specific header?)

Regards!

**Comment by remyroy** [comment]
I'll look into it. I guess Dropbox changed their logic for serving files. Hopefully it can still be automated.

**Comment by Althorion** [comment]
In the meantime, can I download the necessary file manually and put it somewhere where the launcher will find it? It seems to generate the folder for download randomly.

**Comment by remyroy** [comment]
This should be fixed with 909160b645f487ebc22e08c9154e7dced2c3f144 and it should be included with the next release.

**Comment by KurzedMetal** [comment]
yay
