### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by hitmancho** [remyroy/CDDA-Game-Launcher#201]
* Name: DracoDogMod
* Url: https://github.com/DracoGriffin/DG_Mods/tree/master/DracoDogMod
* Author: DracoGriffin
* Homepage: https://github.com/DracoGriffin
* Mod not found in version: 1.3.11.1

**Comment by remyroy** [comment]
It will be included in the next release. Thanks for the info.

**Comment by remyroy** [comment]
This was added 8ac1bf9d44f6acef96fc471e27e5f4b67f033e22 . It will be part of the next release.
