### ISSUE TITLE
Jury Rigged Robots link is to the broken version

### ISSUE THREAD

**Issue by TheSalamanderDJ** [remyroy/CDDA-Game-Launcher#212]
There is a new version on github and google drive available that doesn't crash or have error messages.

**Comment by remyroy** [comment]
Do you have the link or the message that shows where I can find the new link so I can update it?

**Comment by TheSalamanderDJ** [comment]
The link is here:
https://github.com/TheSalamanderDJ/Jury-Rigged-Robots

**Comment by remyroy** [comment]
Alright, it will be updated in the next release. Thanks for the info!

**Comment by remyroy** [comment]
Completed with a2ddea2c96808ef9bcc7ec1bf4b49e298b535ed9 . It should be part of the next release.
