### ISSUE TITLE
Launcher ATE my desktop!

### ISSUE THREAD

**Issue by wraith2476** [remyroy/CDDA-Game-Launcher#213]
I installed the launcher to my desktop or rather the installer. I did however make the mistake of not setting up a folder to install INTO. So long story short, I installed the game and its contents onto my desktop and more than half of my icons AND important files were missing. I restarted my comp, and even tried a system restore to alleviate the issue to no avail. I know I messed up in the respect of installing a game like this directly onto my desktop I’m not here for a lecture just a solution. Please and thank you in advance so kindly.
    P.S. After pulling an all-nighter while trying to find my important files I found a few duplicates of the folder i'd been looking for. They're no longer folders but LINKS to my folder! (folder.lnk)

**Comment by remyroy** [comment]
The launcher initially moves all files in a subdirectory called previous_version. If you avoided installing twice, you should find all your files in there.

**Comment by wraith2476** [comment]
That's a no go. I found previous_version folder and it didn't have anything i'd lost in it.

**Comment by remyroy** [comment]
This recent change 05d5ce589687cc1c408263aa34b825205d6fba61 will prevent installing in a directory that is not empty.

**Comment by wraith2476** [comment]
I initially tried installing this launcher on  my secondary drive where it moved files I had on there. I then moved it to my desktop where it did work. So I'm thinking the second attempt might have cleared out the first attempt in previous_version folder. You honestly think I want to download this mess again?! After it basically destroyed my desktop?! Funny! I just want all of my stuff restored at this point. I'd appreciate some help in that matter instead of having code thrown in my face.

**Comment by remyroy** [comment]
I would try recovery tools like [MiniTool Power Data Recovery](http://www.powerdatarecovery.com/) or [Recuva](https://www.piriform.com/recuva).
