### ISSUE TITLE
Turrets in Lab bugged out and starved me to death

### ISSUE THREAD

**Issue by ComradeKarny** [remyroy/CDDA-Game-Launcher#216]
![screenshot 2018-09-26 20 42 00](https://user-images.githubusercontent.com/43627442/46119131-4d0eb280-c1cf-11e8-9b79-7c02a6029ef7.png)
![screenshot 2018-09-26 20 41 41](https://user-images.githubusercontent.com/43627442/46119134-526bfd00-c1cf-11e8-8cd8-4a9f1b29979f.png)
![screenshot 2018-09-26 20 41 37](https://user-images.githubusercontent.com/43627442/46119137-5435c080-c1cf-11e8-9c62-30ecfa6a40b5.png)
![screenshot 2018-09-26 20 41 25](https://user-images.githubusercontent.com/43627442/46119141-56981a80-c1cf-11e8-8e00-e08ded7e4ede.png)

While sorting out my stuff i had dropped a lighter, when I had dropped the item i was interrupted "you have heard a noise would you like to stop what you are doing?"

I as always {Shift I} ignored further messages of the same type, and when i had the game trapped my in a infinite cycle of chatter, the turret would aggro (on something it could not see) and deaggro.

![screenshot 2018-09-26 20 35 29](https://user-images.githubusercontent.com/43627442/46119312-fe154d00-c1cf-11e8-9478-d4b64586fa60.png)

this went on for 13 hours in game until the message "you are tired would you like to stop?"
 finally had ended it. A fair bit earlier in this Lab run i would probably have died if this had happened at a bad time.
ps: the 5 key would not ask to pause, and i could not figure out how to compress my save file to upload it, as I am not very computer savvy.

**Comment by remyroy** [comment]
This is unrelated to the launcher. Please report this issue in [the proper repository](https://github.com/CleverRaven/Cataclysm-DDA).
