### ISSUE TITLE
Adding No Freeze to repo.

### ISSUE THREAD

**Issue by Poragon** [remyroy/CDDA-Game-Launcher#217]
Name: No Freeze
Url: https://github.com/Poragon/No-Freeze
Author: Poragon
Homepage: https://discourse.cataclysmdda.org/t/no-freeze-mod-release/16709/20
Mod not found in version: not sure

Peeps on discord keep asking for a mod which disables freezing. As the launcher is a good platform for exposing mods, poppin' No Freeze in it will make a large sect. of the player-base aware that such a mod does exist.

**Comment by remyroy** [comment]
Thanks for the info. It will be added shortly.

**Comment by remyroy** [comment]
This was added with 6df0034b721a22b5443038166cbad2f0f0bdb0c5 . It will be part of the next release.
