### ISSUE TITLE
Keyboard key functions.

### ISSUE THREAD

**Issue by Somerandomguy22** [remyroy/CDDA-Game-Launcher#219]
I am currently experiencing problems with the CDDA Launcher. Every time I attempt to move the arrow keys, it will have a delay. Example, I would press the right arrow key once, it won't move but if I press the enter key, the arrow on screen would move onto whatever option I would have chosen when I pressed the right arrow key. This also applies with stopping on a certain setting. I would move down the list, but I cannot stop directly on another setting because if I press any other key, it will jump ahead one setting like its lagging behind one key. It applies to everything and anything on the CDDA launcher and doesn't affect my computer outside the application. Even after I updated the game from 1.3.11 to 1.3.12 it still affects it. 

It has become impossible to play CDDA. It took me 2 hours to make a world and I still was unable to play due to the fact I accidentally added something I didn't want.

If there is already a fix for this and I haven't seen it, please do point me in the right direction. Thanks. 

I am on the 7th OCT update and has happened since 6th OCT.

**Comment by remyroy** [comment]
I feel like you are referring to the game itself. The CDDA Launcher is a separate project from the game. You should probably report your issues on [their github](https://github.com/CleverRaven/Cataclysm-DDA/issues).

**Comment by Somerandomguy22** [comment]
@remyroy Thank you for the reply.  

I apologise earlier for my, rash comment. However, I have found the fix for the subject at hand through a little time and effort. I once again apologise.

Thanks,
