### ISSUE TITLE
Launcher doesn't follow redirect to https

### ISSUE THREAD

**Issue by narc0tiq** [remyroy/CDDA-Game-Launcher#221]
According to <https://old.reddit.com/r/cataclysmdda/comments/9of2ek/help/>, when I turned on HTTPS with forced redirect from plain HTTP, the launcher broke.

Suggest updating the launcher to go to the <https://dev.narc.ro/> site, and then I can flip the redirect on again.

**Comment by remyroy** [comment]
Alright, we'll use https://dev.narc.ro/ and implement redirects.

**Comment by narc0tiq** [comment]
I'm surprised it wasn't naturally following redirects already. I guess QNetworkRequest doesn't? But thanks for taking care of it!

**Comment by remyroy** [comment]
Included with 0f75eba438863f657c3ae1362e532f9eb42a3af3 . It will be part of the next release which should come shortly.

**Comment by remyroy** [comment]
Seems like the HTML code for the listing changed as well. I'll do another update and release to support this.
