### ISSUE TITLE
Error: Could not find remote builds.

### ISSUE THREAD

**Issue by Bowab** [remyroy/CDDA-Game-Launcher#222]
Im using the latest version 1.3.13.

The launcher is having trouble finding the builds. 
See image:
https://i.imgur.com/q3xmnxW.png

**Comment by JazzGuru** [comment]
Hi,
this is an issues that has cropped up a couple of times in the last few days, and it is something that is outside of remyroy's control.

Read the last couple of posts in this reported issue to see what I mean:

https://github.com/remyroy/CDDA-Game-Launcher/issues/220

**Comment by JazzGuru** [comment]
Nice one remyroy.

Glad you now what's going on, and how to fix it... :D

**Comment by remyroy** [comment]
This should be fixed with 86801060ee2c49e3a4c62a4bc53c245090ee3d06 . A new release will be published shortly.
