### ISSUE TITLE
Unhandled exception: Crash when selecting mod

### ISSUE THREAD

**Issue by DrN0psl3d** [remyroy/CDDA-Game-Launcher#223]
* Description: Selected mod in modlist
* Version: 1.3.13
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: setText(self, str): argument 1 has unexpected type 'list'
* Traceback:
```
  File "cddagl\ui.py", line 7503, in repository_clicked

```

**Comment by remyroy** [comment]
This issue has just been fixed with 1.3.15. Try it and let me know.

**Comment by DrN0psl3d** [comment]
Yep, works fine now 👍 
Can be closed!
