### ISSUE TITLE
Unable to update to the latest build, even if it shows in the changelog

### ISSUE THREAD

**Issue by Zetsukaze** [remyroy/CDDA-Game-Launcher#227]
Cannot update to 8096, only 8095. Sorry for the crappy screenshot, I can't use snipping tool to capture the screen with the dropdown open. Had to use paint =P

![launcherbug](https://user-images.githubusercontent.com/1698993/47763667-9b4a3080-dcfc-11e8-9fa4-fd348261aa03.png)

**Comment by remyroy** [comment]
There is [no version 8096 available yet](https://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/). Maybe it has not been built yet or maybe there was a problem with the build.

The launcher only shows builds that can be downloaded. If they are not available on the server, they are not shown.

**Comment by Zetsukaze** [comment]
Ah, sorry for the false bug report!
