### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by ampersand55** [remyroy/CDDA-Game-Launcher#228]
* Name: PKs Rebalancing (working as of build 8098)
* Url: https://github.com/dissociativity/PKs_Rebalancing/archive/master.zip
* Author: dissociativity (Siyalatas/pisskop)
* Homepage: https://github.com/Dissociativity/PKs_Rebalancing
* Mod not found in version: 1.3.15

**Comment by remyroy** [comment]
Thanks for this information. It will be added in the next release.

**Comment by remyroy** [comment]
It was added  in a098cd15f29125173e49e7c1505ddec0ffb10085 . It will be part of the next release which should be soon.
