### ISSUE TITLE
Tablet driver has failed to load error message when launching the updater

### ISSUE THREAD

**Issue by HorrorNerd** [remyroy/CDDA-Game-Launcher#23]
Yesterday I noticed that when I try to run the updater I get an error message that the tablet driver failed to load. It's weird because I don't have a tablet installed. Updated to the newest version and it still happens. I'm running win 7

**Comment by remyroy** [comment]
Can you get a screenshot of the exact error message?

**Comment by remyroy** [comment]
If you get that error again, open a new issue.
