### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by LocXar** [remyroy/CDDA-Game-Launcher#230]
* Name: PKs_Rebalancing
* Url: https://github.com/dissociativity/PKs_Rebalancing
* Author: dissociativity
* Homepage: https://github.com/dissociativity/PKs_Rebalancing
* Mod not found in version: 1.3.15

it is someone who is trying to make the PK mod working with the actual Game.

Its so frustrating, to have the mod in the launcher but it doesnt work without errors. This ist a lot better as what i heard.

**Comment by remyroy** [comment]
This was already mentioned with #228.
