### ISSUE TITLE
Linked More Buildings and Locations Mod needs "forest_mapgen_settings"

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [remyroy/CDDA-Game-Launcher#234]
The version of More Buildings and Locations that is linked in the mods menu of the launcher needs the forest_mapgen_settings added into the regional_map_settings, otherwise the game won't load the mod.

**Comment by remyroy** [comment]
I'll be happy to removed these mods from the repository until the author fixes them or someone else does.

**Comment by remyroy** [comment]
Good call. These 2 mods will be removed from the repository.

**Comment by remyroy** [comment]
I believe these were removed already.
