### ISSUE TITLE
Unavailable components (filled containers) in crafting menu.

### ISSUE THREAD

**Issue by Alce00** [remyroy/CDDA-Game-Launcher#237]
When looking at safe glasses receipt it says that I have plastic bottle and don't have any small plastic bottles, which is accurate. But when making them it gives option to chose between plastic bottle and two small plastic bottles and says that I have 5 of them. All five available small plastic bottles are filled with meds. Choosing that option creates glasses, but not consume any bottles.

**Comment by remyroy** [comment]
This isn't the place to report an issue about the game. See https://cataclysmdda.org/ .

**Comment by Alce00** [comment]
Sorry, clicked on wronf url.
