### ISSUE TITLE
Launcher doesn't update game because of local time/timezone

### ISSUE THREAD

**Issue by Dozed12** [remyroy/CDDA-Game-Launcher#239]
1 - My local time is 21:27
2 - Had my game several builds behind the latest. Latest version is from 22:14 of today indicated in Changelog UI of the launcher.
3 - Pressed "Update game"
4 - Launcher updates game to version that is from 08:45 of today, latest version released before my local time.
5 - I change my pc local time to 22:27
6 - Pressed "Update game" again
7 - Launcher now updates to true latest version, from 22:14 of today.

I didn't search much about this in the source but the part that searches for the latest build might not take into account builds that were released after the local time, due to timezones.

**Comment by remyroy** [comment]
The launcher uses the selected build in the drop-down list and build numbers for the default selected build to select which version to install or to update to. Time is irrelevant in this selection. It only uses time to show your build age (something like this build was created 3 days ago or 2 hours ago).

**Comment by Dozed12** [comment]
I see. In that case I'm not sure what could have caused it to not select the latest build by default. Since changing my local time fixed it I assumed it was the culprit.
