### ISSUE TITLE
Add this new soundpack to the repository

### ISSUE THREAD

**Issue by jasonmbrown** [remyroy/CDDA-Game-Launcher#248]
* Name: 2ch Sounpack
* Url: https://drive.google.com/drive/folders/1e7NAT07njV5TkxnQxpo4nxeI0RfpN25N
* Author: ? Unknown ?
* Homepage: ? Unknown ?
* Soundpack not found in version: 1.3.16

Been using this Pack for a little while, Its Really good. Lots of variance in the effects. Not sure who the author is I cant read Russian. Sorry I can't get anymore info other then The Name and Url.

**Comment by UMS50** [comment]
I use & support this pack, would be cool to know more about it!

**Comment by remyroy** [comment]
The 2ch soundpack link should probably be https://drive.google.com/open?id=14_ZlFCwqavU8JJ9X4PHVM5vqEXs46OsM

**Comment by remyroy** [comment]
Added with e470a925887dff57e1847838878423bbcb42b55b .
