### ISSUE TITLE
Update this mod in the repository

### ISSUE THREAD

**Issue by SnackMcOgrelord** [remyroy/CDDA-Game-Launcher#250]
* Name: Mutation Changes
* Url: https://github.com/Bl4nked/Mutation-Changes-Mod-Fix-
* Author: Original: Peeved Penguin, Fix: Bl4nked
* Homepage: https://github.com/Bl4nked/Mutation-Changes-Mod-Fix-

Mod currently does not function with any of the newer versions of the game, however the aforementioned fix will make it function correctly again.

**Comment by remyroy** [comment]
Thanks for the information. I'll update it for the next release.

**Comment by remyroy** [comment]
Added with b19f2aed1a393486cdc3a543eb4ac4961fd94b0f .
