### ISSUE TITLE
[CO.AG Soundpack] Add this new soundpack to the repository

### ISSUE THREAD

**Issue by SkyBreach** [remyroy/CDDA-Game-Launcher#252]
* Name: CO.AG SoundPack
* Url: https://drive.google.com/uc?id=14aAY2Xk-uVczgrCAWwdwL8SqYSIA31N6&export=download
* Author: SkyBreach
* Homepage: https://discourse.cataclysmdda.org/t/soundpack-co-ag-soundpack/18992

**Comment by SkyBreach** [comment]
Updated link. (Version 1.1)

Full Version [Music + Sounds]:
https://drive.google.com/uc?id=1kjKQDOD0sYQY8QIH6fg8rgqEQgm8Bbqn&export=download
Alternative Addon [Music Only]
https://drive.google.com/file/d/1dIVPd5opStkjhF7iindQ9uwe0ttI0nkQ/view

**Comment by remyroy** [comment]
Thanks for the information. It will be added in the next version.

**Comment by SkyBreach** [comment]
Thank you very much @remyroy 
Glad to hear that!

**Comment by remyroy** [comment]
Added with c64ca4bd166848bf3b71ede2d7096ba26c56d2d9 .
