### ISSUE TITLE
Missing LUA support! + Cannot install StatsThroughSkills VI

### ISSUE THREAD

**Issue by Noomene** [remyroy/CDDA-Game-Launcher#253]
Dear devs,

I'm using the latest version of the launcher. One problem I faced was that I could not install the latest StatsThroughSkills VI mod. It does not appear in the list of installable mods (see screeshot 1). Furthermore, when I start the game, and I try to create a character/world, I cannot add even the basic STS mod, it says "this mod requires LUA" (See screenshot 2)

Please help.

Thank you!

Screenshot 1:

![s1](https://user-images.githubusercontent.com/11027939/53838684-a68bc200-3f63-11e9-8f8a-9144195bf945.JPG)

Screenshot 2 :

![s2](https://user-images.githubusercontent.com/11027939/53838704-b1deed80-3f63-11e9-9bf9-481e9b2d07fc.png)

**Comment by remyroy** [comment]
Which OS are you using?

**Comment by remyroy** [comment]
StatsThroughSkills should already be part of the base game. See https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/mods/StatsThroughSkills .

**Comment by remyroy** [comment]
The windows builds of the game should already have LUA with it.

**Comment by Noomene** [comment]
Thank you very much for the quick reply!
Yes, it is included, but the question is why I could not add the mod to the game and I get that LUA message when creating a character as shown in screenshot 2. I could not add it. Even though the mod folder is there with the JSON and lua files. I do not understand what I am missing.

Thanks again for your help.

**Comment by remyroy** [comment]
This is beyond the scope of the launcher. I'm closing this but I suggest you ask people that creates the game or the game community.
