### ISSUE TITLE
Game Launcher doesn't install or update

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [remyroy/CDDA-Game-Launcher#254]
The launcher has recently stopped working, probably due to the shift from Copper to Danny. On update the launcher removes the executable for the folder. On trying to reinstall, it wouldn't do anything.

**Comment by remyroy** [comment]
I just updated my game to build 8596 and it seems to works fine. Are you talking about updating the launcher itself?

**Comment by SolsticeTheTechMarine** [comment]
Never mind, I fixed my issue. I hadn't previously noticed the text below the install button telling me that the folder had to be empty. After I tried updating the game, I guess the launcher got interrupted. This then caused the launcher to want the folder that I was installing into empty before I installed (which even detected the launcher being inside of the folder, so I put that somewhere else). I Installed it into the empty folder and it worked fine.
