### ISSUE TITLE
Launcher deletes custom mods when it updates

### ISSUE THREAD

**Issue by jedibob5** [remyroy/CDDA-Game-Launcher#26]
Apologies if this isn't a bug and is instead me doing something wrong, but whenever I update the experimental using the launcher, it deletes a mini-mod that I made that blacklists all shocker zombies. It's not that big of a deal, I have a copy of it elsewhere that I can just copy-paste back into the folder, but it would be nice to not have to do that every time I update.

**Comment by remyroy** [comment]
If your mod is in a different folder than the official mods and it has a different ident value in the `modinfo.json` file from every other official mods, it should be kept. Send me a copy of your mode and I'll check to make sure there is no bug.

**Comment by jedibob5** [comment]
Oh. That would make sense. Where is the proper location for non-official mods other than the /data/mods/ folder where the game can find them?

**Comment by remyroy** [comment]
The proper location is `data\mods` even for custom mods (most of the time).

**Comment by remyroy** [comment]
You can also start the game with the `--userdir <path>` command line argument to override the path to the ./data directory but it might have some side effects.

**Comment by jedibob5** [comment]
Okay, well I think something may in fact be wrong in that case, since I do have the mod stored in a separate folder in `data\mods`. Here's the text of the mod, in case something is wrong with it:
`[
{
    "type": "MOD_INFO",
    "mod-type": "SUPPLEMENTAL",
    "ident": "No_Shockers",
    "name": "No Shocker Monsters",
    "author": "Jedibob5",
    "description": "Removes shocker zombies and shocker brutes.",
    "category": "monster_exclude",
    "path": ""
},{
    "type": "MONSTER_BLACKLIST",
    "monsters": [
		"mon_zombie_electric",
		"mon_zombie_brute_shocker"
    ]
}
]`

**Comment by remyroy** [comment]
Isn't the file supposed to be called `modinfo.json`? If you could zip your mods folder and send it to me, that might solve any ambiguities.

**Comment by jedibob5** [comment]
It is, but as I said, GitHub wouldn't let me attach a .json file, so I changed the extension to .txt before uploading it. Here's the zipped mod folder anyway

[No_Shockers.zip](https://github.com/remyroy/CDDA-Game-Launcher/files/120382/No_Shockers.zip)

**Comment by remyroy** [comment]
My bad. Let me see what is wrong with your mod and fix it if need be.

**Comment by remyroy** [comment]
I just tested this with version 0.7.5 and your mod was preserved during the update process. I installed your mod in `data\mods\No_Shockers` and it was copied back after the update.

Which version of the launcher are you using?

**Comment by jedibob5** [comment]
Updated the launcher to 0.7.5, looks like it's all working now. My bad, didn't even know there was a newer version available.
