### ISSUE TITLE
Launcher not updating game

### ISSUE THREAD

**Issue by DragonFire0704** [remyroy/CDDA-Game-Launcher#261]
So, I've been trying for a couple days now, and my launcher doesn't want to update the game anymore. I can no longer see change logs and refreshing sometimes crashes the launcher. I have tried admin start, turning off the firewall, and reinstalling. Please help as I would really like to update soon

**Comment by remyroy** [comment]
The changelog seems to be working fine for me right now, but the available builds list doesn't seem to be loading properly. I'll check that quickly.

**Comment by remyroy** [comment]
Try with this build and let me know if it works.

https://www.dropbox.com/s/vdaxnyf3mqwqvhp/launcher.zip?dl=1

**Comment by DragonFire0704** [comment]
It does indeed work, thank you

**Comment by remyroy** [comment]
I'm guessing this can be closed now.
