### ISSUE TITLE
Add this new mods to the repository

### ISSUE THREAD

**Issue by Axema** [remyroy/CDDA-Game-Launcher#262]
* Name: Secronom Zombies
* Url: https://github.com/Axema/Secronom-Zombies
* Author: Axema Vales
* Homepage: https://discourse.cataclysmdda.org/t/secronom-zombies-mod-thread/16211/1
* Mod not found in version: 1.3.16
=====
* Name: Vampiric Stuff
* Url: https://github.com/Axema/Vampiric-Stuff
* Author: Axema Vales
* Homepage: https://discourse.cataclysmdda.org/t/vampiric-stuffs-mod-thread/16001/1
* Mod not found in version: 1.3.16

@remyroy These 2 mods are actually WIP, but remains stable throughout the game :+1: 

![](https://discourse-cdn-sjc2.com/standard11/user_avatar/discourse.cataclysmdda.org/axema/120/5137_2.png) :heart:

**Comment by remyroy** [comment]
Thanks for the info. They will be added in the next version.

**Comment by remyroy** [comment]
It has been added with 6334ab18aeece14984d8d3be78e3f2a50f9b316d and should be part of the next release. Thanks.
