### ISSUE TITLE
Add this new mod to the Repository

### ISSUE THREAD

**Issue by KaosMachina** [remyroy/CDDA-Game-Launcher#264]
* Name: PK's Rebalancing Working Patch
* Url: https://github.com/dissociativity/PKs_Rebalancing/archive/master.zip
* Author: Dissociativity (forked from Siyalatas, original author Pisskop)
* Homepage: https://github.com/Dissociativity/PKs_Rebalancing
* Mod not found in version: 1.3.15

Throwing this out there because the one in the library doesn't work on current versions.

**Comment by remyroy** [comment]
This mod should already be part of 1.3.16 with the name **PKs Rebalancing [build > 8098]**
