### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by InsanityComplx** [remyroy/CDDA-Game-Launcher#266]
* Name: Hydroponics
* Url: [Google Drive](https://drive.google.com/file/d/1avdtB8WsRPaBtx4zbQhjBK9gtWQ4ujYq/view?usp=sharing)
* Author:  Unknown
* Maintainer: Tiny Hippo

**Comment by remyroy** [comment]
Where did you learn about this mod? Does it have a homepage somewhere?

**Comment by remyroy** [comment]
It should be added with 065a93db6c3f25e477cc1020d13d65b71ba6efdf . It will be part of the next release.
