### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by devilstars** [remyroy/CDDA-Game-Launcher#27]
Hello!

Are you going to make this launcher be multilingual? 

I can help you with russian translation.

**Comment by remyroy** [comment]
I did not have the intention of doing it but if people like yourself manifest themselves to help out doing it, I might as well do it.

Let's keep this issue open until I complete the first few steps of this.

**Comment by devilstars** [comment]
Waiting impatiently! Russian community will be greatly appreciated if you add localization support :)

**Comment by remyroy** [comment]
Initial support for Localization is currently being added. Do you know how to work with `.pot` and `.po` files? I will send you a `.po` file will all the messages in it and you will have to add the Russian ones in with an editor like [Poedit](https://poedit.net/) or something else.

**Comment by devilstars** [comment]
Sure. My email is mail@dev3l.ru

**Comment by remyroy** [comment]
The Russian po file is located in https://github.com/remyroy/CDDA-Game-Launcher/blob/master/cddagl/locale/ru/LC_MESSAGES/messages.po . If you know how to use git and github, it would be great if you could do a pull request with your translations.

**Comment by remyroy** [comment]
Some of the messages include HTML or Markdown markup which must be preserved and not translated. Some of the messages contains Python formatting elements that are replaced in the code. Those fragments often look like `{some_name}` or `{0}`. Those fragments can be moved but they must be preserved as well.

**Comment by remyroy** [comment]
Some messages uses gettext plural form. It seems there are 3 different plural forms in Russian. It should look something like this in the .po file:
```
#: cddagl/ui.py:5155
msgid "file"
msgid_plural "files"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
```

Form 0 should correspond to `(n%10==1 && n%100!=11)`, form 1 should correspond to `n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20)` and form 2 should correspond to the other cases. I'm not familiar with Russian but that should tell you something. If not, let me know and I'll try to explain it in my own words.

**Comment by devilstars** [comment]
I've translated everything, but can't do a pull request.

```
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
Pushing to git@github.com:remyroy/CDDA-Game-Launcher.git

ERROR: Permission to remyroy/CDDA-Game-Launcher.git denied to devilstars.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
No idea what to do with it. 
![2016-02-19_111210](https://cloud.githubusercontent.com/assets/12907959/13167091/aa52eb46-d6f9-11e5-8dfc-e6553f1ea4f1.png)

**Comment by Malkeus** [comment]
That looks like you're trying to push directly to remyroy's repository. Instead fork his repository to your account, make your changes to that fork and then issue a pull request from there.

**Comment by devilstars** [comment]
Thank you for the tip! Seems ok now.

**Comment by Malkeus** [comment]
Glad to help :+1:

**Comment by remyroy** [comment]
I have an initial version that include your Russian translations. Download it from https://www.dropbox.com/s/msr0l8dticbxqgm/launcher.exe?dl=0 . Check out if the translations make sense. You might need to go in the Settings tab, change the language and restart the launcher to see the Russian interface. I'm working on having the interface language change as soon as you select a different language but that will take more time.

I had to correct a few things and add a few translations as well. If you could pull the latest version from my repository into yours, check out the new missing translations and update the new po file (https://github.com/remyroy/CDDA-Game-Launcher/blob/master/cddagl/locale/ru/LC_MESSAGES/cddagl.po) that would be great. If you need help with anything, let me know.

**Comment by remyroy** [comment]
If you want to give me your full name, I will gladly add you into a new section for Translators in the About window as well so that you can be part of the credits. I can also just add Daniel or devilstars if you want.

**Comment by devilstars** [comment]
I've trasnlated new strings and fixed some mistypes. New pull requst is done :)

Btw everything works fine, good job! 

Also i've created new #37 issue about russian font for the game.

**Comment by devilstars** [comment]
> If you want to give me your full name, I will gladly add you into a new section for Translators in the About window as well so that you can be part of the credits. I can also just add Daniel or devilstars if you want.

Is it possible to add my name (Daniel) and website http://cataclysmdda.ru ? It's a russian community website where we have some wiki articles, translated changelogs and installers.

**Comment by remyroy** [comment]
Sure. I'll add your website along your name in the *credits* section.

**Comment by remyroy** [comment]
@devilstars You should tell the author of http://cataclysmdda.ru to include my [OS X Experimental builds](http://smf.cataclysmdda.com/index.php?topic=11629.0) in their Mac OS X download section :)

**Comment by remyroy** [comment]
This is completed with the recent commits.

**Comment by remyroy** [comment]
@devilstars I'm getting a big new feature (saves backup) included in the upcoming version. I've updated the Russian po file if you want to get started with the new messages.

**Comment by Laughingmanhk** [comment]
I can help with the traditional Chinese translation. How can I get started? Thanks.

**Comment by Laughingmanhk** [comment]
> @devilstars I'm getting a big new feature (saves backup) included in the upcoming version. I've updated the Russian po file if you want to get started with the new messages.

I can help with the traditional Chinese translation. How can I get started? Thanks.

**Comment by remyroy** [comment]
@Laughingmanhk Hi there. You can use a software called [Poedit](https://poedit.net/) with the proper .po file to add your translation to the game. There are various Chinese language code for various regions or variation. See https://stackoverflow.com/questions/4892372/language-codes-for-simplified-chinese-and-traditional-chinese . Let me know which one of the following language codes you want to do:

* **zh_CN** for mainland China
* **zh_SG** for Singapore
* **zh_TW** for Taiwan
* **zh_HK** for Hong Kong
* **zh_HANS** for (generic) simplified Chinese characters
* **zh_HANT** for (generic) traditional Chinese characters

Once I know the language code, I can create the proper .po files to be used with Poedit and you'll be able to start translating.

**Comment by Laughingmanhk** [comment]
> @Laughingmanhk Hi there. You can use a software called [Poedit](https://poedit.net/) with the proper .po file to add your translation to the game. There are various Chinese language codes for various regions or variations. See https://stackoverflow.com/questions/4892372/language-codes-for-simplified-chinese-and-traditional-chinese . Let me know which one of the following language codes you want to do:
> 
> * **zh_CN** for mainland China
> * **zh_SG** for Singapore
> * **zh_TW** for Taiwan
> * **zh_HK** for Hong Kong
> * **zh_HANS** for (generic) simplified Chinese characters
> * **zh_HANT** for (generic) traditional Chinese characters
> 
> Once I know the language code, I can create the proper .po files to be used with Poedit and you'll be able to start translating.

@remyroy Thanks for the detailed answer. Poedit seems awesome and much better than working on notepad++. Long story short, I would like to work on **zh_HANT** first, then translate it to **zh_HANS** afterwards.

**Comment by remyroy** [comment]
Here is the zh_HANT: [zh_HANT-cddagl.zip](https://github.com/remyroy/CDDA-Game-Launcher/files/2992144/zh_HANT-cddagl.zip)
Here is the zh_HANS: [zh_HANS-cddagl.zip](https://github.com/remyroy/CDDA-Game-Launcher/files/2992149/zh_HANS-cddagl.zip)

Some others notes regarding the translations. Some of the messages include HTML or Markdown markup which must be preserved and not translated. Some of the messages contains Python formatting elements that are replaced in the code. Those fragments often look like {some_name}, {0} or %s. Those fragments can be moved but they must be preserved as well.

If you need more help or support, let me know.

**Comment by remyroy** [comment]
@Laughingmanhk I'm doing a quick follow up. How is the translation going? Do you need any help with that?

**Comment by Laughingmanhk** [comment]
> @Laughingmanhk I'm doing a quick follow up. How is the translation going? Do you need any help with that?

Half way to go. Could finish it by Mid-April. 
Is there any way that I can "plug" the translation into the launcher for a test run? Some adjustments might required for me to make the User Interface in shape.

**Comment by remyroy** [comment]
I can create some custom build for you to test it. Just send me the file and I'll provide the binary. That's the easiest way.

There is no rush for the translations. Take your time.

**Comment by remyroy** [comment]
@Laughingmanhk I'm doing another quick follow up. Can I help you with creating a test build with what you currently have translated?

**Comment by remyroy** [comment]
@Laughingmanhk Are you still working on the translation? Let me know.

**Comment by Laughingmanhk** [comment]
Hi Roy,
70% right now. Currently I am working on a few projects, also struggling
about the translation of a few key words.
I'll let you know once it's done. Many thanks.
Michael aka Laughingmanhk

Rémy Roy <notifications@github.com> 於 2019年5月16日週四 下午11:46寫道：

**Comment by remyroy** [comment]
@Laughingmanhk Are you still working on the translations? If you are partially done, you can send me what you have and I can create a test build to see how it shows.
