### ISSUE TITLE
Hosting location for experimentals is changing

### ISSUE THREAD

**Issue by narc0tiq** [remyroy/CDDA-Game-Launcher#277]
Per @kevingranade's suggestion/acceptance, we're going to put the experimentals in <https://github.com/CleverRaven/Cataclysm-DDA/releases>, marked as pre-releases.

Expect all the experimentals to be tagged `cdda-jenkins-b${BUILD_NUMBER}`. Assets will be named:
- `cataclysmdda-${MAJOR_VER}-${Platform}-${Graphics}-${BUILD_NUMBER}.zip` for Windows
- `cataclysmdda-${MAJOR_VER}-${Platform}-${Graphics}-${BUILD_NUMBER}.tar.gz` for Linux
- `Cataclysm-${MAJOR_VER}-${Platform}-${Graphics}-${CURRENT_BUILD_NUMBER}.dmg` for OSX
- `Cataclysm-${MAJOR_VER}-${CURRENT_BUILD_NUMBER}.apk` for the single Android build

Please also note that Windows Curses builds were disabled a few days ago, to save build time (it was also suggested that Wincurse builds perform worse than Windows Tiles builds with the tiles turned off).

Expect the current hosting to disappear (replaced by some kind of redirect) around mid-May -- my bandwidth allotment is about to reset, so I can keep it up for a while longer.

---

I'm hanging out on [the CDDA discord](https://discord.gg/DPxUcX7) if you want some real-time interaction.

**Comment by remyroy** [comment]
This should be implemented with 2797a7b418d55c65b16cafc0d467f0c4d0b33a45 .
