### ISSUE TITLE
Unhandled exception: [Launcher Error]

### ISSUE THREAD

**Issue by Bobito-Gonzales** [remyroy/CDDA-Game-Launcher#280]
* Description: [I tried to open the launcher]
* Version: 1.3.16
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is a duplicate of #271 and it should be fixed in 1.3.19 .

**Comment by Bobito-Gonzales** [comment]
Yes, but right now I can’t even open the launcher app, so I am unable to download new versions of it.
And I would rather not have to erase it from my computer and install it again, because I would then loose my saves, which would suck tremendously.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Rémy Roy <notifications@github.com>
Envoyé : Tuesday, April 30, 2019 2:51:57 PM
À : remyroy/CDDA-Game-Launcher
Cc : Bobito-Gonzales; Author
Objet : Re: [remyroy/CDDA-Game-Launcher] Unhandled exception: [Launcher Error] (#280)


This is a duplicate of #271<https://github.com/remyroy/CDDA-Game-Launcher/issues/271> and it should be fixed in 1.3.19 .

**Comment by remyroy** [comment]
You won't lose your saves if you update the launcher. Just replace the launcher binary file with the new one.
