### ISSUE TITLE
Unhandled exception: [Cannot launch]

### ISSUE THREAD

**Issue by SkunkDave** [remyroy/CDDA-Game-Launcher#282]
* Description: [Launching launcher no workie]
* Version: 1.3.16
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by dsmky117** [comment]
#271 fixed in version 1.3.19
https://github.com/remyroy/CDDA-Game-Launcher/releases
