### ISSUE TITLE
Slow Startup with Kaspersky AV

### ISSUE THREAD

**Issue by AeonBlack** [remyroy/CDDA-Game-Launcher#283]
This doesn't and hasn't played nice for many versions with the Kaspersky Anti-Virus on Windows 10 during application startup, taking over 10 minutes on average to load

Causes Kaspersky to go into a higher than usual CPU usage (16% on my system) while files are being unpacked each time to Temp directory, though launcher loads instantly when added to exclusions

Issue is no faster on SSD compared to HDD either

**Comment by remyroy** [comment]
There is [a plan](https://github.com/remyroy/CDDA-Game-Launcher/issues/170#issuecomment-429989965) to solve part of this with a new distribution and a new installer. I just need to do it.

**Comment by KurzedMetal** [comment]
@remyroy Maybe you can add another zip to GitHub releases with the "multi-file" compiled version and let the users download what they prefer?

I personally have been running a self-compiled version of the project without the "one file" flag and it launches so much faster (even without AV software).

**Comment by remyroy** [comment]
Yeah, I wanna do a proper installer that wouldn't use the self-extracting single binary. Just need some time to do it.

**Comment by KurzedMetal** [comment]
Do you have any installer software in mind? Maybe I could give it a look when I get home.

A long time ago I researched some alternatives for installers and I think InnoSetup and NSIS where the most recommended for Open Source.

**Comment by remyroy** [comment]
I've used NSIS in the past with good result but I wanted to check InnoSetup again. I've also wanted to check Wix toolset but that will need a lot more efforts.

My only base requirement for the installer is easy version detection and easy upgrade (version check + painless uninstall/reinstall). This can be done with NSIS but it will require some scripting. Wix toolset and MSI has done things already included but they are much more involved.

**Comment by KurzedMetal** [comment]
I've been reading stuff around (documentation, examples, guides, etc), and seems like:

* Wix: From what I've read, seems like a great tool but way more complex than NSIS or Inno, although you can create real MSI installer (which can't be done with the other two). But arguably that's not necessary for the CDDA Launcher.
* NSIS: I remember it is a classic on the web, but I after I explored it, I personally can't stand the ugly custom language it has, I didn't like the UI and documentation seems a bit lacking / poorly formatted.
* Inno: It has an usable UI and wizard, documentation seems to have good quality (an insta win in my book) and I actually don't mind Pascal scripting (even if I don't know much of the language).

To my inexperienced eyes in the subject, InnoSetup wins hand down...
And I actually downloaded it and gave it a try: the Wizard covered the basics really fast and after some research and testing I found a solution for detection of a previous installation and letting the user uninstall before re-installing (no version check, just makes sure it uninstall anything previous with the same AppId, which is enough IMO).

So I think I actually managed to create a config / script to do exactly what you'd need with the Launcher. :)
I'll probably create a PR soon (when I tweak it and test it a bit more)

**Comment by remyroy** [comment]
@KurzedMetal That's great! I would still like version check but I guess we can do without.

**Comment by remyroy** [comment]
This issue should be alleviated with @KurzedMetal work and the next release that will use a proper setup.
