### ISSUE TITLE
CO.AG Soundpack has the wrong link attached to it.

### ISSUE THREAD

**Issue by MeCodeMyself** [remyroy/CDDA-Game-Launcher#284]
Pretty much. Just wanted to inform people who only download sound packs from the launcher and **the owner of course.**

**Comment by remyroy** [comment]
Do you mean it has the wrong homepage link or the wrong url link? What would be the right link so it can be updated properly?

**Comment by MeCodeMyself** [comment]
So basically when you press the link to download the sound pack it takes you to a mod. About something completely unrelated to the sound pack. Same thing as #270 really.

**Comment by remyroy** [comment]
It should be fixed in 6ab707f59924e73b68be87a3d014ebbf31a676d2 .
