### ISSUE TITLE
Unhandled exception: crash.

### ISSUE THREAD

**Issue by kickymcassington** [remyroy/CDDA-Game-Launcher#285]
* Description: I started the launcher a day after using it successfully on the same boot and it crashed with this error. I will update or delete this report if it works properly after a reboot.
* Version: 1.3.15
* OS: Windows-10-10.0.15063 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by MeCodeMyself** [comment]
Update to the latest version, it fixed it for me.

**Comment by kickymcassington** [comment]
Thanks i'll try updating now. report back if its fixed.

**Comment by DaliTimelord** [comment]
Happened to me, re-downloading newest version seems to fix this.

**Comment by kickymcassington** [comment]
Yup updating the launcher fixed it, thanks guys!
I'll close the issue now.
