### ISSUE TITLE
Unhandled exception: Crash soon after executing the program

### ISSUE THREAD

**Issue by FulcrumA** [remyroy/CDDA-Game-Launcher#286]
* Description: Turned on the launcher. Split second after main window opened and started checking the version, it closed and an error message popup shown up instead.
* Version: 1.3.15
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by dsmky117** [comment]
#271 fixed in version 1.3.19
https://github.com/remyroy/CDDA-Game-Launcher/releases
