### ISSUE TITLE
Unhandled exception: [Launcher Error]

### ISSUE THREAD

**Issue by ronyle143** [remyroy/CDDA-Game-Launcher#287]
* Description: [open launcher and let it load for a second]
* Version: 1.3.16
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in 1.3.19. For more details see #271 .
