### ISSUE TITLE
Unhandled exception: [Crash on Launch]

### ISSUE THREAD

**Issue by TheEventHorizon** [remyroy/CDDA-Game-Launcher#288]
* Description: [Enter what you did and what happened]
* Version: 1.3.16
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in 1.3.19. For more details see #271 .

**Comment by Brambor** [comment]
Same here...

* Description: Launched the launcher, it tried to look for latest builds. I think that this is what caused it.
* Version: 1.3.15
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in recent versions. You should update your game launcher. See #281 for more details.

**Comment by Brambor** [comment]
Yup, just did that, all works fine.
