### ISSUE TITLE
Detecting the game directory

### ISSUE THREAD

**Issue by devilstars** [remyroy/CDDA-Game-Launcher#29]
Hello!

Is it possible to detect the directory where Launcher is being launched? 

For example.
1. I have a game installed in c:\game\cdda
2. I put there a laucher and tha path in laucher is automatically corrected to c:\game\cdda
3. If i put laucher in c:\game2\cdda - the patch in luacher is automatically corrected to c:\game2\cdda

**Comment by remyroy** [comment]
I'll add this as an option in the settings.

**Comment by remyroy** [comment]
This is implemented with 1b5a0d879b735d66c04b1d26256cf4f60e16b184 . It will be part of the next release.
