### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by M1nks** [remyroy/CDDA-Game-Launcher#292]
* Description: When trying to run CDDA Launcher I get this message - this is the first time I've seen it.  I tried 'running as an administrator' and I didn't get the message.  The Error included a note asking me to report it on GitHub so that's what I'm doing.  If you need any other information please ask.
* Version: 1.3.16
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by METPO** [comment]
I have the same mistake

**Comment by M1nks** [comment]
Edit: Actually it does crash with that same error even when running 'as admin'.  However if I don't close down the error and just try launching it again I can get it to run.

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by M1nks** [comment]
Righto.  Cheers.
