### ISSUE TITLE
Необрабатываемое исключение: [Введите заголовок]

### ISSUE THREAD

**Issue by Joanakor** [remyroy/CDDA-Game-Launcher#294]
* Описание: [Напишите, что вы делали и что произошло]
* Версия: 1.3.16
* OS: Windows-8.1-6.3.9600 (64-bit)
* Тип: `<class 'TypeError'>`
* Значение: '<' not supported between instances of 'NoneType' and 'str'
* Диагностика:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by remyroy** [comment]
As mentioned, this is fixed in 1.3.19. See #281 for more details.
