### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by musienco-dn** [remyroy/CDDA-Game-Launcher#296]
* Description: [Just started to freak out 2 days ago. Without even updating. Then I updated, and nothing changed. Just crashed anytime I try and start the launcher.]
* Version: 1.3.18
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by remyroy** [comment]
As mentioned, this is fixed in 1.3.19. See #281 for more details.
