### ISSUE TITLE
CDDA launcher crash

### ISSUE THREAD

**Issue by paradigm369** [remyroy/CDDA-Game-Launcher#298]
<img width="361" alt="CDDA launcher crash" src="https://user-images.githubusercontent.com/45728231/57011290-7dba3d00-6c33-11e9-8e5d-b5f662e5d292.PNG">
* Description: CDDA launcher unable to launch
* Version: 1.3.15
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by paradigm369** [comment]
Thanks!
