### ISSUE TITLE
Launcher crash

### ISSUE THREAD

**Issue by Mister-Cultist** [remyroy/CDDA-Game-Launcher#299]
* When I open the launcher I get an error thrown at me
* Version: 1.3.15
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by remyroy** [comment]
As mentioned, this is fixed in 1.3.19. See #281 for more details.
