### ISSUE TITLE
[Suggestion] Add option to not auto-close the launcher when launching the game

### ISSUE THREAD

**Issue by harald921** [remyroy/CDDA-Game-Launcher#3]
As the title says - make it possible to choose whether or not the launcher should close when launching the game. I often restart my game (totally not save-scumming, cough cough) and it'd be very helpful!

**Comment by remyroy** [comment]
That should be easy enough, I'll try to add it in the next release.

**Comment by remyroy** [comment]
Completed in 329abed96ae6744432ce0201c73f17df16310830 . It should be part of the next release.
