### ISSUE TITLE
Unhandled exception: [launcher crash]

### ISSUE THREAD

**Issue by Ulficek** [remyroy/CDDA-Game-Launcher#300]
* Description: [opened a launcher, it worked just fine yesterday]
* Version: 1.3.16
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by eliotcougar** [comment]
Known issue. Update the launcher to 1.3.19

**Comment by METPO** [comment]
> Known issue. Update the launcher to 1.3.19

How do I update the launcher if it doesn’t even open?&&&

**Comment by dsmky117** [comment]
You have to redownload:
https://github.com/remyroy/CDDA-Game-Launcher/releases/tag/v1.3.19

**Comment by remyroy** [comment]
As mentioned, this is fixed in 1.3.19. See #281 for more details.
