### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by Tefnut** [remyroy/CDDA-Game-Launcher#304]
* Description: [Enter what you did and what happened]
* Version: 1.3.15
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in 1.3.19. See #281 for more details.
