### ISSUE TITLE
Fatal Error: Failed to execute script launcher

### ISSUE THREAD

**Issue by spoompkin** [remyroy/CDDA-Game-Launcher#305]
For the past months, every time I've tried to open up the launcher I've recieved this error:
![Screenshot_3](https://user-images.githubusercontent.com/26240743/57052942-c24ee280-6cde-11e9-9a03-2ab9a0962b12.png)

I have tried messing around with the install locations, turning all antivirus potential off, and more reinstalls than I can remember. It seems to be happening regardless of the version, and it's quite strange as I've used the launcher for a good long while by this point. It popped out of nowhere, basically.

My OS is Windows 10, let me know if you need any more info.

I'm aware that a similar issue was already posted (#109), but my issues still persist despite doing the steps entailed within that issue.

**Comment by hrabnaz** [comment]
I have the exact same problem, i tried another partition with windows 7 and it worked, so this issue is specific to Win10. I tried different versions of the launcher, none worked. Different computers with Win10 works though.

**Comment by remyroy** [comment]
Those kind of issues are hard to test for. They are often system dependent.

Can you try installing [the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)? The exact one should be [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe).

**Comment by hrabnaz** [comment]
I already did that, several times. It still doesn't work. Is there any other windows component your software depends on? Like, it works on win 7 and nearly any other Win10 computer i tested, so it must be something on this windows installation specifically.

**Comment by remyroy** [comment]
Did you try this one in specific? https://aka.ms/vs/16/release/vc_redist.x86.exe ?

Every other dependencies is bundled with the distribution.

**Comment by hrabnaz** [comment]
I did now, it didn't change anything. This is getting weird :D

**Comment by remyroy** [comment]
I'm trying to build a debug version of the launcher to get more developer informations. Unfortunately, that debug version is bugged at the moment. As soon as I can fix this, I'll publish a private debug version of the launcher. If you could run that version and let me know what is shown on screen, that would help me fix your issue.

**Comment by hrabnaz** [comment]
Allright, as soon as you release it i will test it. Thanks for your effort and keep up the good work :D

**Comment by remyroy** [comment]
Try this portable test version: https://www.dropbox.com/s/6t2673h3q3pp86a/cddagl_portable_v1.4.testcrash%2B7846d45.zip?dl=1

Start `launcher.bat`. You are likely to see some kind of black window for a few seconds. Wait until it goes away. A new file called logs.txt will be created in the same directory. Go to https://gist.github.com/ and paste the content of that file in there. Share the link to that gist so I can see the content.

**Comment by hrabnaz** [comment]
https://gist.github.com/hrabnaz/b48399a43d2110873ec018f270a0b102 alright, here it goes. Hope this helps.

**Comment by remyroy** [comment]
Try deleting the following file: `%LOCALAPPDATA%\CDDA Game Launcher\configs.db` and try again.

**Comment by spoompkin** [comment]
Interestingly enough, I recently got a new laptop (using Windows 10 still) and it can run the launcher fine.

**Comment by remyroy** [comment]
With this recent change e84e20794d7709a0c220b87525a35335b345d083 , I've handled that specific case. It should be fixed in the next release.

**Comment by hrabnaz** [comment]
Yes, that worked. Thank you!
