### ISSUE TITLE
Unhandled exception: luchup failure

### ISSUE THREAD

**Issue by RedBloodCat** [remyroy/CDDA-Game-Launcher#309]
* Description: started the launcher
* Version: 1.3.16
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in 1.3.19. See #281 for more details.
