### ISSUE TITLE
Unhandled exception: Launching launcher

### ISSUE THREAD

**Issue by BQurious** [remyroy/CDDA-Game-Launcher#312]
* Description: Opened the launcher, saw the window momentarily (I think all the entries were blank), then crashed with the error. Seems to always occur right
* Version: 1.3.16
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in 1.3.19. See #281 for more details.
