### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by YukariMindGap** [remyroy/CDDA-Game-Launcher#315]
* Name: Nechronica Redux
* Url: https://github.com/YukariMindGap/Necronica_Redux
* Author: YukariMindGap
* Homepage: https://discourse.cataclysmdda.org/t/nechronica-redux/19857
* Mod not found in version: 1.3.21

**Comment by remyroy** [comment]
Added with 1b2d002827b12a62e96548c77584a828235b9318 . It will be part of the next release.
