### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by greygale** [remyroy/CDDA-Game-Launcher#317]
* Description: Attempted to run game launcher, game launcher popped up for a moment and then failed generating this error
* Version: 1.3.16
* OS: Windows-7-6.1.7601 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by Tsurupeta** [comment]
Same issue

**Comment by remyroy** [comment]
This is fixed in recent versions. You should update your game launcher. See #281 for more details.
