### ISSUE TITLE
Unhandled exception: Unable to launch launcher

### ISSUE THREAD

**Issue by TommyGun3211** [remyroy/CDDA-Game-Launcher#319]
* Description: [Enter what you did and what happened]
* Version: 1.3.16
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in recent versions. You should update your game launcher. See #281 for more details.
