### ISSUE TITLE
Unhandled exception: Unstable Nuke Launcher

### ISSUE THREAD

**Issue by GrandpuhTy** [remyroy/CDDA-Game-Launcher#324]
* Description: Backed up my current saves and went to refresh the update list when it bugged out. Crashes on on loading the update list, but will launch.
* Version: 1.3.16
* OS: Windows-8.1-6.3.9600 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by JeremiasB** [comment]
Got the same Error:
CDDA Game Launcher version: 1.3.16
OS: Windows-10-10.0.17134 (64-bit)
Type: <class 'TypeError'>
Value: '<' not supported between instances of 'NoneType' and 'str'
Traceback:
File "cddagl\ui.py", line 3078, in lb_http_finished

**Comment by remyroy** [comment]
This is fixed in recent versions. You should update your game launcher. See #281 for more details.
