### ISSUE TITLE
Unhandled exception: 

### ISSUE THREAD

**Issue by Fizzban** [remyroy/CDDA-Game-Launcher#333]
* Description: I haven't opened the launcher in a little while. I opened it from a shortcut on my taskbar and it threw this error.
* Version: 1.3.15
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by remyroy** [comment]
This is fixed in recent versions. You should update your game launcher. See #281 for more details.
