### ISSUE TITLE
Launcher triggers Suricata IDS false positive

### ISSUE THREAD

**Issue by 81Denton** [remyroy/CDDA-Game-Launcher#335]
Version used: 1.3.1.19
OS: Win 10 x64

Hi,
when the launcher connects to the server at startup, Suricata and any other IDS falsely identify this as a network trojan: https://doc.emergingthreats.net/bin/view/Main/2010645

Probably has to do with the launcher using port 8080 HTTP instead of HTTPS. IMO not a huge issue, but maybe interesting if you're getting reports of people with connectivity issues (because their IDS blocks the server connection).

**Comment by remyroy** [comment]
False positives are common with many poor security softwares.

If you are paranoid, you can always build the launcher from the source code. You are still likely to get this false positive. There is very little productive efforts we can do as software developers with these false positives.
