### ISSUE TITLE
Updating creates a bunch of junk in the recycling bin

### ISSUE THREAD

**Issue by dsmky117** [remyroy/CDDA-Game-Launcher#336]
On v1.3.19, each time you update the game, the previous_version folder is moved to the recycling bin, rather than deleted permanently. This folder contains only the game files of the previous version, **not saves** (edit: saves are actually recycled when 'Do not copy of move the save folder' is unchecked), so for most users these files are useless. In addition, the .zip downloaded containing the new version is moved to the recycling bin.

Each update moves a ~270MB folder composed of ~3800 files and a .zip of ~85MB to the recycling bin, which adds up quickly if you, like me, update the game way too often. I'd like to at least have the option to permanently delete instead of recycling since those files are useless to me.

**Comment by remyroy** [comment]
A new (not recommended) setting could be added for that that would use the old method of permanently delete files. I'll see what I can do for that.

**Comment by remyroy** [comment]
This option to permanently delete files instead of moving them in the recycle bin has been added with 0f688875db5947e8d1e983188e9a2b105299e2b8 . It will be part of the next release.
