### ISSUE TITLE
Необрабатываемое исключение: [Введите заголовок]

### ISSUE THREAD

**Issue by IceProteus** [remyroy/CDDA-Game-Launcher#344]
* Описание: [Пытался в лаунчере установить саундпак]
* Версия: 1.3.22
* OS: Windows-10-10.0.17763 (64-bit)
* Тип: `<class 'FileNotFoundError'>`
* Значение: [Errno 2] No such file or directory: 'D:\\Загрузки\\CO.AG SoundPack (v1.1) (02-Mar-19).zip'
* Диагностика:
```
  File "cddagl\ui.py", line 4567, in install_new
  File "zipfile.py", line 1090, in __init__

```

**Comment by remyroy** [comment]
Can you provide an English description? I believe this is a duplicate of #334

**Comment by IceProteus** [comment]
Проблема решена )
