### ISSUE TITLE
Error With 1.4 - Update cancelled - Could not delete previous_version directory

### ISSUE THREAD

**Issue by JazzGuru** [remyroy/CDDA-Game-Launcher#346]
As of today, I am no longer able to update my game past 9092, as the launcher keeps on telling me that it is unable to delete the Previous Version directory.  If I try to manually delete that folder, then the launcher will no longer work, as it tells me that the launcher.exe shortcut has been changed or moved, so it will no longer work properly.

Hope this won't be too difficult to sort out... :)

**Comment by remyroy** [comment]
Did you put the launcher in your game directory? It feels like you did. If so, just install the launcher somewhere else.

Did you use the installer or the portable version?

**Comment by JazzGuru** [comment]
Hi,
Yes, the installer was in my game directory, as I like to keept hings tidy.  It just broke the habit of a lifetime, having to 'launch' the launcher through the start menu, but if that's how it has to be... :D

**Comment by remyroy** [comment]
You can still create a shortcut to your launcher on the desktop or somewhere else.

**Comment by JazzGuru** [comment]
Thanks remyroy, it's all sorted now... :)
