### ISSUE TITLE
Launcher crashes when changelog doesn't update

### ISSUE THREAD

**Issue by AnonymousCaptain** [remyroy/CDDA-Game-Launcher#352]
Whenever I try to update, the launcher crashes while downloading. The download progress bar suddenly changes to "Ready" before crashing even though the download hasn't completed downloading, the "Cancel update" button also stays the same before crashing.

This has occurred on previous versions of the launcher starting from 1.31.12

EDIT: It also crashes when left alone.

**Comment by remyroy** [comment]
Have you tried the latest version?

**Comment by AnonymousCaptain** [comment]
Yep but the same problem occurs.

**Comment by AnonymousCaptain** [comment]
I just realized that this only occurs if the changelog can't be loaded by the launcher.

**Comment by remyroy** [comment]
What does crashes mean? What does a crash looks like?

In case of doubt, check out [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by AnonymousCaptain** [comment]
The launcher simply freezes and becomes unresponsive, even after waiting for several minutes. 
![Crash 1](https://user-images.githubusercontent.com/43717339/59660864-215bae80-91dc-11e9-843f-d102035a8a0f.PNG)

**Comment by KurzedMetal** [comment]
Can you still reproduce this or was it temporary?

Try opening this this manually if still happens: http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/api/xml?tree=builds[number,timestamp,building,result,changeSet[items[msg]],runs[result,fullDisplayName]]&xpath=//build&wrapper=builds

Can you go to `%localappdata%\CDDA Game Launcher` (paste that in your Windows Explorer) and uploading the file `app.log` in that folder?

Sorry for so many questions, Just trying to gather some info to find what's causing the problem.

**Comment by AnonymousCaptain** [comment]
I can still reproduce this on some WIFI connections, if the launcher can't load the changelog due to an issue with the WIFI, it will freeze the launcher.
[app.log](https://github.com/remyroy/CDDA-Game-Launcher/files/3303802/app.log)

**Comment by KurzedMetal** [comment]
That "gorgon.narc.ro" link is just the source where the launcher gets the Changelog information, I was trying to rule out if your ISP had some connection issue with that page, but if you see information in that link, it means it's working.

Anyways, thanks for the `app.log` file, it's already showing an error message in there:
```
2019-06-18 15:11:26,370 - cddagl - INFO - CDDA Game Launcher started: 1.4.1
2019-06-18 15:12:10,383 - cddagl - CRITICAL - Global error:
Launcher version: 1.4.1
Type: <class 'xml.etree.ElementTree.ParseError'>
Value: no element found: line 1, column 0
Traceback:
  File "cddagl\ui.py", line 1825, in run
  File "xml\etree\ElementTree.py", line 1315, in XML
```

**Comment by KurzedMetal** [comment]
@AnonymousCaptain thanks for the information so far, can I ask you one last thing?
I've proposed an improvement to avoid the crash in the future in case anyone isn't able to load the Changelog.
But I'm still not sure why you aren't able to download the changelog information in the first place...
Can you open [Jenkins Build API with Changelog info](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/api/xml?tree=builds[number,timestamp,building,result,changeSet[items[msg]],runs[result,fullDisplayName]]&xpath=//build&wrapper=builds) (it's the same long link I put up there) and upload a file with the content here?

**Comment by AnonymousCaptain** [comment]
I switched back to the WIFI connection where I can't download the changelog and turns out I can't connect to Jenkins now as well. 

This seems to either be an IP issue or the security system for this network is intentionally blocking this website (Most likely the security system though).
