### ISSUE TITLE
Project organization: Refactoring code base

### ISSUE THREAD

**Issue by KurzedMetal** [remyroy/CDDA-Game-Launcher#355]
Hi remy, this is not a bug report but I wanted to ask you about this and didn't know how to contact you otherwise. Also, maybe someone else can add up something on the subject or have it as reference for future contributions.

In a few of the PRs I worked I felt the need a few times to actually do some refactor on the code (I actually did some work but reverted them back / deleted them from my PRs before submission because I thought it was too much for a mere fix).
I think it could be easier to maintain, spot bugs and test if we split the 8k lines from ui.py is split into multiple more organized package/module structure and some refactor is done.

I was specially thinking about:
* remove ui.py dependency on globals as possible (maybe even reduce class property usage where possible).
* use a simple MVC-like design to separate UI logic from non-UI logic.
* move code into better and more granular package / module hierarchy.
* try to avoid high levels of nesting when refactoring
* reduce the amount of Qt events to simplify analyzing non-UI logic (where / if possible).
* add unit testing to avoid future fk ups (only possible if separating of UI vs non-UI logic is done)
* maybe improve documentation of methods and classes (I actually like adding documentation, but ofc, having an organized doc-less code is more important)
* optional: ignore pep8 recommendation on line length, IMO 79 chars per line is too conservative and restrictive, the gains from constraining to 79 chars are not that great, code could be way more readable at a 100 or 120 chars limit, and still let to easily do side by side comparisons or even three way merges easily in modern Monitors and IDEs. I personally think 99 chars is a solid upgrade that even pep8 mention and accepts.

I know this can be a large work and may introduce new bugs, but also can make the code shorter, more maintainable and robust for future changes in the long run.
Also, it doesn't have to happen all in one go, maybe it can be slowly done when doing changes for new features / bugs.

Have you ever thought about doing this? What's your opinion?
Would you accept PRs for code refactor?
Is there anything you'd forbid about this in your project or maybe anything else you thought it would be nice to improve / add?

EDIT: Adding a TODO list:
- [X] **(Done in #357)** Remove globlals and class dependencies from globals from ui.py classes.
- [x] **(Done in #357)** Separate ui.py classes into different files.
- [ ] Make the code shorter and more readable, aiming for easier maintainability.
- [ ] Refactor UI classes trying to separate UI logic and non-UI logic into different methods.
- [ ] Use a simple MVP pattern with DI to organize project code, moving UI logic into Presenters and non-UI logic into Models.
- [ ] Add unit tests where is possible.

While working on the previous items, I'll try to follow this good practices:
* Organize code into a better package / module hierarchy.
* Improve code self-documentation (with function, method and classes docstrings)
* Try to reduce current levels of block nesting
* Move into a 99 chars per line project style
* Add more logging at DEBUG / INFO level to help troubleshooting bugs

(I didn't want to add these in the TODO list because I'll have to constantly apply this while working on each TODO item.)

**Comment by remyroy** [comment]
I started doing some refactoring in one of my stash but I abandoned. I would gladly accept refactoring and documentation PRs. All the ideas you mentioned above seems pretty good.

It's hard to say which things I would forbid ahead of time. If it makes sense, if it respect the license and if it helps the overall project, I don't see why I would be against it.

I like following pep8. I know the maximum line length is a pain and I've violated that rule in a few cases. I agree that we could go to 99 and I would accept PRs that go to 99.

Shorter PRs and more frequent PRs would probably be the way to go as you mentioned.

There is a lot of duplicated code. Unifying those in functions, classes or methods would be a nice improvement.

I'd say go for it.

**Comment by KurzedMetal** [comment]
> All the ideas you mentioned above seems pretty good...
> It's hard to say which things I would forbid ahead of time.

I actually implicitly asked about the items I mentioned there. So, I guess you already answered that, sorry for the confusion, like the Zen of Python says "explicit is better than implicit" :P

**Comment by KurzedMetal** [comment]
I noticed splitting "business" logic from ui logic in the current code is almost impossible without a complete review/rewrite of pretty much all lines of code, which could lead to a lot of new potential bugs while refactoring (specially since there are currently no unit tests).

I've decided to stop my efforts on refactor this, I will still contribute on bugfix and maybe features if I can, but I won't be doing a complete rewrite.

**Comment by remyroy** [comment]
All your contribution are welcomed. Thanks for getting involved.
