### ISSUE TITLE
Idea: automatic backup before updating the game

### ISSUE THREAD

**Issue by RDru** [remyroy/CDDA-Game-Launcher#359]
Sometimes there are builds that can break your save. 
It would be great if there was an option to make an automatic backup before updating the game.
It would be even better if that save had build number in it.

**Comment by remyroy** [comment]
In effect, there is already a backup if you did not check the *Do not copy or move the save directory* option and if you did not check the *Remove previous_version after update* option. It's in the `previous_version` subdirectory. You can easily restore it by simply clicking the *Restore previous version* button.

**Comment by remyroy** [comment]
This has been added with a1d38f0f45d2e13ee975190bd2e338eeaa0e7b96 . It will be part of the next release.
