### ISSUE TITLE
Unable to change what folder the launcher detects the game in.

### ISSUE THREAD

**Issue by TheGamingFox1911** [remyroy/CDDA-Game-Launcher#360]
Whenever I open up the launcher, for some reason I cannot edit where the launcher detects the actual game. The option to change where it's set up is grayed out for some reason.
![Launcher](https://user-images.githubusercontent.com/52058797/59894172-36d00480-93a5-11e9-9640-c292c81869c7.png)

**Comment by remyroy** [comment]
Did you select the option to use the launcher directory as the game directory in the settings tab? If so, you might want to uncheck that option.

That option should probably be removed anyway.

**Comment by TheGamingFox1911** [comment]
I just did, and it fixed it for me. I am an idiot, thank you for helping me!
