### ISSUE TITLE
"Automatically refresh build list every" can make it easy to hit GitHub API limits

### ISSUE THREAD

**Issue by KurzedMetal** [remyroy/CDDA-Game-Launcher#364]
I just noticed that the "Automatically refresh build list every X mins" option can go as low as 1 min.

This could potentially make the user hit the GitHub limit, specially if the user manually hit the button a few times. I usually like to avoid giving users weapons to shoot themselves :P

I'd recommend setting the minimum of the option to 3 mins (that should be a max of 20 requests per minute, and AFAIK GitHub supports 60 per hour if unauthenticated).

I didn't create a PR because I can't do it now, and I didn't want to forget about it. I may do it myself in the future.

**Comment by remyroy** [comment]
Good idea. I would even put the min auto-refresh value at 5 mins. There is little value in being faster than that in my humble opinion.
