### ISSUE TITLE
Cant Install launcher due to previous version not being uninstalled, despite it being uninstalled.

### ISSUE THREAD

**Issue by ANormalPers0n** [remyroy/CDDA-Game-Launcher#371]
I encountered a issue with the cdda launcher several weeks ago where it would not start despite being in my task manager. As I figured there might be a issue with my installation, I deleted all the files from my computer, along with all cdda game files as I wanted a clean installation. However after downloading the launcher and attempting to install it, a error message informs me that it was unable to uninstall the previous version of the game and it aborts installation. I have searched my entire pc for the keywords cdda or cataclysm but there is no results. So I am unable to install because of some ghost installation that does not exist.

The error message.
![Error message](https://user-images.githubusercontent.com/53472614/62533342-654e5580-b814-11e9-8b2d-465fe6213523.PNG)

**Comment by remyroy** [comment]
I would suggest having a look at [this article](https://www.techradar.com/news/software/10-tips-for-removing-a-program-that-won-t-uninstall-907471). Make sure you have a backup of your files and computer before attempting to use any of those advanced tools mentionned in there.

**Comment by remyroy** [comment]
As a quick tip, in general, I would avoid trying to manually delete files that were installed by an installer.

As an alternative, you can always use the portable version.

**Comment by ANormalPers0n** [comment]
Okay issue solved. Now I just need to fix my original issue of the launcher not opening despite being started. Hurray for being back to square one I guess.

**Comment by remyroy** [comment]
Can you show me the log file? It should be in `%LOCALAPPDATA%\CDDA Game Launcher\app.log`

**Comment by ANormalPers0n** [comment]
[app.log](https://github.com/remyroy/CDDA-Game-Launcher/files/3472964/app.log)

**Comment by ANormalPers0n** [comment]
sure thats what you need? doesnt seem to be much in there

**Comment by remyroy** [comment]
Yep. There isn't much so I'm not sure was is wrong there.

**Comment by ANormalPers0n** [comment]
anything I should check to make sure it isint some common issue?

**Comment by remyroy** [comment]
Have you tried launching the launcher on Windows 7 or Windows XP compatibility mode? Did you install this file first https://aka.ms/vs/16/release/vc_redist.x86.exe ?

If you want to go all the way, I've created a debug version of the launcher that should show more information. Try this portable test version: https://www.dropbox.com/s/h5bx5km78xu0uu2/cddagl_portable_v1.4.1.testcrash%2Bf14fa6c.zip?dl=1

Start launcher.bat. You are likely to see some kind of black window for a few seconds. Wait until it goes away. A new file called logs.txt will be created in the same directory. Go to https://gist.github.com/ and paste the content of that file in there. Share the link to that gist so I can see the content.

**Comment by ANormalPers0n** [comment]
"pysqlite2 not found in PYZ"
Tried using the test launcher and thats the last thing to appear. any idea what this issue could be?

**Comment by ANormalPers0n** [comment]
oh i didint see the last part of your comment one moment

**Comment by ANormalPers0n** [comment]
okay so the black window is not disappearing. The last thing the window says is "pysqlite2 not found in PYZ" and it doesnt close. Will a log still be created if the process doesnt finish? I cant find the log folder if there is one

**Comment by remyroy** [comment]
If you use the launcher.bat file to start this test version of the launcher, it will create a file called logs.txt in the same directory with that wall of text in it. It will be easier to share here so I can inspect it all.

**Comment by ANormalPers0n** [comment]
[logs.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/3477696/logs.txt)

**Comment by ANormalPers0n** [comment]
I barely know anything bout coding, but after looking at this it seems the issue is whatever PYZ is.

**Comment by remyroy** [comment]
This is unrelated to the PYZ thing. I've ran the same test build on my computer and I see those messages as well. When I check for differences in your logs compare to mines, all I see is after:

```
# code object from 'C:\\Users\\Cayne.DESKTOP-OT18FLO\\Downloads\\cddagl_portable_v1.4.1.testcrash+f14fa6c\\cddagl_portable_v1.4.1.testcrash+f14fa6c\\pkg_resources\\_vendor\\packaging\\__init__.pyc'
# pkg_resources._vendor.packaging.__about__ not found in PYZ
# code object from 'C:\\Users\\Cayne.DESKTOP-OT18FLO\\Downloads\\cddagl_portable_v1.4.1.testcrash+f14fa6c\\cddagl_portable_v1.4.1.testcrash+f14fa6c\\pkg_resources\\_vendor\\packaging\\__about__.pyc'
```

mine will run the actual launcher showing those lines in my logs:

```
[2704] LOADER: Running pyi_rth_win32comgenpy.py
[2704] LOADER: Running pyi_rth_pyqt5.py
[2704] LOADER: Running launcher.py
```

and your logs doesn't show those lines.

This seems to be related to way PyInstaller bundles or loads the application and the fact that your environment does something different that fails with that setup.

I'm lost here. The last thing I can think about is trying again with a different build that would use a more recent version of PyInstaller. So let me do that. I'll download the latest version of PyInstaller, build another test version and I'll send it to you if you wanna try.

**Comment by ANormalPers0n** [comment]
Hey im down for anything if it gets my game working.

**Comment by ANormalPers0n** [comment]
Thanks for the help btw, I do appreciate you trying to get it working for me

**Comment by remyroy** [comment]
Here is the new test build: https://www.dropbox.com/s/if71kbq5gph4vub/cddagl_portable_v1.4.1.testcrash%2Beaf922f.zip?dl=1

**Comment by ANormalPers0n** [comment]
Same issues as before. Sucks but seems like im stuck not using the launcher. Any more ideas that I could try?

**Comment by remyroy** [comment]
Since it seems related to your environment, you could always try reinstalling Windows from a clean state, install the vc runtime from https://aka.ms/vs/16/release/vc_redist.x86.exe and try the launcher from that point.

**Comment by ANormalPers0n** [comment]
Not sure I want to reinstall windows just for this. I think Ill just download the experimentals and wait for the full release of the next version. Hope you have more luck with anyone else who needs help, keep up the work on the launcher.
