### ISSUE TITLE
FOF_NO_UI should be set to prevent popup

### ISSUE THREAD

**Issue by ImportTaste** [remyroy/CDDA-Game-Launcher#376]
FOF_NO_UI prevents the Windows File Operations window from popping up. Often I will click the upgrade button and just let it do its thing, but the file operation window will come up while I'm mid typing and it might get paused or cancelled depending on what keys I was hitting at the time.

(I'd submit a PR myself but I have been having problems getting it to compile correctly after following the building instructions, the launcher.exe it creates always complains throws an error.)

**Comment by remyroy** [comment]
That seems a good reason to prevents the window from popping up. I wonder if it will still popup UI if retries or permanent file deletion are needed. This might need some testing. Thanks for letting us know about this.

**Comment by remyroy** [comment]
I believe FOF_SILENT is more interesting here than FOF_NO_UI as it removes the popup dialog but it keeps the error UI if a file is locked by another application for instance.

**Comment by remyroy** [comment]
This has been added with 93674b0ab30e55d6e300ad1a7e10b80ba64431fa . It will be part of the next release.
