### ISSUE TITLE
CDDA Game Launcher files cannot be inside Game directory! (1.42)

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#379]
Something is not right with game and launcher paths checking in launcher version 1.42 - launcher tells "Unknown version - Reason: CDDA Game Launcher files cannot be inside Game directory!" while launcher and game are in different folders ("C:\Games\cdda" and "C:\Games\cdda-launcher").

![image](https://user-images.githubusercontent.com/16213433/64262683-21e02780-cf37-11e9-9cf6-4983862ce73e.png)

**Comment by ZhilkinSerg** [comment]
Removing `cdda` prefix from launcher folder names resolves the issue. I guess there is some kind of regex used for path matching?

**Comment by remyroy** [comment]
This is a duplicate of #377 . There will be a quick bug fix release soon with it.

**Comment by remyroy** [comment]
This has been fixed and the fix is part of the latest 1.4.3 release.

**Comment by ZhilkinSerg** [comment]
Thanks!
