### ISSUE TITLE
Launcher returned -1 after downloading 0.9

### ISSUE THREAD

**Issue by Zireael07** [remyroy/CDDA-Game-Launcher#38]
Auto-update failed (something about not being able to access?), so  I downloaded 0.9 manually.

Can't start, get an error about "launcher returned -1". 

0.8.5. works fine.

**Comment by remyroy** [comment]
Can you check the file `%LOCALAPPDATA%\CDDA Game Launcher\app.log`? Check out if there is some error near the end of it or send me the whole file.

**Comment by Zireael07** [comment]
Nope, nothing in the log (I deleted the file, ran 0.9., no file. Ran 0.8.5 and the file was created with 0.8.5 being the only line)

**Comment by remyroy** [comment]
Can this try [this launcher](https://www.dropbox.com/s/msr0l8dticbxqgm/launcher.exe?dl=1)? It is the exact same one as 0.9 except that it does not hide its stdout and stderr which shows as a command line window.

If the command line window closes too fast for you to see the error message, first start a command line window and run it from there.

I would need the error message from the output.

**Comment by Zireael07** [comment]
'No translation file found for domain cddagl'
.. and some line numbers I couldn't catch as it closed

The path is fairly long so command line sucks :(

**Comment by remyroy** [comment]
Hmm, that is weird. The translation files should be included with the launcher.

When the launcher start, it should create a directory named `_MEI` followed by a bunch of numbers. That directory should be in `%TEMP%`. It should also contain a `cddagl\locale` with a few directories and files like `cddagl\locale\en\LC_MESSAGES\cddagl.mo` for English for instance. Can you see those files?

**Comment by remyroy** [comment]
In any case, I'm currently adding some code to check for translation files missing and make sure the launcher can still run even if they are.

**Comment by remyroy** [comment]
This should be partially fixed with 0bde2af034fa91f7689dbcc9a7b9bf99c7ab489d. There might be like an antivirus or another process that prevent the localization files from being read or extracted in that `_MEI` directory for some reason.

**Comment by Zireael07** [comment]
There are a few _MEI folders in my %TEMP%, but the most recent one is three days old. It does contain cddagl, but not locale.

I tried running the provided launcher a few more times, but no dice.

.. I guess my %TEMP% needs a good clean, by the way. First thing to do when I have access to my own computer tomorrow :P

**Comment by remyroy** [comment]
Try the new 0.9.1 version and see if it works better for you. It includes the fix in 0bde2af034fa91f7689dbcc9a7b9bf99c7ab489d.

**Comment by remyroy** [comment]
This should be fixed with the recent commits and the resolution of #40 .
