### ISSUE TITLE
can't get the launcher to open with no error message

### ISSUE THREAD

**Issue by SirEdvardo** [remyroy/CDDA-Game-Launcher#380]
I've been trying to get the launcher to work for a while now on 1.4.3 and 1.4.2, I've ran the launcher exe normally and as admin, uninstalled reinstalled and installed over to no avail (it also won't let me change the download path), I think I've deleted the config in %localappdata%, I think. on window's 10 home 64 bit, and CDDA works when I launch it with no issues on 0,d, I've installed and repaired Redistributable a few times. don't know what else to try, all the exe does when launched is load for a second then stop with nothing happening after

**Comment by remyroy** [comment]
Try [this version](https://www.dropbox.com/s/if71kbq5gph4vub/cddagl_portable_v1.4.1.testcrash%2Beaf922f.zip?dl=0). Launch with the launcher.bat file. It will create a file named logs.txt in the same directory. Open that file, copy the content on a new gist on https://gist.github.com/ and share the link to that gist. It might include information that will help us figure out what is wrong.

**Comment by SirEdvardo** [comment]
Here you go
https://gist.github.com/SirEdvardo/aec00446e89d1da06adb72955c743cc4

**Comment by remyroy** [comment]
Your launcher seems to be in a weird path with special characters. 

Try again to start it in c:\cdda for instance.

**Comment by SirEdvardo** [comment]
ok, that worked, don't know why I didn't bother trying that x.x
thanks for the help

**Comment by remyroy** [comment]
You could also use the installer which would install it in a correct path by default.
