### ISSUE TITLE
launcher removes arcana every update

### ISSUE THREAD

**Issue by adamkad1** [remyroy/CDDA-Game-Launcher#381]
every time i update the game, arcana get removed from my mod folder for some reason

**Comment by remyroy** [comment]
I just tested upgrading from 9588 to 9601 wtih Arcana and it stayed there after the update process.

Are you using special permissions on that arcana mod folder like read-only, encrypted or something else? Are you using an AV product that could block this copy or move operation?

Arcana is also a bad mod that breaks all the time from what I've heard. I would use the new Magiclysm mod instead if I were you.

**Comment by adamkad1** [comment]
Not that i know of, this is the only mod this happens to, and i know from discord that the owner is very active and works hard to fix the mod, is currently working on making it work with magiclysm system, so yeah, its not going anywhere

**Comment by adamkad1** [comment]
anyway, i changed its name and it seems to be fine now?

**Comment by chaosvolt** [comment]
> Arcana is also a bad mod that breaks all the time from what I've heard. I would use the new Magiclysm mod instead if I were you.

My number one most common bug report is "you fixed this bug over a month ago, but it's still showing up for launcher user"

Kindly don't shit on someone else's work when your own work is actively the cause of the most commonly-reported bug.
