### ISSUE TITLE
Launcher flagged as malware

### ISSUE THREAD

**Issue by W4rd3nn** [remyroy/CDDA-Game-Launcher#383]
![image](https://user-images.githubusercontent.com/12723348/64931311-c733af00-d805-11e9-8b5c-7f3f51a3b0e8.png)

This occurred while updating the game itself, not the launcher. Caused nearly every anti-virus program on my computer to screech in agony. This has NEVER happened to me before. Uninstalling the launcher just in case.

**Comment by remyroy** [comment]
Poor antivirus products are known to detect the launcher as a threat and block its execution. A simple workaround is to add the launcher binary in your antivirus whitelist or select the action to trust this binary when detected.

If you are paranoid, you can always inspect the source code yourself and build the launcher from the source code. You are still likely to get false positives. There is very little productive efforts we can do as software developers with these. You can find our building guide on https://github.com/remyroy/CDDA-Game-Launcher/blob/c4664b6cc6e73823ed82f1efc48c3e6e77fdb1e4/BUILDING.md .

**Comment by W4rd3nn** [comment]
Like I said, this is the first time this has ever happened. I've had the launcher for nearly two years now, and this is the first time any of my antiviruses flagged it. What worries me is EVERY antivirus on my system flagged it. Avast, Malwarebytes Premium, and Windows Defender. But what's weird is the launcher itself hasn't updated recently. I've checked the files myself and none of them have a modified date past the day I installed the newest update. I'm curious if the newest experimentals may be compromised somehow. Either way, I'm going to just wait for a codebase update to see if my antiviruses flag it again. As it stands, I have no way of whitelisting the program as the launcher gets deleted the moment I download it.

**Comment by LastRagnarokkr** [comment]
A thought occured to me, could it be that the problem is not at the source, but at the downloader? As in, could it be injected with malware during downloading by a man in the middle attack?

**Comment by remyroy** [comment]
Here is the results from virustotal:

https://www.virustotal.com/gui/url/9af3a7430f70133679df021ae4eba5b2ec99a1bcec6a1c3a94a4e94339a58627/detection

0 out of 73 different antivirus products found a threat.

Here is the other results for the installer:

https://www.virustotal.com/gui/url/d4023c1bd5e1b6ea03b4e064880130084cb9b7f6d33c36163178b4aea26158f4/detection

again, 0 out of 73 different antivirus products found a threat.

I would be very surprised if there was a something or someone who was inserting a malware after it was uploaded on github. That would mean that github is compromised and a great amount of other software are affected as well.

**Comment by W4rd3nn** [comment]
UPDATE:
Guess my anti-malware was just being jumpy? I tried redownloading it today and my computer didn't screech in agony at me. Oh well, even if there is a virus, it's worth it.

Closing this.
