### ISSUE TITLE
Nimian Manufacture value OOR error, guns

### ISSUE THREAD

**Issue by BarBreaker** [remyroy/CDDA-Game-Launcher#386]
**Describe the bug**
Latest build as of sep. 19/19 gives value out-of-range errors on nimian manufactures civilian weapons with durability 20, the version of the mod is included with the launcher. I am unable to reproduce the error's specific behaviour with the mod from other sources

**To Reproduce**
1. Go to 'mods'
2. Click on 'Nimian Manufacture's guns'
3. Install mod and run game

**Expected behavior**
Mod would add content and run as normal, with mod contents enabled.

**Behaviour**
Mod throws error then returns me to main menu after character generation.
**Screenshots**
(Unable to post screencaps, currently posting on mobile, error occurrs in the nm_civvie_guns JSON on every line containing durability 20)

Desktop
 - OS: Win 10
 - Game version: latest of 9000 series builds

**Additional context**
The only fix I can think of is aggressively find-and-replacing all instances of the 20 durability with a durability of 8, which is the highest I've seen in any of the core content or other mods.

**Comment by remyroy** [comment]
Have you tried contacting the mod author? Maybe we can have someone *fix* or maintain this mod so that it can work with the latest version of the game. The other alternative is to remove the mod from the repository or specify at which build it will start to break.

**Comment by BarBreaker** [comment]
I haven't done any extensive testing, I'll get back to you on that. I
haven't contacted Nimian yet, I think he has a github repo, I'll open an
issue there. The fix is simple enough at present, so I'll probably just
pass that on to him, It makes me wonder why my previous version of the mod
( not the game, it was a self install) threw the same error, without
noticeable impact.

I'll poke around.

**Comment by BarBreaker** [comment]
It appears Malkeus made a fix for the lates version so far, so I'd probably replace the existing mod with this: https://github.com/Malkeus/M_Nimian_Manufacture

**Comment by remyroy** [comment]
The new fixed version was added in dbf65f46c7998fa375a5ce236eaa2ec8d7d3e1f4 . It will be part of the next version.
