### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by B0xy1** [remyroy/CDDA-Game-Launcher#388]
* Name: [No zombies]
* Url: [https://github.com/iamlcarus/nozombies]
* Author: [Icarus]
* Homepage: [https://discourse.cataclysmdda.org/t/i-made-a-mod-to-remove-zombies-specifically/17921]
* Mod not found in version: 1.4.3

**Comment by B0xy1** [comment]
Thanks for reading my message. I am a huge cdda fan and i hope this mode
lets me experience  an apocalyppse with 10 times more monsters  and aliens
but no zombies thank you for your work on cdda launcher.

**Comment by remyroy** [comment]
It was added with ec15a99e5615dfad82e8c4dbf65f207608bef1ed . It will be part of the next release.
