### ISSUE TITLE
CDDA launcher detects as Trojan:Win32/Zpevdo.B by Windows Defender

### ISSUE THREAD

**Issue by purgatorios** [remyroy/CDDA-Game-Launcher#389]
**Describe the bug**
Something in the launcher is tripping Windows Defender.

**To Reproduce**
Download .zip or .exe on MS Windows 10 device with current security updates as of 9/22/2019.
Install/unzip.
Examine Defender log if no popups occur.

**Expected behavior**
No virus warnings.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I never uninstalled the launcher, so somehow Windows started detecting it today, I played fine last night.

**Comment by remyroy** [comment]
Poor antivirus products are known to detect the launcher as a threat and block its execution. A simple workaround is to add the launcher binary in your antivirus whitelist or select the action to trust this binary when detected.

If you are paranoid, you can always inspect the source code yourself and build the launcher from the source code. You are still likely to get false positives. There is little productive efforts we can do as software developers with these. We have a [nice building guide](https://github.com/remyroy/CDDA-Game-Launcher/blob/master/BUILDING.md) for those who want to build the launcher from the source code.

**Comment by purgatorios** [comment]
Makes sense, thanks for the info!  Will disregard these warnings.
