### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by Augenhollen** [remyroy/CDDA-Game-Launcher#392]
* Description: [Tried to update the game]
* Version: 1.4.3
* OS: Windows-8.1-6.3.9600-SP0 (64-bit)
* Type: `<class 'PermissionError'>`
* Value: [Errno 13] Permission denied
* Traceback:
```
  File "cddagl\ui\views\main.py", line 3498, in step

```

**Comment by remyroy** [comment]
The error happened while trying to read the game main binary file. So it seems like the launcher could not read the game main binary file. Is it possible your game files are read protected, encrypted or somehow unavailable to the launcher process? It might be interesting to try again and put the game directory somewhere safe like on your desktop. The default permissions for a new desktop directory should give all the good permissions for the launcher to work.

**Comment by Augenhollen** [comment]
Noticed something interesting, game freezes and crashes during the copying of the CO.AG soundpack, manual re-installation fixed the problem. Don't know if this is useful information but here you go.

**Comment by Augenhollen** [comment]
Should i close the issue now?

**Comment by remyroy** [comment]
If your issue is solved, you should close this.
