### ISSUE TITLE
alcohol shouldn't spawn in prison fridges

### ISSUE THREAD

**Issue by DamonStamper** [remyroy/CDDA-Game-Launcher#393]
It's odd that alcohol spawns in prison fridges. I don't know if there is some kind of area metadata that containers can be assigned that changes their spawn list (or adds restrictions to the spawn list) but that might be a fix.

**Comment by Zireael07** [comment]
Request for main game, not the launcher.

**Comment by remyroy** [comment]
You should report on https://github.com/CleverRaven/Cataclysm-DDA/issues . This github is for the launcher only.
