### ISSUE TITLE
Fermenting times

### ISSUE THREAD

**Issue by Hextroyer413** [remyroy/CDDA-Game-Launcher#394]
When updated my game the fermenting times for recipes showed a glitched description.
I used the most recent version of the launcher and updated from 9810 to 9856
![bug](https://user-images.githubusercontent.com/57329654/68091202-82b6ae00-fe5b-11e9-941e-1c3c17deba3d.png)

**Comment by Zireael07** [comment]
Report on the game's repo https://github.com/CleverRaven/Cataclysm-DDA, not the launcher repo.

**Comment by remyroy** [comment]
In addition, I suggest you restore your game to a previous version to keep playing while this issue is being resolved.

**Comment by remyroy** [comment]
Closing since this is not related to the launcher.
