### ISSUE TITLE
user-default-mods.json doesn't get copied when updating.

### ISSUE THREAD

**Issue by Malkeus** [remyroy/CDDA-Game-Launcher#4]
All my mods moved to the new version, but I had to copy over my user-default-mods.json myself. Aside from that, it worked flawlessly. Really nice work remyroy :)

**Comment by remyroy** [comment]
What is in that file? Should it be automatically copied or should there be an option for people to choose if they want to copy it or not?

**Comment by Malkeus** [comment]
On world creation, after you select the mods you'd like to have in the new world, you can press 's' to save the currently selected mods as the default, and they will be automatically selected the next time you create a world. It's a great time saver. I personally always want it copied, since it only gets created when I choose to save the current list as default. It's not a file that will be overwritten as it's not included in the zip file.

**Comment by Malkeus** [comment]
hmm...you may want to set your permissions ;)

**Comment by remyroy** [comment]
I will include copying that file in the update process in the next release.

**Comment by Malkeus** [comment]
Thank you

**Comment by remyroy** [comment]
This was added in 869cf448163829175e0e662bd33818f5cfd4f31b and will be part of the next release.
