### ISSUE TITLE
Crash: Unhandled exception on startup

### ISSUE THREAD

**Issue by Cheet4h** [remyroy/CDDA-Game-Launcher#40]
Downloaded the new launcher version manually (Autoupdate failed) and ran it. On startup I see the launcher briefly, then it crashes and I'm notified of the unhandled exception.

OS is Windows 10 Professional x64

I tried to run the launcher from D:\Dropbox\CDDA\ and C:\DDA\ - same result.

* Version: 0.9.1
* Type: `<class 'ValueError'>`
* Value: Unsupported locale 'None'
* Traceback:
```
  File "cddagl\ui.py", line 890, in timeout
  File "site-packages\arrow\arrow.py", line 602, in humanize
  File "site-packages\arrow\locales.py", line 21, in get_locale

```

**Comment by remyroy** [comment]
Can you try [this launcher](https://www.dropbox.com/s/dhwuinov62zbvia/launcher2.exe?dl=1)? It includes a fix I think will solve your problem. If it does, I'll release a new version based on it.

**Comment by Cheet4h** [comment]
gives the same error :/

**Comment by remyroy** [comment]
I've just released 0.9.2. It should fix this problem. If not, please copy the whole error message here.

**Comment by Cheet4h** [comment]
```
CDDA Game Launcher version: 0.9.2
Type: <class 'ValueError'>
Value: Unsupported locale 'None'
Traceback:
File "cddagl\ui.py", line 890, in timeout

File "site-packages\arrow\arrow.py", line 602, in humanize
File "site-packages\arrow\locales.py", line 21, in get_locale
```

**Comment by remyroy** [comment]
Can you check the file `%LOCALAPPDATA%\CDDA Game Launcher\app.log` and send me the whole thing or the bottom part it?

**Comment by Cheet4h** [comment]
That file does not exist, the folder is completely empty.

**Comment by remyroy** [comment]
I've just release 0.9.3 which should contain a fix for this if you wanna try it.

**Comment by GaelanDarkwater** [comment]
Greetings and thank you for an awsome lil utility, however I suffer the same issue as Cheet4h.


CDDA Game Launcher version: 0.9.3
Type: <class 'ValueError'>
Value: Unsupported locale 'None'
Traceback:
File "cddagl\ui.py", line 890, in timeout

File "site-packages\arrow\arrow.py", line 602, in humanize
File "site-packages\arrow\locales.py", line 21, in get_locale****

**Comment by remyroy** [comment]
Let me check once more and see how I can solve this.

**Comment by remyroy** [comment]
Can you try [this new launcher](https://www.dropbox.com/s/tf3yt11hzoobw6q/cdda-launcher.exe?dl=1)? Hopefully, it should be the end of this.

**Comment by remyroy** [comment]
I think I found another problem. Try [this new one](https://www.dropbox.com/s/1js2tq8kqzyh35x/cdda-launcher2.exe?dl=1) and let me know.

We'll get there :+1:

**Comment by Cheet4h** [comment]
The latest version doesn't throw an error on startup. Seems fixed.

**Comment by remyroy** [comment]
Thanks for take some time to test it. I'll create a new release soon.

This should be fixed with the last few commits.
