### ISSUE TITLE
"Available Builds" stops at 9999, won't show any newer builds

### ISSUE THREAD

**Issue by ArcanErasmus** [remyroy/CDDA-Game-Launcher#400]
**Describe the bug**
Launcher won't allow updating to builds higher than 9999.

**To Reproduce**
1. Open the launcher
2. Click on the "Available builds" dropdown

**Expected behavior**
You should see all builds, but instead it stops at 9999.

**Screenshots**
![image](https://user-images.githubusercontent.com/8963206/70844406-b0a1f180-1e0e-11ea-8acd-6ffe8e0bbf1a.png)

![image](https://user-images.githubusercontent.com/8963206/70844410-b992c300-1e0e-11ea-8d61-a91d57e34bc1.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1.4.3

**Additional context**
Ten thousand builds! Arbitrary milestone, but CDDA sure has come a long way.

**Comment by remyroy** [comment]
They builds starting with 1 are at the bottom but the sorting is wrong. I'll see if I can fix this issue quickly.

**Comment by remyroy** [comment]
This was fixed with 482b58c91aaba8f9debf5304765a66db14ded01b . It will be part of the next release.
