### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by pawnishoovy** [remyroy/CDDA-Game-Launcher#405]
- Name: [More Survivor Stuff]
- Url: [https://github.com/pawnishoovy/More-Survivor-Stuff]
- Author: [pawnishoovy]
- Homepage: [https://discourse.cataclysmdda.org/t/more-survivor-stuff-mainly-heavy-stuff/22254]
- Mod not found in version: 1.4.4

**Comment by remyroy** [comment]
Thanks for letting us know about this mod. It will be verified and added shorthly.
