### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by MrJet2020** [remyroy/CDDA-Game-Launcher#408]
Name: XEAS
Url: https://github.com/MrJet2020/XEAS
Author: MrJet2020
Homepage: https://discourse.cataclysmdda.org/t/mod-xeas-xeno-adapted-stuff/22407

Add new hard crafted Xeno-Adapted Stuff. Close to hi-tech content. Includ armor set (slightly better protection than survival armor, less encumbrance), new knife (better butchering, impression damage) and vortex bag (120 L, tiny size, no encumbrance). Craft recipes in vanilla lab journal. Late game content!

**Comment by remyroy** [comment]
Thanks for the information. The mod will be added shortly and will be included in the next version.
