### ISSUE TITLE
"Unknown version - Game directory doesn't exist, Game is not installed here."

### ISSUE THREAD

**Issue by Tynner23** [remyroy/CDDA-Game-Launcher#412]
CDDA Game Launcher version: 1.4.4
OS: Windows-10-10.0.18362-SP0 (64-bit)
Type: <class 'TypeError'>
Value: expected str, bytes or os.PathLike object, not NoneType
Traceback:
File "cddagl\ui\views\main.py", line 1403, in update_game

File "cddagl\ui\views\backups.py", line 763, in prune_auto_backups
File "ntpath.py", line 76, in join

This Is The Error I Received, I Get This Message Whenever I Try To Install Version 1.4.4, And Also When I Try To Install The Game On Version 1.3.22, I've Tried Both Stable, Experimental, And Both
64-bit And 32-bit, I'm New To CDDA, So I Apologize In Advance If It is Simply My Own Stupidity Causing The Problem

**Comment by remyroy** [comment]
Try to uncheck the option to backup the saves before updating. We'll try to fix this issue in the next version.

**Comment by remyroy** [comment]
This is likely to be fixed with 88f045976f0ed395fbb4237b3249dd67030631eb . It should be part of the next version.

**Comment by Tynner23** [comment]
Working Now, Thanks

**Comment by remyroy** [comment]
You can activate the option again after the game is installed.

**Comment by Tynner23** [comment]
Ahh, I Understand What That Meant Now, Since There Was No Game Directory It Was Unable To Create The Backups XD
