### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by LlubNek** [remyroy/CDDA-Game-Launcher#415]
* Name: Medieval Mod Reborn
* Url: https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/master.zip
* Author: chaosvolt
* Homepage: https://github.com/chaosvolt/cdda_medieval_mod_reborn
* Mod not found in version: 1.4.4

Replaces obsolete built-in mod Medieval and Historic Classes and Shields

**Comment by remyroy** [comment]
This mod is already in the base game. It is not obsolete.
