### ISSUE TITLE
Preserve `fonts` folder when updating game

### ISSUE THREAD

**Issue by damien** [remyroy/CDDA-Game-Launcher#424]
**Is your feature request related to a problem? Please describe.**

I have fonts I use specifically for playing CDDA that are not installed on my system, but instead placed in the `fonts` folder in the root of the game directory. CDDA reads from this folder for additional, non-system fonts it can load via a user's `config/fonts.json` configuration file.

When updating the game via the launcher, the `fonts` directory is not preserved. To keep my fonts, I need to manually move font files from the `previous_version/fonts` directory into the new version's `fonts` directory.

**Describe the solution you'd like**

Preserve the `fonts` directory in a manner similar to how the `config` directory is preserved between versions.

**Describe alternatives you've considered**

* Managing this manually. I currently do, and it's a bit of a pain.
* Installing fonts. Not ideal, as I don't really need fonts I use for CDDA elsewhere. Many fonts used for CDDA are also not useful when fonts are scaled up in size past 12 or 14px (whiterbt, terminus, etc)

**Additional context**

I'm planning on making a PR to address this as I foray into contributing to this project. Let me know if there's anything I should keep in mind as I draft more PRs for review. :)

**Comment by remyroy** [comment]
I did not know you could have game specific fonts that are not system wide fonts. Go ahead with the PR if you want. It should take too much effort as we are already coping various other folders and files already and you can see how it's currently done.
