### ISSUE TITLE
Missing translation cause crash on startup

### ISSUE THREAD

**Issue by jiornojiovanni** [remyroy/CDDA-Game-Launcher#431]
**Describe the bug**
Crash on start caused by missing translation in locale it.dat file.

**To Reproduce**
1. Open the launcher.
2. See error.

**Expected behavior**
No crash.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/31773561/78336793-42856400-7590-11ea-883a-4ec66f6cec88.png)

**Desktop**
 - OS: Windows
 - Version 10

**Additional context**
I can help translate the missing text in italian, but I'm unable to open the locale .dat file.

**Comment by remyroy** [comment]
This is part of the third party library called [Arrow](https://arrow.readthedocs.io/). If you want to help them with translation, you should get in touch with them.

In the meantime, we should be able to fix this issue by catching this exception or by trying with another language if one is not supported.

**Comment by remyroy** [comment]
Adding a minute granularity to the humazine function seems to solve this issue. It is part of 876d12b92b746b2b9ec21e801954526c37683ca5 which should solve this issue. It will be part of the next release.

**Comment by remyroy** [comment]
In most case, we still want an auto granularity, reopening to see what we can do instead.

**Comment by remyroy** [comment]
We now have a safe_humazine function 3b81e6d14d9a054fe74f85f187ef6279b4973edc that shouldn't fail even if a locale is missing some translation in Arrow. We'll be using that in the next release and this issue should be fixed now.

**Comment by jiornojiovanni** [comment]
Nice
