### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by oivil** [remyroy/CDDA-Game-Launcher#437]
* Description: [Enter what you did and what happened]
* Version: 1.4.7
* OS: Windows-10-10.0.18362-SP0 (64-bit)
* Type: `<class 'ValueError'>`
* Value: Humanization of the 'week' granularity is not currently translated in the 'it' locale. Please consider making a contribution to this locale.
* Traceback:
```
  File "cddagl\ui\views\main.py", line 2821, in lb_http_finished
  File "lib\site-packages\arrow\arrow.py", line 1053, in humanize

```

**Comment by remyroy** [comment]
This is fixed in 1.4.8. Just update your game launcher and you'll be fine.
