### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by owlpelletsareyummy** [remyroy/CDDA-Game-Launcher#441]
**Describe the bug**
launcher crashes before CDDA opens.

**To Reproduce**
1. Open Launcher
2.click "launch"

**Expected behavior**
CDDA opens.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Screenshots**
shows error message:
![Screenshot (6)](https://user-images.githubusercontent.com/63534699/79063479-73c7f900-7c4e-11ea-8d51-deab44e17079.png)

**Additional context**
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-162-gcde5bb0
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x625896[cataclysm-tiles.exe+0x225896]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x625896),
    (libbacktrace: 0x625896    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x60a8ff[cataclysm-tiles.exe+0x20a8ff]), 
    (libbacktrace: log_crash+0x4af@0x60a8ff),
    (libbacktrace: 0x60a8ff    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x60b5d2[cataclysm-tiles.exe+0x20b5d2]), 
    (libbacktrace: signal_handler+0x32@0x60b5d2),
    (libbacktrace: 0x60b5d2    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x21b@0x7ffeb1bcae7b[msvcrt.dll+0x2ae7b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ffeb1bcf28b[msvcrt.dll+0x2f28b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x62a93f[cataclysm-tiles.exe+0x22a93f]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xdaf@0x62a93f),
    (libbacktrace: 0x62a93f    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: IMG_LoadWEBP_RW+0x11ca44@0x1272ed4[cataclysm-tiles.exe+0xe72ed4]), 
    (libbacktrace: Z12realDebugmsgIJPKcS1_EEvS1_S1_S1_S1_DpOT_+0x2a4@0x1272ed4),
    (libbacktrace: 0x1272ed4    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x52f0e4[cataclysm-tiles.exe+0x12f0e4]), 
    (libbacktrace: Z14read_from_fileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRSiEE+0x294@0x52f0e4),
    (libbacktrace: 0x52f0e4    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x52f2c1[cataclysm-tiles.exe+0x12f2c1]), 
    (libbacktrace: Z28read_from_file_optional_jsonRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvR6JsonInEE+0x61@0x52f2c1),
    (libbacktrace: 0x52f2c1    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xc73226[cataclysm-tiles.exe+0x873226]), 
    (libbacktrace: ZN15options_manager4loadEv+0x56@0xc73226),
    (libbacktrace: 0xc73226    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0xe58694[cataclysm-tiles.exe+0xa58694]), 
    (libbacktrace: ZN10catacurses14init_interfaceEv+0x1a4@0xe58694),
    (libbacktrace: 0xe58694    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: IMG_LoadWEBP_RW+0x66ceed@0x17c337d[cataclysm-tiles.exe+0x13c337d]), 
    (libbacktrace: main+0xf1d@0x17c337d),
    (libbacktrace: 0x17c337d    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #13
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #14
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffeb22a7bd4[KERNEL32.DLL+0x17bd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #15
    (dbghelp: RtlUserThreadStart+0x21@0x7ffeb24cced1[ntdll.dll+0x6ced1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by remyroy** [comment]
This seems to be a crash with the game itself. You should refer to the game developpers instead. See https://github.com/remyroy/CDDA-Game-Launcher#i-found-an-issue-with-the-game-itself-or-i-would-like-to-make-a-suggestion-for-the-game-itself-what-should-i-do
