### ISSUE TITLE
Fatal error: Failed to execute script launcher

### ISSUE THREAD

**Issue by Owl0111** [remyroy/CDDA-Game-Launcher#445]
Description 
I am attempting to run the CDDA launcher but it simply returns the error "Failed to execute script launcher"

 - OS: Windows 10 pro
 - Version	10.0.18363 Build 18363

![Capture](https://user-images.githubusercontent.com/51752116/80202276-fe432c00-8642-11ea-9173-82572ee5b4af.PNG)
Interestingly enough it seems to work on a different system.
If it's any help I recently switched from linux to windows.

**Comment by remyroy** [comment]
Did you install the [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/vc_redist.x86.exe) as mentionned in the [download/release section](https://github.com/remyroy/CDDA-Game-Launcher/releases)?

**Comment by Owl0111** [comment]
I tried doing that. Also tried to delete a config.dbs as it appeared to fix it in a similar error thread but it did not exist in the cdda launcher folder.

**Comment by remyroy** [comment]
I've just made a debug release to get more information regarding your issue. You can download it here: https://www.dropbox.com/s/knwe4sc9r0yct65/cddagl_portable_v1.4.8.debug.py37.zip?dl=1

Extract the archive, start the launcher using the `launcher-debug.bat` file. It should create a `debug.txt` file with some logs in the same directory. Send me back that `debug.txt` file and that should give me more information regarding your issue.

**Comment by Owl0111** [comment]
Eh.. I just decided to reset windows since I didn't have anything important saved and that somehpw seemed to fix whatever the problem was. Thank you for your help <3
