### ISSUE TITLE
launcher deletes none default tile sets

### ISSUE THREAD

**Issue by shpookys** [remyroy/CDDA-Game-Launcher#446]
every time you update the game the settings and saves stay but it clears out my tile-sets that ive added is there a option to have it not do this? and if not could it be added?

**Comment by remyroy** [comment]
Where is your tilesets located? It should be kept if it's in `gfx` and if it has a unique ident value.

**Comment by shpookys** [comment]
yes it is in the gfx folder and it keeps removing it when i update for some reason......
like i just started having this issue?
![image](https://user-images.githubusercontent.com/16250856/80335653-cdf9ba00-8809-11ea-8294-d4a2db16935f.png)

**Comment by shpookys** [comment]
this was not a issue i had a while back......... ima try just reinstalling the launcher and see what happens

**Comment by shpookys** [comment]
i reinstalled the launcher and forced updated the game and it still threw out undead people :/ 
![image](https://user-images.githubusercontent.com/16250856/80335919-9a6b5f80-880a-11ea-8cee-ffcf50e98979.png)

**Comment by shpookys** [comment]
oh nvm i just installed it incorrectly its all good i was supposed to take out a folder that was in that what and put it in there and not the whole thing (i no longer have the issue now)
![image](https://user-images.githubusercontent.com/16250856/80336584-858fcb80-880c-11ea-96fb-4e66f7f4c9fc.png)
![image](https://user-images.githubusercontent.com/16250856/80336611-980a0500-880c-11ea-84e0-b9bd6153be99.png)
its weird tho the texture pack worked normally even when i installed it incorrectly its just that it would remove it whenever i updated
