### ISSUE TITLE
Naming convention for CDDA release assets

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#455]
I've had to change naming convention for CDDA release assets - add character `b` before build number. Thus what previously was:

https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-jenkins-b10674/cataclysmdda-0.E-Windows_x64-Tiles-10674.zip

will become:

https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-jenkins-b10674/cataclysmdda-0.E-Windows_x64-Tiles-b10674.zip.

I will temporary return naming convention back, but it will eventually include `b` character in the future. Maybe you can change `target_regex` shown below to include optional `b` character for future releases?

https://github.com/remyroy/CDDA-Game-Launcher/blob/3b81e6d14d9a054fe74f85f187ef6279b4973edc/cddagl/ui/views/main.py#L2780-L2784

**Comment by remyroy** [comment]
Sure, we'll add the optional b.

**Comment by remyroy** [comment]
Included in 8bcf25c5ae9eed84744ab80bf402096d71348984 . Thanks for the heads up. When should we expect this change to land so we can plan for a release ahead of time?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Included in [8bcf25c](https://github.com/remyroy/CDDA-Game-Launcher/commit/8bcf25c5ae9eed84744ab80bf402096d71348984) . Thanks for the heads up. When should we expect this change to land so we can plan for a release ahead of time?

There is no rush in making new launcher release - instead I can switch over to new naming convention after I see new launcher build (whenever it will be ready).

Note that `b` change is already in now, but just temporary (while I am testing something). I will change it back today after finishing my tests, so downloads will be available again on current (and older) launcher builds.

**Comment by remyroy** [comment]
1.4.9 includes this change so it should see all the builds whether or not they have the additionnal b in their name.

**Comment by ZhilkinSerg** [comment]
It took me a couple of days longer, but I am now ready to return back previous naming convention. On the other hand, you've already did a release, so it could be unnecessary.

Do you have any objections if I am not switching back? Only concern I see that people should use launcher version 1.4.9 and above to download newer CDDA versions.

**Comment by remyroy** [comment]
It's up to you. I'm guessing some players won't like being required to update. I don't have a strong opinion about it either way.

**Comment by Dansiman** [comment]
I wouldn't mind updating my launcher, but I'm unable to do so until at least one of the newer versions of it gets successfully reported as a false positive to MalwareBytes. I'm unfortunately unable to do so myself because my PC is a loaner from my employer (for WFH use) and is running a cloud-managed MB installation - so even though I have local admin rights on the machine, I have no way to add an exception, nor to collect the necessary logs to submit a false positive to MalwareBytes. ☹️
