### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by btonasse** [remyroy/CDDA-Game-Launcher#456]
* Description: [Enter what you did and what happened]
* Version: 1.3.19
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by remyroy** [comment]
You should update to a newer version of the launcher. It should solve your issue. That version is more than a year old.
