### ISSUE TITLE
Launcher only updates to the build prior to the most recent

### ISSUE THREAD

**Issue by 3NC3PH4L0ND1V3** [remyroy/CDDA-Game-Launcher#457]
Launcher has issues recognizing the most recent build no matter how long i wait after a new release. It will only update to the build prior to the newest. For example: If the most recent build is 10685 it will only allow me to update to 10684. This happened to me over the last 4-5 update processes spanning over the last 2 weeks. I already redownloaded and installed the newest version of the launcher several times. It still happens everytime.

![Screenshot (4)](https://user-images.githubusercontent.com/63214239/82690431-7ad62400-9c5c-11ea-8617-4a3acaac7e40.png)

**Comment by remyroy** [comment]
The launcher gets the game releases on https://github.com/CleverRaven/Cataclysm-DDA/releases . It cannot get releases that are not there yet. Maybe the CI server is having issues with sending the releases on GitHub. @ZhilkinSerg Do you know something about this?

**Comment by ZhilkinSerg** [comment]
There is nothing to worry about - build 10685 is failed while creating tag and has no downloads.

It may be worth adding check for existing tag on Github after getting build number from CI - e.g. if https://ci.narc.ro/job/Cataclysm-Multijob/10685/ exists, but there is no https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10685 mark this build as failed for all platforms. Or alternatively check if build is marked as failed/successful  on CI (e.g. via https://ci.narc.ro/buildStatus/text?job=Cataclysm-Multijob&build=10685)
