### ISSUE TITLE
CDDA launcher.exe has been changed or removed.

### ISSUE THREAD

**Issue by FellsHollow** [remyroy/CDDA-Game-Launcher#458]
When I try to open up the launcher it shows an error saying that the item 'launcher.exe' that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly.

Do you want to delete this shortcut?
**To Reproduce**

1. Go to open the shortcut from either taskbar or desktop on Win 10.
2. Error shows up.'
3. Confirm delete.
4. Reinstall from GitHub the most recent release.
5. Behaviour repeats.

**Expected behavior**
I've never had this issue before when opening CDDA's launcher. It usually just opens up, updates, and that's that.

**Screenshots**
![image](https://user-images.githubusercontent.com/64809825/82737140-49109c00-9cf4-11ea-8dc6-f9447aed8571.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Nothing to add.

**Comment by remyroy** [comment]
I suspect you either uninstalled the launcher or your AV product removed it. See this [FAQ question](https://github.com/remyroy/CDDA-Game-Launcher#my-antivirus-product-detected-the-launcher-as-a-threat-what-can-i-do) about it.

**Comment by FellsHollow** [comment]
Thank you, it took some time, but I finally figured out how to do so.
