### ISSUE TITLE
Do not install the launcher to appdata. Ask the user.

### ISSUE THREAD

**Issue by cthae** [remyroy/CDDA-Game-Launcher#460]
**Is your feature request related to a problem? Please describe.**
It's unable to update/uninstall/install itself on my machine. I don't think I have any special config, but the 1.10 installer fails.

Also, I wouldn't want it to put itself in the system volume. Memory on C is a lot more precious than elsewhere, so I keep games away from C:.

**Describe the solution you'd like**
Adequate installers always offer to choose the path. 
Please do it! And please use something like ./cataclysm by default.

**Comment by remyroy** [comment]
We can ask the user. Sure.

**Comment by remyroy** [comment]
I just reviewed our installer script and it seems that it does ask the user but only on first installation. If you try to reinstall it or update it while it is already installed, it will not prompt the user for the directory. It will assume that the user want to reinstall at the same location.

This seems like a reasonable choice overall. If you want to choose exactly where to install the launcher if it is already installed, you may do so by first uninstalling it.

Now there might be another issue at work here. You AV product might be blocking the installation. If that is the case, see [the FAQ question](https://github.com/remyroy/CDDA-Game-Launcher#my-antivirus-product-detected-the-launcher-as-a-threat-what-can-i-do) about it.

**Comment by cthae** [comment]
Not using an AV. I switched to the portable version that doesn't have the installer. That does the trick for me.

Uninstall didn't do anything for me, it didn't delete any files whether I run it directly or via the installer. Just pops up a generic "no access" error. Even if I run it with admin rights.

I solved it by using a portable version and manually deleting all old launcher files.

**Comment by remyroy** [comment]
I'm glad the portable version was useful for you.
