### ISSUE TITLE
Content inside items are deleted every time open certain spots

### ISSUE THREAD

**Issue by RedBloodCat** [remyroy/CDDA-Game-Launcher#465]
Everytime i open items from certain tiles they reset the inventory(For an example that the batteries in the UPS gets deleted) and i get the same error(picture below).  I have tried to save and load the game inn again but it still comes up.
 
![image](https://user-images.githubusercontent.com/49415411/83293685-5514c600-a1ec-11ea-9a34-b4de5aacc303.png)

"""
 DEBUG    : can't set ammo null in none as it is not an ammo
 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 579
"""

OS: Windows 10
Version: newest one out at this time from the launcher

**Comment by Zireael07** [comment]
This should be opened on the game's repo, not the launcher's repo.

**Comment by remyroy** [comment]
See [this FAQ question](https://github.com/remyroy/CDDA-Game-Launcher#i-found-an-issue-with-the-game-itself-or-i-would-like-to-make-a-suggestion-for-the-game-itself-what-should-i-do) about it.
