### ISSUE TITLE
Police officer starts without a gun

### ISSUE THREAD

**Issue by Brytenwalda** [remyroy/CDDA-Game-Launcher#467]
**Describe the bug**
Police officer starts without a gun, but two magazines of .45 ammo.

I used debug to spawn it and discovered another one - USP .45 cannot be stored in a holster. 

**To Reproduce**
1. Create a new character. 
2. Police officer doesn't have a gun.
3. Spawn it.
4. Try to put it in the holster. 

**Desktop (please complete the following information):**
Windows 10, latest version.

**Comment by remyroy** [comment]
See [the FAQ question](https://github.com/remyroy/CDDA-Game-Launcher#i-found-an-issue-with-the-game-itself-or-i-would-like-to-make-a-suggestion-for-the-game-itself-what-should-i-do) about finding an issue with the game itself.
