### ISSUE TITLE
no access to the last cdda stable version

### ISSUE THREAD

**Issue by fredaudy** [remyroy/CDDA-Game-Launcher#470]
**Describe the bug**
why the last stable version 0.E-2 Ellison-2 does not appear in the launcher?

**To Reproduce**
1. open launcher
2. refresh the main window

**Expected behavior**
to get the last 0.E-2 Ellison-2 version reachable from the launcher

**Screenshots**
![image](https://user-images.githubusercontent.com/8089058/85018337-50995880-b16d-11ea-9fbd-ab942812491e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1.4.10

**Comment by remyroy** [comment]
We will eventually add it but 0.E-2 is mostly a fix for Android players. 0.E-1 is fine on PC.

**Comment by fredaudy** [comment]
ok, thanks

**Comment by remyroy** [comment]
It is now part of 1.4.11
