### ISSUE TITLE
 Easy-CBM-Mods

### ISSUE THREAD

**Issue by Taichi22** [remyroy/CDDA-Game-Launcher#475]
* Name: Easy-CBM-Mods
* Url: https://github.com/Fris0uman/Easy-CBM-Mods
* Author: Fris0uman 
* Homepage: https://github.com/Fris0uman/Easy-CBM-Mods/commits?author=Fris0uman
* Mod not found in version: 1.4.11

**Comment by remyroy** [comment]
Added with 8a44064f829c40a4b0083b8a6a84fe7961cb2eff . It will be part of the next release.

**Comment by Fris0uman** [comment]
So it's not a big deal, and it's cool that it's added to the launcher. But I would have appreciated to be told about it, a quick @Fris0uman or something would have been nice.
