### ISSUE TITLE
Launcher offers to update to a build with (changelog latest+1) number

### ISSUE THREAD

**Issue by GGgatherer** [remyroy/CDDA-Game-Launcher#479]
**Describe the bug**
Changelog(in the launcher) shows latest build is 10903. Launcher shows 10904 as available build.

**To Reproduce**
Start the launcher. May be gone when newer build rolls out, though. 
Couldn't see anything looking like a log file in its folder so I backed it all up. If needed, can upload requested files in their current state.

**Expected behavior**
Either ability to see what we are updating for, or inability to update to a build without description.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7

**Comment by remyroy** [comment]
For some reason, the CI log API that we are using is not returning all the builds info. We are pulling from http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/api/xml?tree=builds[number,timestamp,building,result,changeSet[items[msg]],runs[result,fullDisplayName]]&xpath=//build&wrapper=builds and we are missing the latest one it seems. Maybe there was a change in the CI config or we need to modify that query somehow. We'll check it.

**Comment by remyroy** [comment]
Well, I think it's a little worst than what I just wrote. There seems to be an off by one issue with the build numbers. If you go on http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/10908/ , you'll get the details for build 10909 at the top but the URL is for 10908. So I'm guessing all the builds we are showing are the correct ones by their numbers are all off by one. Maybe @ZhilkinSerg or @narc0tiq can help us with that? Was something changed in the CI configs recently?

**Comment by remyroy** [comment]
@GGgatherer So you are seeing the latest build available as 10904 in the available builds list and the changelog stops at 10903 (10909 and 10908 at the time of writing this) for instance, but I think they are the same build, just with different numbers that are off by one. Their *names* are different but I believe they are the same. This is somewhat out of my ability to fix, but I'm sure those working of the system that creates those builds will fix it soon™ or that a solution will be provided shortly.

**Comment by ZhilkinSerg** [comment]
It should be resolved now.
