### ISSUE TITLE
Cataclysm++

### ISSUE THREAD

**Issue by drugl007** [remyroy/CDDA-Game-Launcher#482]
* Name: [Enter the name of the mod]
* Url: [Enter the Url where we can find the mod]
* Author: [Enter the name of the author]
* Homepage: [Enter the Url of the author website or where the mod was published]
* Mod not found in version: 1.4.11

**Comment by ZhilkinSerg** [comment]
Cataclysm++ is there:

![image](https://user-images.githubusercontent.com/16213433/90733748-a907e600-e2d5-11ea-972d-a4ee02f16e6e.png)

**Comment by Eddyskingdom** [comment]
just close it then
