### ISSUE TITLE
Add Otopack soundpack to the repository

### ISSUE THREAD

**Issue by LaVeyanFiend** [remyroy/CDDA-Game-Launcher#484]
* Name: Otopack
* Url: https://github.com/Kenan2000/Otopack-Mods-Updates
* Author: @Kenan2000
* Homepage: https://github.com/Kenan2000/Otopack-Mods-Updates
* Soundpack not found in version: 1.4.11

Technically a duplicate of #480, which wasn't filled out correctly.

**Comment by Kenan2000** [comment]
Thank you for this, @LaVeyanFiend , really appreciate this! 😃 
Now could you give me some advice @remyroy  - if I decide to upload my mods to the launcher should I make an issue or PR?

**Comment by remyroy** [comment]
@Kenan2000 PR is the best and easiest way for me. If not, you can simply provide me with these information in an issue and I'll add it:

* Name: [Enter the name of the mod]
* Url: [Enter the Url where we can find the mod]
* Author: [Enter the name of the author]
* Homepage: [Enter the Url of the author website or where the mod was published]
* Mod not found in version: 1.4.11

**Comment by kenneth-ellis** [comment]
Is Otopack included in the launcher now? I don't see it in the Soundpacks list in my install.

**Comment by remyroy** [comment]
The soundpack has been added with de1063a5141d0ffc649bb8a57a486e940924aae1 . It will be part of the next release.
