### ISSUE TITLE
Add this new soundpack to the repository

### ISSUE THREAD

**Issue by PartridgeProgramming** [remyroy/CDDA-Game-Launcher#490]
* Name: Otopack
* Url: https://github.com/Kenan2000/Otopack-Mods-Updates
* Author: Kenan2000
* Homepage: https://github.com/Kenan2000
* Soundpack not found in version: 1.4.11

**Comment by remyroy** [comment]
This is a duplicate of #484 . This soundpack was included recently and will be part of the next release.
