### ISSUE TITLE
Trojan:Win32/Wacatac.D4!ml

### ISSUE THREAD

**Issue by konrafx** [remyroy/CDDA-Game-Launcher#493]
Hi im new here so hope this belongs here. Might be silly but... still droping it here.

Windows defender quarantined:  :\CDDA Game Launcher\launcher.exe  and
\Start Menu\Programs\CDDA Game Launcher.lnk as a Trojan :Win32/Wacatac.D4!ml .

**Comment by remyroy** [comment]
See [the FAQ question and answer](https://github.com/remyroy/CDDA-Game-Launcher#my-antivirus-product-detected-the-launcher-as-a-threat-what-can-i-do) about this.

**Comment by konrafx** [comment]
Thanks for reply, I feel much less paranoid now. Sorry for not going to FAQ first.
