### ISSUE TITLE
Windows defended detects a trojan and deletes the launcher

### ISSUE THREAD

**Issue by meelock** [remyroy/CDDA-Game-Launcher#494]
**Describe the bug**
Detected: Trojan:Win32/Wacatac.D4!ml 
Status: Quarantined
Date: 9/21/2020 1:00 PM
Details: This program is dangerous and executes commands from an attacker.

Affected Items: 
file: C:\Users\elish\AppData\Local\Programs\CDDA Game Launcher\launcher.exe
file: C:\Users\elish\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\CDDA Game Launcher.lnk
startup: C:\Users\elish\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\CDDA Game Launcher.lnk

**To Reproduce**
Start the launcher after downloading it

**Expected behavior**
The launcher not to be quarantined.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/6434568/93815598-14addd80-fc0b-11ea-96b7-38bc0b1e57b5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.4.12

**Comment by meelock** [comment]
Duplicate of #462, my bad

**Comment by meelock** [comment]
Wait, no...  this is something else it seems.

**Comment by A4Brogan** [comment]
I am also having this issue, as Windows Defender apparently thinks it's Wacatac.D4!ml

**Comment by remyroy** [comment]
This is not a bug with the launcher per say. This is a recurrent issue with poor antivirus products. See [this FAQ question](https://github.com/remyroy/CDDA-Game-Launcher#my-antivirus-product-detected-the-launcher-as-a-threat-what-can-i-do) about it.

**Comment by dissyllabic** [comment]
Same issue here - and @remyroy : unfortunately it does not matter whether it is poor antivirus, the unwashed masses ie. 80% of the users will get this error and let the antivirus block the launcher.exe and move unto another product or not use the launcher :(

**Comment by zivedo** [comment]
I have the same problem with the launcher and windows defender. The antivirus product plays no role at all. There is a code in the launcher that looks like a security hole and therefore the antivirus program warns. Calling an antivirus tool bad just because it warns about a possible problem is the wrong approach. An antivirus tool is bad if it would ignore the problem.

**Comment by RainbyPlays** [comment]
So, i have had this same problem and thought it was something else, and it winds up being the launcher (which i also deleted) and i also scan my entire system to be safe, and it winds up being a launcher error/compromise. Welp, better to overreact then not react enough.

**Comment by Inglonias** [comment]
reverting to 1.4.11 works around this issue for now.

**Comment by ZhilkinSerg** [comment]
> Same issue here - and @remyroy : unfortunately it does not matter whether it is poor antivirus, the unwashed masses ie. 80% of the users will get this error and let the antivirus block the launcher.exe and move unto another product or not use the launcher until it is fixed. I am a keen supporter of your efforts to make an awesome product but have moved to the 1.4.1.1 version, because I can't be bothered to f*uck around with my Windows defender settings because of one program being falsely flagged as containing a virus. So I am looking fwd to the next version being built in a fashion so as to not being flagged as a trojan.

The thing launcher does (downloading binaries from Internet, extracting and launching them) will always trigger shitty heuristic algorithms.

**Comment by Inglonias** [comment]
I don't know how correct that is, since the previous version of the launcher doesn't trigger said shitty heuristics.

**Comment by Zireael07** [comment]
@Inglonias: That's because more and more "av" products include a popularity metric - if it's not popular, treat is as a danger. Which sucks for any products which are niche and/or update often. And this launcher ticks both of those boxes, being both niche and having new executables often.

**Comment by ZhilkinSerg** [comment]
> I don't know how correct that is, since the previous version of the launcher doesn't trigger said shitty heuristics.

Yeah, current version does not trigger it now just as it won't trigger in the future and just as previous versions triggered it in the past.
