### ISSUE TITLE
Unable to generate a valid starting location Shelter

### ISSUE THREAD

**Issue by Aanokint** [remyroy/CDDA-Game-Launcher#495]
Receiving the following when I attempt to launch from Character creation:
Unable to generate a valid starting location Shelter [sloc_dks_shelter] in a radius of 3 overmaps, please report this failure.

Version: 0.E-6161-gac84e5c (tiles)
Build: 11026
Branch: Experimental
Platform: Windows x64
Launcher: 1.4.11 - 1.4.12 is available but Windows Defender throws a fit, as noted in other reports.

Mod list: All default sans Dinomod, No blacklist mods, all Balance mods
All world gen values left as default

Char Gen: Multi Pool, Evacuee, Druid. default stats, Traits [Thick-skinned, tough, tough feet, Druid, Facial Hair: beard, Hair: red, 'fro, RP: Medic, Skin Tone: light, default stats

Given all above settings, I have consistently seen the error three times.

**Comment by ZhilkinSerg** [comment]
This has nothing to do with launcher.

**Comment by remyroy** [comment]
See https://github.com/remyroy/CDDA-Game-Launcher#i-found-an-issue-with-the-game-itself-or-i-would-like-to-make-a-suggestion-for-the-game-itself-what-should-i-do
