### ISSUE TITLE
Secronom has incorrect url

### ISSUE THREAD

**Issue by adinsx** [remyroy/CDDA-Game-Launcher#496]
**Describe the bug**
Secronom url is outdated

**To Reproduce**
1. Try to install Secronom from the repository.
2. Notice the statusbar says "Selected file is a bad archive file". Because the url in the details is a 404.

**Expected behavior**
Expected Secronom to install.

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Current url is: https://github.com/Kenan2000/Secronom-Zombies/raw/master/secronom.zip

**Comment by remyroy** [comment]
This should be fixed with 8a8c3b48f1707983dc9ca3645ae4429f38fa7eb8 . Thanks for the report.
