### ISSUE TITLE
Launcer's changelog displays the wrong build number

### ISSUE THREAD

**Issue by Unfortun3** [remyroy/CDDA-Game-Launcher#497]
**Describe the bug**
So as title says there is something wrong with build number in launcher's changelog. Atm latest changes are supposed to be for build #11056 and it displays build #11054, Problem started occurring after build #11037 there is a gap between builds 11037-11040(http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/) and that's probably what caused the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/67174940/94933186-bae2c880-04d2-11eb-8a0c-5e2a472625df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Launcher version: 1.4.12

**Comment by remyroy** [comment]
@ZhilkinSerg Is this something similar to #479 ?

**Comment by Unfortun3** [comment]
In that case you've stated that it's not pulling latest build changelog. In my case changelog contains latest build changes but build number is incorrect.

**Comment by remyroy** [comment]
It seems to be back to normal now.

We have little control over issues like this. We are mainly fetching information around in different systems (mainly github and Jenkins).

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg Is this something similar to #479 ?

Yeah, it is the same thing with build number of child build job off by one. I resolved it some time during the weekend.
