### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by p-dimi** [remyroy/CDDA-Game-Launcher#499]
* Name: Useful Helicopters
* Url: https://github.com/SpadeDraco/useful_helicopters
* Author: SpadeDraco
* Homepage: https://github.com/SpadeDraco/useful_helicopters
* Mod not found in version: 1.4.12

**Comment by remyroy** [comment]
It was just added with 7585b68930f1cbdb84a7880cc9f8640dad3fa026 . It will be part of the next release. Thanks.
