### ISSUE TITLE
[Suggestion] Option to retain a copy of the downloaded zip file when updating.

### ISSUE THREAD

**Issue by Malkeus** [remyroy/CDDA-Game-Launcher#5]
I often break things when I'm making changes. It's handy to have a copy of the zip file to refer to for reference or to replace a file. This option would save me a step and a bit of bandwidth as well. 

Also, and possibly related, where does the launcher save it's data? It remembers which directory I've pointed it at between sessions. I keep my game on a usb drive because I'm often moving between computers, will the launcher lose the directory when I start it on a different computer?

**Comment by remyroy** [comment]
Preserving a copy of the zip should be easy enough. I'll try to add it in the next release.

The launcher settings are kept in `%LOCALAPPDATA%\CDDA Game Launcher` but it should be easy to remake them on your other computers instead of copying it.

**Comment by Malkeus** [comment]
It's simple enough to reselect the directory now, but it could get to be a pain when you've added a few options. Will it read it from the local directory if I copy the settings there?

**Comment by Malkeus** [comment]
Hmm, it doesn't read it locally, but if I rename my catadda directory to cdda it works just fine on clean startup, so that's nice. I have to remember to check the 'don't move save directory' box, but thats ok too.

**Comment by remyroy** [comment]
I could add the possibility of checking the current directory for the settings file but it might have some weird side effects like if your use drive is on a different letter when you switch computer, it will keep pointing the the previous letter (on your other computer).

**Comment by Malkeus** [comment]
hmm...I didn't think of that possibility. ignore that pr I made then. Wait...tell me if it would have worked first, and then ignore it haha

**Comment by Malkeus** [comment]
It's ok as it works now, I just need to check a box before updating after I move to a different computer.

**Comment by remyroy** [comment]
This has been implemented in 773b039c594bdcf85c260f4b7b63ed04ef92838f and will be part of the next release.
