### ISSUE TITLE
the game screen is blank but still responds to commands.

### ISSUE THREAD

**Issue by fish-from-hell** [remyroy/CDDA-Game-Launcher#500]
Whenever I run the game with the launcher, the screen is completely blank, but I can still move over to the MOTD thing on the main screen and the motd comes up, but nothing else comes up.

**Comment by remyroy** [comment]
What happens if you launch the game without the launcher?

**Comment by fish-from-hell** [comment]
The screen and such comes up, so it may be a problem concerning the launcher.

**Comment by fish-from-hell** [comment]
Ok, I deleted all the files for the launcher, then reinstalled it, and  that seemed to fix it. I reckon that I accidently corrupted the files somehow, because I checked the log file and it said that whenever it tried to start, it got errors because of a missing XML element.
