### ISSUE TITLE
Cdda game launcher fails to start?

### ISSUE THREAD

**Issue by SirClarke** [remyroy/CDDA-Game-Launcher#507]
**Describe the bug**
I try to open the launcher and it loads part of the way then stops and freezes giving a (Not responding) Msg

**To Reproduce**
Open the Launcher

**Expected behavior**
It to start and Load the changelog or let me start the game

**Screenshots**
![image](https://user-images.githubusercontent.com/31796878/98009477-93c63200-1dc3-11eb-9954-d01a28ad4ee8.png)

**Desktop (please complete the following information):**
 - OS: Windows Ten

**Additional context**
Not that I know of sorry

**Comment by Scorch-Mechanic** [comment]
Can confirm. Attempted fix by deleting config.db as described in the readme, that did not resolve the issue.

**Comment by Lordflickshot** [comment]
Same thing is happening to me

**Comment by Rumbers** [comment]
Same here, even on fresh install to new location

**Comment by Rumbers** [comment]
![image](https://user-images.githubusercontent.com/14980882/98012881-83c54700-1df1-11eb-980e-33633a8d15f8.png)
Perhaps related to these responses... they look to to me but maybe schema has changed?
![image](https://user-images.githubusercontent.com/14980882/98013062-c7b84c00-1df1-11eb-8c8f-8affe534d5b5.png)

**Comment by Lazulf** [comment]
im having the same problem, launchers crashing as it tries to fetch the latest build. any word on a fix on this yet?

**Comment by Lazulf** [comment]
i was looking at the app folder in appdata and came across this output, do you guys have the same results?
![image](https://user-images.githubusercontent.com/73902222/98016184-85234f00-1db2-11eb-82eb-d73a4bfb1e54.png)

**Comment by Scorch-Mechanic** [comment]
`2020-11-03 09:16:38,949 - cddagl - INFO - CDDA Game Launcher started: 1.4.12
2020-11-03 09:16:40,218 - cddagl - CRITICAL - Global error:
Launcher version: 1.4.12
Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'strip'
Traceback:
  File "cddagl\ui\views\main.py", line 3377, in run
  File "cddagl\functions.py", line 34, in unique
  File "cddagl\ui\views\main.py", line 3375, in <lambda>
`
Yeah, but I'll be blowed if I know what it means. I'm not afraid of computers, but programming is a black art as far as I'm concerned.

**Comment by Rumbers** [comment]
Yeah it's failing to read changelog_xml  - i dont know python to change it
Code:
```
build_changes = build_data.findall(r'.//changeSet/item/msg')
build_changes = map(lambda x: html.escape(**x.text.strip(),** True),
                                build_changes)
```

**Comment by Lamandus** [comment]
can confirm

**Comment by Rumbers** [comment]
It's this element in the build report

![image](https://user-images.githubusercontent.com/14980882/98022712-dc024600-1dfd-11eb-9a3b-0c3fea4d520b.png)

**Comment by remyroy** [comment]
I can confirm. Let's see if we can fix this quickly.

**Comment by remyroy** [comment]
This should be fixed with 282a0cc62ab1f160fae7499fb7d714037735fd61 . It will be part of the next release which should be done shortly.

**Comment by remyroy** [comment]
Version 1.4.13 should fix this issue. The self-updating feature of the launcher might not work if the launcher crashes before it can self-update. You might need to [manually download and install the latest release](https://github.com/remyroy/CDDA-Game-Launcher/releases).

**Comment by SirClarke** [comment]
Thanks a lot, man keep up the great work
