### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by Entity-y** [remyroy/CDDA-Game-Launcher#511]
* Name: [OG_Drugs]
* Url: [https://discourse.cataclysmdda.org/t/original-drug-names/25335]
* Author: [Entity-y]
* Homepage: [https://github.com/Entity-y/OG_Drugs]
* Mod not found in version: 1.4.13

**Comment by remyroy** [comment]
Is that mod working? The mod_info.json does not even have an ident value.

**Comment by Entity-y** [comment]
Mod works, and updated modinfo.json to have ident value.

**Comment by remyroy** [comment]
Added with 30130141985fc56f8af4a9068eb47d57fb0a8fc4 . It will be part of the next release.
