### ISSUE TITLE
Feature request: show commit links

### ISSUE THREAD

**Issue by 8street** [remyroy/CDDA-Game-Launcher#512]
**Is your feature request related to a problem? Please describe.**

In the Launcher there are web links in change log (eg #12345). But not all changes have web links. Can you add links to commits?

It seems this can be obtained with the command: [commitId](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/api/xml?tree=builds[number,timestamp,building,result,changeSet[items[msg,commitId]],runs[result,fullDisplayName]]&xpath=//build&wrapper=builds)

So, the link consists of "https://github.com/CleverRaven/Cataclysm-DDA/commit/" + commitId

**Describe the solution you'd like**

Changelog for example:

- Changes1 (#_link1_)
- Changes2 (Commit: _link2_)

**Describe alternatives you've considered**

**Additional context**

**Comment by remyroy** [comment]
That seems reasonable. Let's see if I can implement this quickly 😉

**Comment by remyroy** [comment]
It does clutter the change log a little, but it should be fine for most. Completed in 991a99bbb303d5921f81995bfae8386fd345581d . It will be part of the next release.
