### ISSUE TITLE
Available build not loading

### ISSUE THREAD

**Issue by SirClarke** [remyroy/CDDA-Game-Launcher#515]
**Describe the bug**
It will not load past the Available build number 11203

**To Reproduce**
Open the Launcher

**Expected behavior**
Download the new update

**Screenshots**
![image](https://user-images.githubusercontent.com/31796878/101071115-28aa7f80-356a-11eb-9c85-ba2ac4870118.png)

**Desktop (please complete the following information):**
Windows Ten
Using cddagl_installer_v1.4.13

**Additional context**
Not sure this helps but on here http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/ It says some of the builds have failed but I don't know if that matters...

**Comment by remyroy** [comment]
The launcher only sees [the releases on Github](https://github.com/CleverRaven/Cataclysm-DDA/releases). If you look carefully, you'll see that those last few releases don't have the binaries.

@ZhilkinSerg @narc0tiq Is there an issue with CI server uploading to Github?

**Comment by SirClarke** [comment]
oh I see I'm just glad it sounds like I have not broken something thanks for getting back to me so soon

**Comment by morthein** [comment]
Just about to report this myself, stuck on 11203 for a few days, thought maybe I broke mine.

**Comment by SirClarke** [comment]
Seems to have started updating now should I close this now?

**Comment by remyroy** [comment]
> Seems to have started updating now should I close this now?

Sure

**Comment by SirClarke** [comment]
Thanks again for your time

**Comment by ZhilkinSerg** [comment]
Build server has its troubles. Just wait out and builds will eventually go through.
