### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by NancokPS2** [remyroy/CDDA-Game-Launcher#517]
* Name: [Mole Mutations]
* Url: [https://github.com/NancokPS2/Mole-Mutation]
* Author: [Nancok]
* Homepage: [https://github.com/NancokPS2/Mole-Mutation]
* Mod not found in version: 1.4.13

**Comment by remyroy** [comment]
Added with 29af671e29048ed7b39e9c4d195b582c2e7fb1b2 . It will be part of the next release.
