### ISSUE TITLE
Broken mod link

### ISSUE THREAD

**Issue by NyarlathotepZERO** [remyroy/CDDA-Game-Launcher#523]
Link is not working for https://nofile.io/f/fpzg9u6S0om/More+Buildings+&+Locations!.rar

also: https://nofile.io/f/JHWXQPk80Uu/Whaleys+Big+River+Building+Pack.zip

**Comment by remyroy** [comment]
Yeah, all nofile links are dead. I'll remove them for now and see if they come up later or somewhere else.
