### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by martinrhan** [remyroy/CDDA-Game-Launcher#524]
* Name: Magiclysm No Class Limit
* Url: https://github.com/martinrhan/Magiclysm_No_Class_Limit
* Author: martinrhan
* Homepage: https://github.com/martinrhan/Magiclysm_No_Class_Limit
* Mod not found in version: 1.4.14

**Comment by remyroy** [comment]
Added wtih 3ffb36dee718b3d18edc434795adb06be9225bb8 . It will be part of the next release.
