### ISSUE TITLE
Suggestion: Add confirmation to "Restore previous version"

### ISSUE THREAD

**Issue by harald921** [remyroy/CDDA-Game-Launcher#53]
I just learned the hard way why that'd be a good idea

**Comment by remyroy** [comment]
Have you tried cancelling the restoration? The launcher goes to great length to make sure nothing important is deleted.

The process of restoring your previous version start by moving the current game in a temporary directory. It than moves the previous game files in the current directory and than moves back the *old* current game into the previous directory. Nothing should be lost in the process. Restoring twice should bring back the original version.

**Comment by harald921** [comment]
Oh. I didn't know that. Thanks for the info!
