### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by retsuyama** [remyroy/CDDA-Game-Launcher#535]
* Name: AdvancedGear-CDDA-Mod
* Url: https://github.com/Lorith/AdvancedGear-CDDA-Mod/archive/master.zip
* Author: Shard (Lorith)
* Homepage: https://github.com/Lorith/AdvancedGear-CDDA-Mod
* Mod not found in version: 0.E-3 (tiles)

**Comment by remyroy** [comment]
Added with 2e24f2640ff3871791291035154b7d156c1b5b67 . It will be part of the next release.
