### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by AndrewLetailleur** [remyroy/CDDA-Game-Launcher#541]
* Name: Youkai Enemies
* Url: https://github.com/Toltetix/cdda-youkai-mod
* Author: Toltetix
* Homepage: https://github.com/Toltetix/cdda-youkai-mod
* Mod not found in version: 1.4.14

**Comment by remyroy** [comment]
Added with ae2baaac883f202defbb8fc82466800e2fbe0367 . It will be part of the next release.
