### ISSUE TITLE
Viewing MOTD deletes EXE on portable version

### ISSUE THREAD

**Issue by MitztheKat** [remyroy/CDDA-Game-Launcher#547]
**Describe the bug**
I am unable to use the launcher now, As I was scrolling through MOTD the application closed itself, and shortly after i saw the CDDA launcher exe hard-delete itself. I checked my recycle bin and it is not there. I checked my antivirus and it did not state that anything has been removed within the time it's been installed. 

**To Reproduce**
1. Open CDDA experimental through the launcher
2. go to MOTD
3. Keep scrolling with down
4. see crash, and watch the exe delete itself

**Expected behavior**
The MOTD should reach the end just fine and not crash and implode the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/29964282/114050222-14e59180-985a-11eb-8032-9c79354dd2ff.png)
![image](https://user-images.githubusercontent.com/29964282/114050534-5a09c380-985a-11eb-9574-e24c7c50cc89.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 home
 - touch screen, no mouse connected

**Additional context**

**Comment by Zireael07** [comment]
There is no way that CDDA can delete itself. Many antiviruses hide logs in weird places and/or make it difficult to reverse quarantining/file deletion.
Or you have a legitimate virus on your computer that deleted CDDA...

**Comment by MitztheKat** [comment]
oh ok, it seems the app.log was a false positive in McAfee. IDK why, but it was. Might want to look into this, idk.
fukken hell, my apologies.
