### ISSUE TITLE
Problem installing/updating the launcher

### ISSUE THREAD

**Issue by RogerioPiatek** [remyroy/CDDA-Game-Launcher#550]
**Describe the bug**
So, I tried updating launcher with the installer, but tells me it's already installed, (I deleted the folder already), the launcher try to delete but don't work, ask to reinstall, don't work too, after that show me a error, actually just portable works.

**To Reproduce**
1. Open the installer
2. He tells me the game is already installed, confirm to delete, don't work, then confirm to reinstall.
3. A error message appears

**Expected behavior**
The launcher delete (or see I already deleted the main folder) and install the new version

**Screenshots**
![image](https://user-images.githubusercontent.com/74259272/115132322-88fc0400-9fd5-11eb-9f32-2771b0295794.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Sinanzee** [comment]
I'm also having trouble fetching the changelogs. Wondering if the two issues are connected.

**Comment by ZhilkinSerg** [comment]
> I'm also having trouble fetching the changelogs. Wondering if the two issues are connected.

They are not.

**Comment by RogerioPiatek** [comment]
> > I'm also having trouble fetching the changelogs. Wondering if the two issues are connected.
> 
> They are not.

Any idea? Later I'll see if I can uninstall using Windows instead of just delete the folder.

**Comment by RogerioPiatek** [comment]
So, after some try, I really need to delete in Windows, after that all things happen normally, ask me where I want to install and all that.
