### ISSUE TITLE
I'm not being able to update the game.

### ISSUE THREAD

**Issue by OmeleteDuFroMago** [remyroy/CDDA-Game-Launcher#551]
**Describe the bug**
I'm sorry if this was already posted cuz i can't find a post about it. When i open the launcher it just says this and i can't update.

**To Reproduce**
Just open the launcher.

**Screenshots**
![image](https://user-images.githubusercontent.com/26847612/115332619-8e408680-a16e-11eb-8f19-b7816da71e8b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8

**Comment by ZhilkinSerg** [comment]
You can update regardless of changelog parsing status - just select version from the "Available builds" dropdown and press "Update" button.

**Comment by OmeleteDuFroMago** [comment]
> 
> 
> You can update regardless of changelog parsing status - just select version from the "Available builds" dropdown and press "Update" button.

Are you sure? unless the last update was legit 5 days ago it only shows me the one from 5 days ago.

**Comment by ZhilkinSerg** [comment]
Did you try to select build number from the dropdown and press Update button?

**Comment by remyroy** [comment]
The build server from which we are pulling changelog is currently down. https://ci.narc.ro/ @narc0tiq Are you still involved with CataclysmDDA?

**Comment by remyroy** [comment]
The latest experimental release shown on https://cataclysmdda.org/experimental/ is the same one shown in the launcher which are the ones available on the official github releases: https://github.com/CleverRaven/Cataclysm-DDA/releases . We are pulling information from there so we are limited to what is available there.

**Comment by narc0tiq** [comment]
Not so much involved, but I didn't shut down the build machine - yet I see
that it is down. I'm going to have to ask around. Cheers!

**Comment by OmeleteDuFroMago** [comment]
> 
> 
> The latest experimental release shown on https://cataclysmdda.org/experimental/ is the same one shown in the launcher which are the ones available on the official github releases: https://github.com/CleverRaven/Cataclysm-DDA/releases . We are pulling information from there so we are limited to what is available there.
Ooh i see, i didn't find much information about it around so i tought the problem was with me, appreciate tho.
