### ISSUE TITLE
Point the launcher at the new build system

### ISSUE THREAD

**Issue by Inglonias** [remyroy/CDDA-Game-Launcher#557]
**Is your feature request related to a problem? Please describe.**
With the Jenkins build bot being migrated away from in favor of Github actions, the launcher can no longer be used to update the game.

**Describe the solution you'd like**
Point the launcher at the new build system.

**Describe alternatives you've considered**
I dunno. I could learn enough python to do it myself, I guess? That may take a while, and it sounds like a lot of work.

**Additional context**

**Comment by remyroy** [comment]
The launcher should be able to get the new builds with this recents change: f57b3186ee5630881a00c317c36a46fd04df7b1c . It will be part of the next release. I'm in the process of improving the executable bundle process so it will be less likely to trigger AV products. This might take a little while.

**Comment by kevingranade** [comment]
To be clear, it should be pretty straightforward to get the new build artifacts from the github release API, but the more iffy thing is the changelog since that was being served by narc.ro and we don't have a 1:1 replacement for that.

**Comment by Inglonias** [comment]
Doesn't the build action occur every time there's a commit? Use the commit message as the changelog.

**Comment by remyroy** [comment]
The changelog has been removed when selecting the experimental branch until there is a replacement.

**Comment by kevingranade** [comment]
No, it is triggered on merge, which can be an arbitrary number of commits, and we just pushed a change that prevents overlapping releases, so there will be multiple merges per release if they're fast enough.  What I'm thinking is the list of commit messages can either be retrieved from the github API or maybe we can write it to the description of the release.

**Comment by kevingranade** [comment]
It looks like the commit span doesn't make it into the release by default, so we need to capture something during the release process and write it to the release.

**Comment by ZhilkinSerg** [comment]
@remyroy
 
New experimental release tag naming scheme:

- `https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-YYYY-MM-DD-HHmm` (e.g. https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-05-14-1641).

New experimental release artifact naming scheme:

- Window 32 bit - `cdda-windows-tiles-x32-YYYY-MM-DD-HHmm.zip` (e.g. https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2021-05-14-1641/cdda-windows-tiles-x32-2021-05-14-1641.zip)
- Window 64 bit - `cdda-windows-tiles-x64-YYYY-MM-DD-HHmm.zip` (e.g. https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2021-05-14-1641/cdda-windows-tiles-x64-2021-05-14-1641.zip).

**Comment by remyroy** [comment]
I guess we'll need another update 😄

**Comment by remyroy** [comment]
@ZhilkinSerg

The new tag will break our ability to search by build number if it includes the date.

We can easily search for build `#33` if it uses the `experimental-33` tag like on this release: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/experimental-33

but we cannot search for build `#1641` if it uses the `cdda-experimental-2021-05-14-1641` tag (with the date in it) like on this release: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-05-14-1641

We can adjust for the date being in the asset name without any issue. Just that the tag naming will cause some issues.

**Comment by remyroy** [comment]
Or maybe we could use the full date and number at the end as the build number.

**Comment by remyroy** [comment]
This should be taken care of in 546fe9b2e4c5daa4c48fc5d2cc35f2ea3e38cff8

**Comment by ZhilkinSerg** [comment]
You can allow entering hyphens in addition to numbers to "Find build #" field (or use mask).
