### ISSUE TITLE
Missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by jwc1015** [remyroy/CDDA-Game-Launcher#559]
When I try to run the launcher, I get a message stating that api-ms-win-core-path-l1-1-0.dll is missing.
This has only happened after the launcher updated to version 1.5.3.
**To Reproduce**
Laptop with windows 7.
Update launcher to version 1.5.3.
Run.
**Desktop**
 - OS: Windows 7 (64-Bit)

**Comment by jwc1015** [comment]
I just saw that version 1.5.1 dropped support for 'old versions of Windows' and 'might not work with _unpatched_ Windows 7/8. However, I am unsure of what is meant by _patched_ Windows 7 - just a completely updated version? Or is there some kind of non-Microsoft patch that is being referred to?

**Comment by Apxangel1** [comment]
I tried to reinstall back to 1.5.1, but the issue still persisted.

**Comment by RDru** [comment]
I see some python 3.9 in folder names and this version no longer works under Windows 7.

**Comment by Apxangel1** [comment]
If win 7 **no more** then as someone wise said " time to update...

**Comment by RDru** [comment]
The sad part is I have no reason to update other than stuff stopping to work. I use Win 10 at work and I see no benefit over Win 7.

**Comment by ZhilkinSerg** [comment]
Latest version of Python (used in the latest launcher version) does not support Windows 7 or earlier versions.

**Comment by jwc1015** [comment]
> I tried to reinstall back to 1.5.1, but the issue still persisted.

Only the version before that and earlier works - 1.5.1 was the one that removed compatibility.

**Comment by jwc1015** [comment]
Thus, unless this is changed I will not be updating the launcher, sadly.

**Comment by remyroy** [comment]
We'll try to see if we can support Windows 7 with the next release.

**Comment by jwc1015** [comment]
Ah, ok! Thank you for the quick response; have a great day!

**Comment by remyroy** [comment]
You should retry with version >= 1.5.4

**Comment by jwc1015** [comment]
> You should retry with version >= 1.5.4

Ok! Thank you, for the quick response time and your work. Have a great day!
