### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Dennisaran** [remyroy/CDDA-Game-Launcher#57]
Hey, I thought I followed the step by step fairly well but it seems I must have made a mistake somewhere. I try the step where you test the launcher and what I get is this.

C:\Users\SomeGuy\Documents\Games\Cataclysm DDA\CDDA-Game-Launcher-master>python cd
dagl\launcher.py
Traceback (most recent call last):
  File "cddagl\launcher.py", line 29, in <module>
    from cddagl.ui import start_ui, ui_exception
  File "C:\Users\SomeGuy\Documents\Games\Cataclysm DDA\CDDA-Game-Launcher-master\c
ddagl\ui.py", line 43, in <module>
    from pywintypes import error as PyWinError
  File "C:\Python34\lib\site-packages\win32\lib\pywintypes.py", line 124, in <mo
dule>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python34\lib\site-packages\win32\lib\pywintypes.py", line 64, in __im
port_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed: The specified module could not be found.

I'm sure that this tells me what I'm doing wrong fairly obviously, but I was hoping for some help since I'm totally ignorant of what this means.

**Comment by remyroy** [comment]
Try this command to install some missing dependencies and try to launch the launcher again.

`pip install pywin32 pypiwin32`

**Comment by Dennisaran** [comment]
Yep! Didn't have Pywin32 installed. Thanks for your help!

**Comment by remyroy** [comment]
No problem.
