### ISSUE TITLE
Excepción no capturada: [Cargar un título]

### ISSUE THREAD

**Issue by whhduqjdjw** [remyroy/CDDA-Game-Launcher#578]
* Descripción: [Describa lo que hizo y qué sucedió]
* Versión: 1.5.5
* Sistema Operativo: Windows-10-10.0.19042-SP0 (64-bit)
* Tipo: `<class 'OSError'>`
* Value: [Errno 28] No space left on device
* Traceback:
```
  File "C:\Users\Jose bro\AppData\Local\Programs\CDDA Game Launcher\cddagl\ui\views\main.py", line 2818, in download_http_ready_read
    self.downloading_file.write(self.download_http_reply.readAll())

```

**Comment by remyroy** [comment]
Duplicate of #579
