### ISSUE TITLE
Unhandled exception: crash while updating to a new version

### ISSUE THREAD

**Issue by Clanf** [remyroy/CDDA-Game-Launcher#58]
got crash while updating to a new version, it made backup, deleted everything (besides backup and game and launcher .exe) and just died
- Description: [Enter what you did and what happened]
- Version: 1.2
- Type: `<class 'PermissionError'>`
- Value: [WinError 5] Отказано в доступе: 'D:\_GAMES\cdda\data'
- Traceback:

```
  File "cddagl\ui.py", line 2381, in timeout
  File "zipfile.py", line 1228, in extract
  File "zipfile.py", line 1287, in _extract_member

```

**Comment by remyroy** [comment]
Can you translate error value to English for me?

> [WinError 5] Отказано в доступе: 'D:\_GAMES\cdda\data'

**Comment by Clanf** [comment]
oh, my bad, it's "Access denied"

**Comment by remyroy** [comment]
This is a duplicate of #82 which has been solved.
