### ISSUE TITLE
Unhandled exception: Preventing the latest experimental-update today

### ISSUE THREAD

**Issue by Buck4r00b4nz41** [remyroy/CDDA-Game-Launcher#60]
* Description: While updating to the latest experimental-version the launcher "froze" and after pressing the cancel button this error popped up. Build 5151 is the last one working. Tried -52 to -55 and they all fail to update properly.

This game in conjunction with your very convenient and well made launcher made me create a github account! ;-)

* Version: 1.2
* Type: `<class 'AttributeError'>`
* Value: 'GameDirGroupBox' object has no attribute 'opened_exe'
* Traceback:
```
  File "cddagl\ui.py", line 1924, in update_game

```

**Comment by Buck4r00b4nz41** [comment]
Now I also got this one:

CDDA Game Launcher version: 1.2
Type: <class 'PermissionError'>
Value: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\CDDA Game Launcher\\moved-405d8c7f\\data\\mods\\More_Locations\\military_outpost\\mil_outpost_ublc_01.json'
Traceback:
File "cddagl\ui.py", line 1937, in update_game

File "cddagl\ui.py", line 2012, in restore_previous_content
File "shutil.py", line 537, in move
File "shutil.py", line 482, in rmtree
File "shutil.py", line 372, in _rmtree_unsafe
File "shutil.py", line 372, in _rmtree_unsafe
File "shutil.py", line 372, in _rmtree_unsafe
File "shutil.py", line 377, in _rmtree_unsafe
File "shutil.py", line 375, in _rmtree_unsafe

**Comment by remyroy** [comment]
Thanks for the report. I'll check it out.

**Comment by remyroy** [comment]
The latest experimental release do not have an executable file which is why it crash like this. Let me put something to prevent that.

**Comment by remyroy** [comment]
This should be fixed with changes in 2a12214266f68ac1a194b31f4924a7b7168c2235. A new version is being built to include this.
