### ISSUE TITLE
Error when mutating into spider / getting arachnid mutation

### ISSUE THREAD

**Issue by Spacer-1970** [remyroy/CDDA-Game-Launcher#612]
**Describe the bug**
When you get the arachnid mutation, whether through spider serums or the debug menu, you get an error saying that there is no valid mood_face found for: THRESH_SPIDER and if you continue to use spider serums after the error the game crashes

**To Reproduce**
[crash.log](https://github.com/remyroy/CDDA-Game-Launcher/files/7525646/crash.log)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0 1903

**Additional context**
Add any other context about the problem here
[cdda bug report.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/7525559/cdda.bug.report.txt)
.

**Comment by ZhilkinSerg** [comment]
Game bugs must be reported in game repo, not in launcher repo.

https://github.com/CleverRaven/Cataclysm-DDA/issues/new?assignees=&labels=&template=bug_report.yaml

**Comment by Spacer-1970** [comment]
Thanks i never knew i just used the launcher's help menu to report bugs and it took  me here
