### ISSUE TITLE
Unhandled exception: [Attemtping game update is broken]

### ISSUE THREAD

**Issue by SpaceCatHaxor** [remyroy/CDDA-Game-Launcher#613]
* Description: [haven't played in a minute, tried to update and can't]
* Version: 1.5.6
* OS: Windows-10-10.0.18362-SP0 (64-bit)
* Type: `<class 'PermissionError'>`
* Value: [WinError 5] Access is denied: 'C:\\Program Files\\CDDA\\previous_version'
* Traceback:
```
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2085, in completed_test
    self.clear_previous_dir()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2139, in clear_previous_dir
    self.backup_current_game()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2190, in backup_current_game
    os.makedirs(backup_dir)
  File "os.py", line 223, in makedirs

```

**Comment by ZhilkinSerg** [comment]
You do not have permissions to write to location launcher is installed into.

**Comment by SpaceCatHaxor** [comment]
After some investigation, I think this is an issue with Windows, not the CDDA launcher. For whatever reason, its ignoring all my security settings and my permissions, and anything installed in Program Files isn't allowed to modify anything. Regardless of what the permissions are actually set to, if I'm running as admin or normal user, etc. I moved the install to a different drive and it works for now. Its still frustrating, but its Microsoft causing the problem.
