### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by KeenEye333** [remyroy/CDDA-Game-Launcher#627]
* Name: [Achievements Expanded]
* Url: [https://github.com/KeenEye333/Achievements-Expanded/archive/master.zip]
* Author: [KeenEye333]
* Homepage: [https://github.com/KeenEye333/Achievements-Expanded]
* Mod not found in version: 1.5.6

**Comment by remyroy** [comment]
This project is now [unmaintained](https://github.com/remyroy/CDDA-Game-Launcher#unmaintained).
