### ISSUE TITLE
jenkins-latest/Windows_x64/Tiles (5155)

### ISSUE THREAD

**Issue by Honcharuk** [remyroy/CDDA-Game-Launcher#63]
No executable found in the downloaded archive.

**Comment by remyroy** [comment]
This is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/17422 . The issue is with the game builds, not the launcher. Use build 5151 which has an executable.

**Comment by Xelat84** [comment]
BTW launcher hangs when trying to update to build with missing exe. Probably need to make checks for that case.

**Comment by remyroy** [comment]
@Xelat84 That was fixed in 1.3

**Comment by Xelat84** [comment]
@remyroy yeah, thanks for that! Just checked for updates few hours ago and there was none. Now I see new update! Good job! :+1:
