### ISSUE TITLE
"Add to list" function can't find releases

### ISSUE THREAD

**Issue by sbenzaquen** [remyroy/CDDA-Game-Launcher#634]
**Describe the bug**
The "Add to list" feature to add builds to the list does not work.
The problem is in `NEW_BUILD_TAG`.

It says:

```
NEW_BUILD_TAG = lambda bn: f'experimental-{bn}'
```
when it should say
```
NEW_BUILD_TAG = lambda bn: f'cdda-experimental-{bn}'
```

Making this change locally fixes the issue.

**To Reproduce**
1. Find a release tag. One from the "Available builds" list does the job.
2. Type it in "Find build #"
3. Click "Add to list"
4. Error "Build # xxxxx not found on GitHub"

**Expected behavior**
The build is found and added to the list.

**Comment by Catsoul-lee** [comment]
No longer supported. Please turn to https://github.com/DazedNConfused-/CDDA-Game-Launcher for help
