### ISSUE TITLE
Launcher doesn't install nor update the game "[Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by Wilou1428** [remyroy/CDDA-Game-Launcher#636]
After few months break I've tried updating experimental branch game and it fails with "[Errno 2] No such file or directory: C:\\Users\\{my user name}\\AppData\\Local\\Temp\\cdda{random chars}\\". My system is Windows 10 I run it on x64.

![pythonw_Lx3YbOlDXD](https://user-images.githubusercontent.com/19410660/157735499-e7c53975-0fa2-4790-acd3-ebcd8477dbb1.png)

After the error I've checked the Temp folder and it did have the folder. I've tried running the launcher in admin the same error. I've uninstalled the launcher it left some empty folders, I've deleted them and installed the launcher again. Now it doesn't Install the game and fails with the same error and still creates the folder it cannot find, even in admin mode. I've tried installing in a different directory the same behaviour.

Is there a more verbose log file I can attach?

**Comment by pvorselaars** [comment]
Same here. It seems to be unable to download the builds from the experimental branch. Installing builds from the stable branch still works. However, the latest stable build, according to the launcher, is 0.F Frank-2 instead of 0.F Frank-3.

**Comment by remyroy** [comment]
This project is now unmaintained. You might wanna try this new project: https://github.com/DazedNConfused-/CDDA-Game-Launcher

**Comment by Wilou1428** [comment]
oh didn't know there was a fork change, thanks!
