### ISSUE TITLE
When trying to install game launcher throws Error no such file or directory

### ISSUE THREAD

**Issue by AlexanderBodnya** [remyroy/CDDA-Game-Launcher#638]
After clean installation on windows 11 when I try to install CDDA launcher shows error 'No such file or directory' pointing to folder in Temp. Folder is actually created but after I click on install once again.

1. Click 'install game'
2. Error no such files or directory $random_name_1
3. Click on install game once again
4. Directory $random_name_1 is created in Temp
5. Error no such file or directory $random_name_2 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Comment by remyroy** [comment]
This project is now [unmaintained](https://github.com/remyroy/CDDA-Game-Launcher#unmaintained) but there are a few alternatives if you look.

**Comment by AlexanderBodnya** [comment]
Thanks! Suggested installer works!
