### ISSUE TITLE
Installing the game on a directory erases the existing files without prompting.

### ISSUE THREAD

**Issue by mrZalli** [remyroy/CDDA-Game-Launcher#64]
I tried installing CDDA through this launcher, and the game directory given in the ui's directory bar was not the one I wanted to be the game directory.

Turns out that the installation process hard-erased everything from that folder, but luckily it was my dropbox folder and I was able to restore everything.

This is clearly very unsafe and potentially disastrous. Removal of all the files should be prompted or maybe even forbidden.

**Comment by remyroy** [comment]
The launcher goes to great lengths not to delete any file that could be important to you. Whenever it deletes files that could be important, it will prompt a confirmation from you. When doing an update or installing the game, it will move all files from the selected directory into the previous_version directory inside your game directory (unless you selected one of the settings to prevent that which is not the default behavior). When restoring the previous version, it will move all files from the selected directory into a temporary directory, it will move the previous version files into the selected directory and it will move the temporary files into the previous_version directory. This means that restoring your previous version twice should bring you back exactly where you were.

**Comment by mrZalli** [comment]
Oh, I did not notice that! I saw suddenly everything from my dropbox folder disappear and I guess I panicked.

Oh well there wasn't any pending changes so I might as well download everything back from the net.
