### ISSUE TITLE
An Unhandled exception: [The CDDA Game Launcher just Crached]

### ISSUE THREAD

**Issue by Dosbally** [remyroy/CDDA-Game-Launcher#65]
- version: 1.3.2
- Type: <class 'UnicodeDecodeError'>
- Value: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
- Traceback:
`File "cddagl\ui.py", line 2475, in copy_next_dir

File "cddagl\ui.py", line 2526, in post_extraction_step2
File "cddagl\ui.py", line 2423, in asset_name`

**Comment by remyroy** [comment]
Thanks for the report. I'll check it out.

**Comment by remyroy** [comment]
Duplicate of #75.
