### ISSUE TITLE
Unhandled exception: copying new game version

### ISSUE THREAD

**Issue by Kazzum** [remyroy/CDDA-Game-Launcher#67]
* Description: tried to update from Cataclysm version 4858 to 5307
* Version: 1.3.2
* Type: `<class 'UnicodeDecodeError'>`
* Value: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
* Traceback:
```
  File "cddagl\ui.py", line 2475, in copy_next_dir
  File "cddagl\ui.py", line 2526, in post_extraction_step2
  File "cddagl\ui.py", line 2423, in asset_name

```

**Comment by remyroy** [comment]
Thanks for the report. I'll check it out.

**Comment by Kazzum** [comment]
I have since replace the entire launcher and cataclysm directory as I wasn't to attached to it and it works fine now.

**Comment by remyroy** [comment]
Duplicate of #75.
