### ISSUE TITLE
Add this new soundpack to the repository

### ISSUE THREAD

**Issue by andrewisachump** [remyroy/CDDA-Game-Launcher#69]
* Name: [Enter the name of the soundpack]
* Url: [Enter the Url where we can find the soundpack]
* Author: [Enter the name of the author]
* Homepage: [Enter the Url of the author website or where the soundpack was published]
* Soundpack not found in version: 1.3.2

**Comment by remyroy** [comment]
You forgot to input the values for the name, url, author and homepage for this soundpack.

**Comment by remyroy** [comment]
If you know the soundpack, reopen a new issue.
