### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by solzerid** [remyroy/CDDA-Game-Launcher#77]
* Description: [

I Just updated to latest build
Error happened on first run after update

Ran Launcher
Clicked Launch
Avast shows cataclysm-tiles.exe as unknown file
Selected "I trust this file"
Then error popped up

Shortcut to launcher is set up to run as administrator
]

* Version: 1.3.3
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'PermissionError'>`
* Value: [WinError 5] Access is denied
* Traceback:
```
  File "cddagl\ui.py", line 975, in launch_game
  File "cddagl\ui.py", line 998, in launch_game_process
  File "subprocess.py", line 859, in __init__
  File "subprocess.py", line 1114, in _execute_child

```

**Comment by remyroy** [comment]
This is a config problem with Avast. We could detect it and show a message about it but it would still not launch because of Avast.

**Comment by solzerid** [comment]
The previous build caused the same avast popup to show, but it would still run when I selected that I trusted the file.

**Comment by remyroy** [comment]
Try again. I don't know exactly how Avast work, but that same procedure should solve this issue.

**Comment by solzerid** [comment]
There was possibly an update to Avast that caused the conflict. On second look, the popup was slightly different. I believe the option to ignore the warning before was "Run File Anyway" and now it is "I trust this file". Whitelisting fixed the permissions issue.

**Comment by remyroy** [comment]
Good to know. Closing.
