### ISSUE TITLE
Increase maximum number of backup saves

### ISSUE THREAD

**Issue by Moredread** [remyroy/CDDA-Game-Launcher#79]
I'm quite a hoarder, and 100 save backups aren't that much (for me XD). Is there a reason that limit is in place?

**Comment by remyroy** [comment]
I'll increase it to 1000 in the next release.

**Comment by Moredread** [comment]
cool :)

**Comment by remyroy** [comment]
This has been completed in 535d065cfa43039cb76793d99a24695526b4fb9d. It will be part on the next release which should be soon.
