### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by fdinh** [remyroy/CDDA-Game-Launcher#82]
- Description: [Enter what you did and what happened]
- Version: 1.3.4
- OS: Windows-10-10.0.14393 (64-bit)
- Type: `<class 'PermissionError'>`
- Value: [WinError 5] Access is denied: 'D:\Games\Roguelikes\CDDA\CataclysmDDA\data'
- Traceback:

```
  File "cddagl\ui.py", line 2436, in timeout
  File "zipfile.py", line 1228, in extract
  File "zipfile.py", line 1287, in _extract_member

```

**Comment by remyroy** [comment]
The launcher will now catch those operating system errors and will display them to the user instead of crashing. This has been added in a97903e750daca6bf0ca0c4dbf0c8802abfb518d and will be part of the next release.
