### ISSUE TITLE
Feature request: Confirmation dialogue on "Restore Previous Version"

### ISSUE THREAD

**Issue by Kiesman** [remyroy/CDDA-Game-Launcher#85]
It would be amazing to have a YES/NO confirmation dialogue on the Restore Previous Version button. It's awful when you accidentally click it and it reverts save data (occasionally).

**Comment by remyroy** [comment]
Restoring twice should always bring you back to where you were. The restore button also transform to a cancel button which can cancel the process if you made a mistake.

**Comment by theit8514** [comment]
I :+1: this, I just had a problem with CDDA and was attempting to restore a backup and accidentally clicked 'Restore Previous Version.' I encountered no confirmation dialog, and the UI of the launcher locked up. There was no cancel button and no indication that anything was happening. I believe you are running this on the UI thread which causes the UI changes to not update.

Closing the application causes corruption and loss of backups. There should be at least some indication of what will happen when you click the button.
