### ISSUE TITLE
Unhandled exception: [Launcher crashed, I think it was a bad version, not launcher]

### ISSUE THREAD

**Issue by Litppunk** [remyroy/CDDA-Game-Launcher#86]
* Description: [updated from one of yesterdays versions (about 6:PM) to a newer version 5881, I think.]
* Version: 1.3.5
* OS: Windows-XP-5.1.2600-SP3 (32-bit) [as a wineskin wrapper on OS X 10.9.5]
* Type: `<class 'pywintypes.error'>`
* Value: 87
* Traceback:
```
  File "cddagl\ui.py", line 2246, in completed_test
  File "cddagl\ui.py", line 2291, in backup_current_game
  File "cddagl\ui.py", line 165, in retry_rmtree
  File "cddagl\win32.py", line 545, in find_process_with_file_handle
  File "cddagl\win32.py", line 459, in list_handles

```
I think this issue is the version not the launcher, but I may be wrong.

**Comment by remyroy** [comment]
I think this is more likely related to Wine. The launcher call some win32 apis that might not be implemented or fully implemented in Wine. I'll check out this error when I have some time.

**Comment by Litppunk** [comment]
I have NEVER, had a problem with that before, but thats always possible
