### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by Litppunk** [remyroy/CDDA-Game-Launcher#87]
* Name: [PK's Rebalancing Mod]
* Url: [https://www.dropbox.com/s/il87ysjl85to0dc/PKs_Rebalancing.zip?dl=0]
* Author: [Pisskop]
* Homepage: [http://www.wiki.cataclysmdda.com/index.php?title=Pisskop%27s_Rebalancing_Mod#Pisskop.27s_Rebalancing_Mod]
* Mod not found in version: 1.3.5

**Comment by remyroy** [comment]
PK's Rebalancing Mod is already included in the base experimental game.  It is called PK's Reimagining in the list.

There are also changes in the way mods will be distributed. Eventually, they might get provided on Github with various releases and version with better support for API changes.

**Comment by Litppunk** [comment]
Odd I looked multiple times and didn't see it.

Neat. Pretty behind on my Cata V.V
