### ISSUE TITLE
Custom fonts deleting after update

### ISSUE THREAD

**Issue by egorzaderiy** [remyroy/CDDA-Game-Launcher#9]
After updating game to latest version, custom fonts will disappear from "\data\font\"

Steps to reproduce:
1. Copy font (i'm using terminus ttf) to "\data\font\". 
2. Update the game
Result: The custom fonts will disappear

Version of launcher - 0.4

**Comment by Malkeus** [comment]
did you check the previous_version folder? it's probably there. The whole original contents of the game directory are copied to previous_version directory before the update happens. Then it copies over sounds and mods and configs and memorials(?) and graveyard(?)? Not sure on those last two, ahven't paid attention that closely.

Could probably stand to check for extra content in that folder as well.

**Comment by remyroy** [comment]
It should be easy enough to add copying those custom fonts with the update. Let me check how they are found by the game and copy them.

**Comment by remyroy** [comment]
This is implemented in fdd83d61003abfd19e06e0421f23b77ff776c722 . It will be part of the next release.
