### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by becauseitsnecessary** [remyroy/CDDA-Game-Launcher#94]
[bullshit.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/695143/bullshit.txt)

Following the building guide, while getting a few thousand lines of warnings that mean nothing to me, I got the launcher.exe to build. On using it I get the error "Failed to execute script pyi_rth_qt5plugins" which also means nothing to me. 

Installed fine a year ago before I bought a new computer with Windows 10. Gibberish added to a text file and included.

**Comment by remyroy** [comment]
It seems there are issues with your PyQT installation. These kind of issues are out of scope for this project, sorry. Check out with pyinstaller or PyQT support.
