### ISSUE TITLE
Mods that don't come with the game or the launcher don't get copied to new versions

### ISSUE THREAD

**Issue by Taberone** [remyroy/CDDA-Game-Launcher#95]
If the mod isn't included in the game already or available to download through the launcher, the launcher apparently refuses to copy it over to any new versions when updating. This forces me to keep going back into the previous_version directory so I can copy and paste my mod into the updated version.

<a href="http://imgur.com/KSr43jy"><img src="http://i.imgur.com/KSr43jy.png" title="source: imgur.com" /></a>

This is one such example. The "Touhou" mod is something I've made myself, and it always gets left behind whenever the launcher updates. It might be in the mods folder now, but once I update it'll be back in the previous_version directory

**Comment by remyroy** [comment]
The launcher will preserve custom mods which have a unique `ident` value in modinfo.json that is not already part of the base game when updating the game. Make sure your custom mod has a different and unique `ident` value than those provided by the game and it should be preserved.

**Comment by Taberone** [comment]
`{
    "type": "MOD_INFO",
    "ident": "Touhou",
    "name": "Touhou Professions",
    "author": [ "Taberone" ],
    "description": "Touhou-inspired professions. Coregame balance not guaranteed.",
    "category": "touhou",
    "path": ""
}`

Thats what I have for Modinfo.json and it still didn't get preserved, although the Modinfo file isn't exactly "modinfo.json", its "touhou_Modinfo.json".

**Comment by remyroy** [comment]
Every mod need a file called `modinfo.json`. That will fix your issue.
