### ISSUE TITLE
Launch game after update

### ISSUE THREAD

**Issue by phillosopherp** [remyroy/CDDA-Game-Launcher#96]
* Description: [Enter what you did and what happened]
* Version: 1.3.8.2
* OS: Windows-10-10.0.14393 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'replace'
* Traceback:
```
  File "cddagl\ui.py", line 984, in launch_game
  File "cddagl\ui.py", line 1025, in launch_game_process
  File "html\__init__.py", line 19, in escape

```

**Comment by remyroy** [comment]
This should now be fixed with ea9c9b615150d097e1f196a96e920466df3ec493. It will be part of the next release.
