### ISSUE TITLE
The CDDA Game Launcher just crashed, An unhandled exception was raised. Here are the details.

### ISSUE THREAD

**Issue by ROTMG2013** [remyroy/CDDA-Game-Launcher#99]
* Description: I updated the game with one save and this is what happened. 
* Version: 1.3.8.2
* OS: Windows-10-10.0.14393 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'replace'
* Traceback:
* CDDA Game Launcher version: 1.3.8.2
```
  File "cddagl\ui.py", line 984, in launch_game
  File "cddagl\ui.py", line 1025, in launch_game_process
  File "html\__init__.py", line 19, in escape

```
![cdda_launcher_crash_capture](https://cloud.githubusercontent.com/assets/25410730/22401473/ed6754fa-e588-11e6-8553-2b198e9a334b.JPG)

**Comment by remyroy** [comment]
Thanks for the report. I'll check it out.

**Comment by ROTMG2013** [comment]
Thank you.

**Comment by ROTMG2013** [comment]
I think it was just the previous build that had that error because the new
update is working fine now.

Thank you for your time.
